### ISSUE TITLE
HPC Toolkit - Uso Real - Egeon - MPAS

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#104]
# Descrição

Usar o HPC Toolkit de forma real para analise do problema de super escalabilidade do modelo MPAS.

- Fixar em 128 cores (1 até 16 nós) - 
1 no 128 procs/nó, totalizando 128 procs.
2 nos 64 procs/nó, totalizando 128 procs.
4 nos 32 procs/nó, totalizando 128 procs.
8 nos 16 procs/nó, totalizando 128 procs.
16 nos 8 procs/nó, totalizando 128 procs.
32 nos 4 procs/nó, totalizando 128 procs.

- 1 hora de previsão (avaliar a janela da possibilidade)
- Compilador (usado na #128)
- Rodar com 15km e/ou 30km
- Setar métrica de cash_miss
- Executar
- Obter resultados das saídas e analisar

# Impactos

Não há impactos.

# Dependências

Compilação do modelo: #91
Execução-exemplo do modelo: #95
Issue #128

# Solução

(Notas João)
-  Saídas das rodadas disponíveis no FTP do GCC.
- Aberta issue #163 para continuidade das analises das rodadas desta issue.
- Aberta issue #164 para outras linhas de investigação apontadas nesta issue.

# Problemas encontrados

...

**Comment by joaomas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GCC-MONAN-62a3a783cb59a00014ce8e70/issues/monanadmin/monan/104?planning-poker) with Zenhub @carlosrenatosouza2 @robertopsouto

**Comment by carlosrenatosouza2** [comment]
# Lembretes:
- Memory affinity?
- PAPAI: qtos gflops?
