### ISSUE TITLE
HPC Toolkit - Analise super-linearidade MPAS no EGEON [SPIKE] 🔎

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#137]
### User Story

COMO Saulo,
QUEREMOS Compreender as causas da super-linearidade apresentadas no MPAS no Egeon,
PARA Atuar nos problemas apresentados e solidificar o conhecimento sobre o modelo.

### :clipboard: Critérios de aceite de conclusão da Issue

- Resgatar as rodadas do Santos Dummont que não apresentaram este comportamento realizando uma análise crítica.
- Descrever os passos necessários para os testes utilizando o compilador da AMD (aocc v4.0.0) se ainda forem viáveis.
- Analisar os apontamentos feitos no e-mail do Celso (ver detalhamento adicional abaixo) e apontar os passos futuros e requisitos necessários para os novos experimentos.
- Issue do tipo SPIKE (exploratória).

### Detalhamento adicional da atividade

- Testar usando o compilador da AMD; Executar o MPAS na Egeon com HPC Toolkit; Verificar a super linearidade (João - sprint passada,  mantida aqui para histórico);
- E-mail do Celso (11/8/2023):

B) Efeito de super-linearidade observado:
Devo confessar que nunca me deparei com nenhum caso onde a super-linearidade [que] não fosse resultado de algum efeito de caches. Entendo que os testes da Fig.6 foram realizados num esquema de "escalabilidade forte", ou seja, o mesmo tamanho de problema sendo executado com cada vez mais nós ou processadores. Isso é o mais comum em aplicações onde se procura obter a resposta no menor prazo possível. Contudo, isso leva a uma divisão cada vez maior do domínio, fazendo com que os sub-domínios para cada processador sejam cada vez menores, e se encaixem melhor nas caches do sistema. Uma alternativa seria realizar também um estudo com "escalabilidade fraca", onde se aumenta o tamanho do problema à medida que se usa mais nós. A idéia é manter o uso de memória por nó constante, de modo a eliminar aqueles efeitos de cache. Sei que isso pode ser mais trabalhoso de se construir (para cada número de nós seria necessário montar uma configuração do problema), mas essa seria, a meu ver, uma forma "justa" de comparação. Além disso, executar um "problema maior" (que pode significar melhor resolução, dada uma região fixa) deve ser também uma das metas de qualquer centro de previsão de tempo/clima.

### Impactos

_(... consequência técnica encontrada durante a execução da issue)_

### Dependências

Não há dependências.

### Solução

- [x]  Instalação do MPAS: instalada a versão v6.3
- [x]  Verificação da super linearidade no SDumont: em andamento
- [x]  Verificação do funcionamento do HPCToolkit:

- Verificação realizada no SDumont, onde a superlinearidade também foi observada (acrescentado em 15/09/2023)
- Rodada de 1h de integração, utilizando ate 8 nós computacionais (192 cores/MPI ranks)

<html>
<body>
<!DOCTYPE html>

#ranks | tempo (s) | Speed-up ideal | speeup | eff
-- | -- | -- | -- | --
24 | 1911,36 | 1 | 1,0 | 1,00
48 | 824,91 | 2 | 2,3 | 1,16
96 | 400,87 | 4 | 4,8 | 1,19
192 | 202,55 | 8 | 9,4 | 1,18

</body>
</html>

- Versão instalada no sistema (hpctoolkit-2022.10.01) requer que adaptações sejam realizadas nos scripts atuais, para seu correto funciomento.
- A opção `-I`, para informar o caminho de busca do código-fonte da aplicação, foi descontinuada:
  
```bash
hpcprof \
 -I /mnt/beegfs/roberto.souto/mpas/github/MPAS-Model_v6.3/+ \
 -S ${executable}.hpcstruct hpctoolkit-atmosphere_model-measurements-${SLURM_JOBID}

hpcprof -I /mnt/beegfs/roberto.souto/mpas/github/MPAS-Model_v6.3/+ -S atmosphere_model_v6.3_single.hpcstruct hpctoolkit-atmosphere_model-measurements-85049
hpcprof: invalid option -- 'I'
Usage: hpcprof [options]... <measurement files/directories>... 
```

Com a nova opção `-R`, sugerida nesta mais recente versão para substituir `-I`, não foi obtido até então resultado do perfil de desemenho da aplicação:

```bash
hpcprof \
 -R '/mnt/beegfs/roberto.souto/mpas/github/MPAS-Model_v6.3'='/mnt/beegfs/roberto.souto/mpas/github/MPAS-Model_v6.3' \
 -S ${executable}.hpcstruct hpctoolkit-atmosphere_model-measurements-${SLURM_JOBID}
```

Como sugestão, instalar versão anterior do HPCToolkit, tal como a versão hpctoolkit@2021.10.15, compatível com os scripts desenvolvidos até então no projeto.

### Problemas encontrados

- (João) A issue ficou em 'blocked' por um período devido a problemas de compilação do MPAS com o compilador da AMD [aocc v4.0.0].

### Conclusão

- (João) Desdobramento desta issue serão feitas em novas issues.

**Comment by joaomas** [comment]
Em blocked - consultando informações sobre o compilador da AMD a ser instalado.

**Comment by robertopsouto** [comment]
Oi, @joaomas. 
Na verdade o compilador da AMD (aocc v4.0.0) que foi instalado via spack na minha conta da Egeon parece estar ok. A questão é que há uma dificuldade em compilar o MPAS com este compilador. Vou continuar tentando descobrir o que pode estar acontecendo.
Um chamado ao suporte seria para solicitar a instalação do compilador da AMD, e também do OpenMPI, para uso de todos os usuários da Egeon.
