### ISSUE TITLE
Acompanhar apresentações do Seminário PCI - 2022

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#142]
- Acompanhar as apresentação do seminário PCI.

**Comment by klclaudio** [comment]
O Seminário foi interessante e chama a atenção algumas questões, que já apareceram no workshop do MONAN:
escolha do MPAS x FV3.
Uma apresentação de Josiane de Araújo Francelino, estudou importância do planejamento e os riscos envolvidos em grandes projetos (departamento de defesa EUA),  e discorreu sobre o sucesso do projeto atingir o objetivo principal estar associado às escolhas da tecnologia utilizada no momento do planejamento.

**Comment by klclaudio** [comment]
Para o seminário foi elaborado um conjunto  de slides com as principais atividades realizadas, e foi finalizado com as sugestões propostas.
