### ISSUE TITLE
RISC - Análise da solução HPE - Denis

### ISSUE THREAD

**Issue by deniseiras** [monanadmin/monan#145]
# Descrição
Deverá ser avaliada e questionada a proposta da empresa de acordo com as especificações da RFI.
A RFI e as propostas das empresas estão disponíveis no Google Drive do grupo GCC, pasta "RISC - RFI + Propostas", que pode ser visto através do link:
- https://drive.google.com/drive/folders/1QID1pCDCCVmSricwwL68IuGFQPgh6-0O?usp=share_link
# Impactos
# Dependências
# Solução
As anotações antes e depois da apresentação estão disponíveis no documento abaixo (somente para membros INPE)
https://drive.google.com/drive/folders/1h_u6OUJqcIl8FAsF8-ZVelqAIawDhK_G?usp=share_link

**Comment by deniseiras** [comment]
Perguntas e respostas dos fornecedores: https://rfi_sc.inpe.br/per_sc.html

**Comment by egkhamis** [comment]
solucoes HPE

sistema pinot:
2x amd epyc 7742 64-proc
até quanto dá para para aumentar o clock (padrao 2.25Ghz).. foi utilizado?
mpi rank order foi testado?
é possível fazer upgrade da memória RAM?
hpe slingshot 10 interconnects
é possivel incluir GPU no sistema? amd instinct mi250x gpu sim mas e NVIDIA H100?
tudo isso para novas tecnologias por 10 anos?
suporte, treinamento, manutencao
topologia Dragonfly, resfriamento por agua dentro das blades

bibliotecas foram compiladas com o mesmo compilador utilizado no brams? intel 2021.4.0

Benchmark do brams
instala wrf tambem?
só mpi
No hyper threads
Turbo boost on
srun -m plane=128 (alguma diretiva a mais para o boost)
grade 978x1009
6 instancias simultaneas?
dt=45
escala até 1024 (8 nós)… nao era até 9000proc?
dt=30
ultrapassa 2h

benchmark do mpas
diferença, usa openmp=4
39 nós, 1248 proc
não rodou 4 instancias simultaneas e sim sequenciais em 2horas de janela
nao rodou teste de escalabilidade

diretorios com resultados da validcao ainda disponiveis?
custo energetico estimado?

arquivos mus: quem é responsável pelo tratamento da água utilizada no sistema de refrigeracao? serao fornecidos os produtos?


DDP: 
PBS com 3 anos de suporte (item 24 do FCA diz ultima versão do Slurm)
soluçao de software.. e o singularity? (aparentemente nao solicitamos na RFI) matlab original? (item 51 do FCA diz 1 licença perpétua com 5 anos de suporte)
5x arm allinea essential.. só 1 ano de suporte? quantos processadores, nós? para 32 processos (ítem 23 arquivo FCA) 
hpe cray programing environment com 3 anos de suporte
treinamento
faltou eccodes (item 24 da RFI)
faltou julia (item 26 da RFI)
faltou anaconda (item 27 da RFI)
faltou spack (item 28 da RFI)
o que são os serviços?
preco: ~17 milhoes de reais (softwares que nao é deles/serviços/treinamentos)

FCA: 
anexo B
ítem 16 - parece falso: allinea essential (diferente do arm forge do ítem 20 da RFI) só 1 ano de suporte, PBS com 3 anos de suporte, hpe cray programing environment com 3 anos de suporte (vide item 
item 17 - todas as bibliotecas carregadas previamente também são chaveadas?
item 20 - quais são os ‘demais’ compiladores open source
item 21 - apenas compiladores Cray para GPU? quais outros?
ítem 62 - não fornece o tempo de treinamento para 5 pessoas.. nao especifica item 33.2 da RFI
item 66 - arquivo HPE INPE RFI com acesso a benchmark com prazo de visualizacao vencido (indisponivel)
item 68 - benchmark com escalabilidade faltando do mpas
item 69 - saidas dos modelos com acesso vencido
item 75 - aonde comprova pico de 1.659 Pflops no Linpack? nos benchmarks do brams e mpas?
item 68 - faltou o roadmap para o Cray EX2500, prometido para dezembro pois acabou de ser lancado em novembro
item 79 - valores em dolares (arquivo FCA) e reais (arquivo DDP) confusos
preço: ~20 milhões de dólares (hardware)
