### ISSUE TITLE
Formas de desenvolvimento: clone e fork

### ISSUE THREAD

**Issue by klclaudio** [monanadmin/monan#15]
# Descrição
Documentar  as formas de contribuição ao projeto: 

1 - *Clone* -  que é a situação de um desenvolvedor colaborador  
2 - *Fork* - que é a situação  de um desenvolvedor não colaborador (ie., não adicionado como colaborador ao repositório) 
A documentação deve ser incorporada à seção 4.3.1 do arquivo https://github.com/monanadmin/monan/blob/main/doc/Processo_de_desenvolvimento_monan.md#431-clone-de-desenvolvimento  

# Problemas abordados
Esclarecimento sobre as formas de colaboração.

# Dependências
Não há.

# Impactos
Não há.

# Definição da Conclusão
Permitir o esclarecimento de possibilidades de colaboração ao MONAN.

**Comment by cfbastarz** [comment]
Olá @klclaudio, na página https://github.com/monanadmin/monan/projects/1 temos alguns cards que permitem termos uma visão das tarefas que estão na Backlog do projeto, em status de To Do, In Progress, In Test, Done e Dependencies. Vou marcar esta tarefa como "In Progress", ok? Obrigado!

**Comment by joaomas** [comment]
Esta issue esta sendo encerrada pois estamos tratando do tema do versionamento e git/git flow nas issues do "Épico-MT-001" que envolve o estudo de caso Grell-Freitas, usando um caso real. As descobertas estão sendo documentadas no DTN01, DTN03 e DTN06.
