### ISSUE TITLE
Analisar para aprovação o Relatório I  (Equipe da Portaria 566)

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#150]
# Descrição

A  Comissão de Assessoramento aos Coordenadores do Projeto de Sistema de Supercomputação do INPE. Criada pela portaria 566/2022, através de seus membros, deve analisar o relatório I que deverá reportar a Saulo Freita, Ivan Barbosa e ao diretor do INPE do andamento dos trabalhos do projeto RISC e analisar as decisões.

# Dependências
Não há
# Solução

O relatório (10674508) foi colocado no SEI, processo número 01340.007463/2021-47 e enviado aos membros da comissão para o parecer. 

O membro da Comissão Denis Eiras sugeriu alterações estéticas que foram incorporadas ao relatório. 
O membro Celso solicitou alterações outras que serão incorporadas ao relatório assim que receber proposições de outros membros.

Um memorando (10672065) foi elaborado para a assinatura de todos e uma prévia foi encaminhada aos interessados acima citados.

# Problemas encontrados
Nenhum

**Comment by deniseiras** [comment]
De minha parte foram feitas sugestões de pequenas correções no texto e revisão de cálculos das tabelas. Enviados para o Luiz Flávio.
