### ISSUE TITLE
PAD: Estudo de caso n.1 - Analise Perfomance Modular (AP1) - Main [Run 1]

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#178]
### User Story:

**COMO** Grupo PAD
**QUEREMOS** estudar e aplicar a etapa de analise de perfomance modular (AP1) no estudo de caso n.1 (Grell-Freitas)
**PARA** gerar o Relatório Final de Pontos Críticos /Gargalos e validar o DTN03.

### Critérios de aceite de conclusão da Issue:

- Aplicar a analise de perfomance modular (AP1) no Estudo de Caso n.1 utilizando as ferramentas de apoio descritas nas issues #192, #193 e #194.
- Elaborar o Relatório Final de Pontos Críticos/Gargalos.
- Analisar de forma critica o DTN03, DTN01 e DTN06 com base no Estudo de Caso n.1 referente ao fluxo de processo de analise de performance modular como descrito nos fluxogramas e páginas do documento.

#### Git hub com o código stand alone.

Como o código GF standalone ainda não é membro direto do MONAN eu criei um repositório a parte para ele  dentro do Git  Monan-admin:

https://github.com/monanadmin/GF_standalone

Baixe o código com o git clone e faça um branch. Seguindo a informação do DTN 06 esse branch deve conter o número da issue associada. Nesse caso aqui a tarefa #178. Estou atuando diretamente no master por enquanto.

#### Como compilar:

Para compilar é bem simples. Vá ao diretório bin e execute o seguinte comando:

```bash
make -f Makefile_r8
```
Ele vai gerar um arquivo gf.x que é o executável.

#### Executando o código

Vá para o diretório raiz (do GF_standalone) e execute da seguinte maneira:

```bash
./bin/gf.x
```

Ele vai rodar rapidamente. Os resultados serão escritos em dois arquivos grads: ref_g.ctl e ref_g.gra

#### Comparando a saída

Existe um arquivo padronizado para comparação no subdiretório9 refs. Abra o arquivo gerado com o Grads e abra o arquivos dentro de refs. Verifique especialmente as seguintes variáveis comparando-as: outt1, outt2 e outt3.

Vai apresentar diferenças pois a as alterações já feitas mudaram a precisão das variáveis. Discutimos o comportamento nas dailys.

#### Ferramentas e medição

Usando ferramentas de medição de performance disponíveis como o HPCTollkit, kprof/grof,  CrayPat, Forge ou outra determinar as subrotinas ou funções que mais consomem tempo. Nelas tentar determinar os laços ou estruturas que demandam mais recursos e tempo para rodar.  Gerar relatórios no padrão da ferramenta escolhida com essas medições.  Veja o exemplo para o kprof:

![](![Alt text](https://ptgmedia.pearsoncmg.com/images/chap01_0131492470/elementLinks/01fig23.jpg "kprof")

Assim se identificam os gargalos de tempo, o número de chamadas e as procedures demandantes. 

#### Estudar o problema

Com os resultados obtidos  e, tendo procedures, laços ou trechos de código que dominam os tempos, deve-se estudar as razões aparentes que levam ao trecho gastar tempo demais comparado aos outros. Assim deve-se determinar as razões para que possam ser atacadas nas próximas etapas. Isso pode envolver problemas com estruturas de decisão (IF) dentro de laços que impeçam a vetorização, possíveis cache miss devido a ordem de arrays na memória e laços que os acessam, etc. Tendo determinado trechos suspeitos estes devem ser manipulados na próxima fase.

#### Atuar em modificação do código

Com os estudos determinados devem ser aplicadas as técnicas de otimização, vetorização ou outras que permitam que o trecho do código em questão seja acelerado. Na impossibilidade de atuação deve-se tentar explicar as razões de não mais poder acelerar o código e levar o fato para discussão nas reuniões.

#### Observações

* Por ser um código rápido e pequeno cabe fazer alterações no programa de simulação para que ele chame mais vezes o código principal, modConParGf.F90, de forma a se obter valores mais robustos.

* As alterações feitas precisam observar o padrão de codificação do DTN 01

* A cada modificação é saudável observar se as saídas ainda fazem sentido.

* Estar sempre atentos a atualizações no código fonte do GitHub e fazer o merge com o de seu trabalho.  

### Dependências

#192
#193
#194

#### Pré-avaliação

Embora não tenha sido muito aprofundada, em geral, a análise de gargalos não identificou pontos muito críticos. 
Foi identificado pelo PO e em consenso comum que muitos pontos do código têm loops que fazem a verificação de atuar ou não em determinadas colunas da atmosfera, como no exemplo abaixo:
```
! --- get air density at full layer (model levels) by hydrostatic balance (kg/m3)
      do i = its, itf
         rho_hydr(i, :) = 0.0
         if (ierr(i) /= 0) cycle
         do k = kts, ktf
            rho_hydr(i, k) = 100.*(po_cup(i, k) - po_cup(i, k + 1))/(zo_cup(i, k + 1) - zo_cup(i, k))/c_grav
            !print*,"rhohidr=",k,rho_hydr(i,k),po_cup(i,k+1),zo_cup(i,k+1)
         end do
      end do
```
isto é, em diversos pontos a verificação `if (ierr(i) /= 0) cycle` faz com que o loop se torne mais lento.
Uma das possíveis soluções é armazenar os índices `i` das colunas que não tem erros em uma estrutura de dados como um vetor ou uma lista ligada, para que o loop sempre atue somente nessas colunas.

Esta e outras ações levaram a distintas linhas de análise e ações, a saber:

1. Melhor entendimento do HPCViewer e Usar o HPCViewer para análise de gargalos. #193 
2. Criação de repositórios no Github para liberdade de se alterar o código para testes (branch monan-178-cr).
3. Criação de repositório alternativo para análise de viabilidade e análise de performance de Lista Ligada ( https://github.com/carlosrenatosouza2/utils ). O repositório fork deste será incorporado (https://github.com/deniseiras/fortran_linked_list) #188 
4. Importar projeto, adaptar a estrutura e compilar.
5. Adaptar os fontes conforme necessidade de tipos de dados da lista ligada.
6. Criar testes de performance: inserir muitos itens no final da lista e remover itens do meio da lista.
7. Testar uso na solução de remoção de `if (ierr(i) /= 0) cycle`. #190 
5. Análise da ferramenta VTune e uProf da AMD. #194 

#### Conclusões

O primeiro passo foi a organização do repositório https://github.com/monanadmin/GF_standalone seguindo a DTN 06, isto é, seguindo o padrão definido do Git Flow. Foi criada a branch feature/monan-178-c para as tarefas de avaliação #192 #193 e #194 .

Abaixo segue conclusões das issues subdividadas dependentes.

**#192 - Estudo de caso n.1 - Analise Perfomance Modular (AP1) - Gprof/Kprof [Run 1]**

A analise não apresentou indicadores consistentes referente aos pontos críticos.

**#193 - Estudo de caso n.1 - Analise Perfomance Modular (AP1) - HPC Toolkit [Run 1]**

Verificou-se superficialmente que, em grande parte do código, ao não usar opções de otimização, os cálculos consomem grande parte do processamento, distribuído nas grandes rotinas. 

Outros pontos do código a serem avaliados são os já identificados anteriormente, com if cycle.

Ainda é preciso avaliar melhor os resultados e discutir em uma próxima sprint se é necessário aprofundar esse estudo e comparar as descobertas das outras análises. Também é preciso fazer os mesmos passos em uma análise de mais de uma coluna.

**#194 - Estudo de caso n.1 - Analise Perfomance Modular (AP1) - VTune e uProf [Run 1]**

ifort -g -O0 -fpe0 cai em divisao por zero
Na compilação com intel (módulo intel/2021.4.0) identificou-se divisão por zero da variável xmb durante a execução do software ao utilizar a flag -fpe0 (esse erro não ocorre quando -r4 é utilizado em conjunto).

Linha 11550 na chamada da subrotina setGradsVar(... variável/xmb,...)
Para obtermos reprodutibilidade binária dos resultados, a flag -r8 foi utilizada. Essa força que todas as variáveis reais estejam em dupla precisão, o que já está descontinuado.

Excesso de "if's" foram identificados dentros dos laços nas subrotinas. Uma estratégia de otimização seria utilizar lista ligada implementada com ponteiros ou vetores para diminuir o número de vezes que esses ïf's" são chamados.

Foi observada alternância na ordem da execução de instruções nas subrotinas durante realizações seriais.

Até o momento não foi possível utilizar o uProf da AMD por falta de instalação na EGEON. O uProf é o software concorrente e similar ao VTune e mais apropriado para esse tipo de análise na Egeon.

**Comment by luflarois** [comment]
# Git hub com o código stand alone.

Como o código GF standalone ainda não é membro direto do MONAN eu criei um repositório a parte para ele  dentro do Git  Monan-admin:

https://github.com/monanadmin/GF_standalone

Baixe o código com o git clone e faça um branch. Seguindo a informação do DTN 06 esse branch deve conter o número da issue associada. Nesse caso aqui a tarefa #178. Estou atuando diretamente no master por enquanto.

## Como compilar:

Para compilar é bem simples. Vá ao diretório bin e execute o seguinte comando:

```bash
make -f Makefile_r8
```
Ele vai gerar um arquivo gf.x que é o executável.

## Executando o código

Vá para o diretório raiz (do GF_standalone) e execute da seguinte maneira:

```bash
./bin/gf.x
```

Ele vai rodar rapidamente. Os resultados serão escritos em dois arquivos grads: ref_g.ctl e ref_g.gra

## Comparando a saída

Existe um arquivo padronizado para comparação no subdiretório9 refs. Abra o arquivo gerado com o Grads e abra o arquivos dentro de refs. Verifique especialmente as seguintes variáveis comparando-as: outt1, outt2 e outt3.

Vai apresentar diferenças pois a as alterações já feitas mudaram a precisão das variáveis. Discutimos o comportamento nas dailys.

**Comment by joaomas** [comment]
@luflarois atualizei a descrição da issue com base no seu comentário... acredito que o comentário possa ser removido... se necessário podemos ir editando e melhorando a descrição principal da issue.

**Comment by egkhamis** [comment]
@luflarois seria interessante nesse momento manter o valor de c_pi original para bater binário das saídas ao invés de compara-las no grads

**Comment by carlosrenatosouza2** [comment]
31/01/23
- Precisei relembrar comandos git, revisei a parte do curso de git@udemy sobre branchs, merges, commit, checkout.

**Comment by deniseiras** [comment]
### Aprendendo mais do HPCToolkit:

Para listar as opções de métricas do HPCTOOLKIT:
- `hpcrun -L`
- Ex de uso: `hpcrun -t -e CACHE-MISSES -e CPUTIME -e CYCLES -e INSTRUCTIONS executable`

### Use case do HPCTOOLKIT em no programa standalone gf.x na Egeon em nó de login:
- modificado Makefile_r8 para incluir opção '-g'. O padrão do makefile é sem otimização (O0)
- Para executar uma vez o HPCToolkit:
```
make -f Makefile_r8
module load hpctoolkit-2021.10.15-gcc-9.4.0-i3utntd
hpcrun -t ./bin/gf.x 
hpcstruct ./bin/gf.x 
hpcprof -I . -S gf.x.hpcstruct hpctoolkit-gf.x-measurements
hpcviewer hpctoolkit-gf.x-database
```
- Para executar mais de uma vez o HPCToolkit, criou-se o script `run_gf_times.sh`, abaixo,  e executou-se:
*run_gf_times.sh*
```
times_to_execute=3

hpct_measure="hpctoolkit-gf.x-measurements"
hpct_struct="gf.x.hpcstruct"
hpct_db="hpctoolkit-gf.x-database"

rm -rf "$hpct_measure"* "$hpct_struct"* "$hpct_db"*

for counter in $(seq 1 $times_to_execute); do
  echo -e "\n\n\nExecution of profiler on gf.x # $counter"

  hpcrun -t ./bin/gf.x
  hpcstruct ./bin/gf.x
  mv $hpct_measure "${hpct_measure}__EXEC${counter}"
  mv $hpct_struct "${hpct_struct}__EXEC$counter"
  mv ref_g.ctl "ref_g.ctl__EXEC${counter}"
  mv ref_g.gra "ref_g.gra__EXEC${counter}"

  hpcprof -I . -S "${hpct_struct}__EXEC$counter" "${hpct_measure}__EXEC${counter}"

done

echo -e "\n\n\ncheck generated databases:\nhpcviewer hpctoolkit-gf.x-database__EXEC[#]\n\n"
```

Está sendo analisado um bug que indica não reprodutibilidade. Verifica-se que duas execuções executaram linhas bem distintas de chamadas. Um exemplo, através da imagem abaixo, onde as linhas selecionadas dos dois hpcviewer apresentam linhas de execução distintas:
![image.png](https://images.zenhubusercontent.com/6335d6f2d6d9bb4660047b43/a6692f31-7946-474c-b0bd-94fd9ff9222f)
![image.png](https://images.zenhubusercontent.com/6335d6f2d6d9bb4660047b43/213e8311-7c7a-42f0-9a99-28a48692b17d)
Ao executar o programa sem o hpctoolkit também se percebe diferenças nos binários ref_g.gra .

**Comment by egkhamis** [comment]
### Utilizando o VTune, profiler da Intel:

Para utilizar o vtune:
- remover o uso dos modulos carregados por padrao:
$module purge
-carregar os modulos da Intel e abrir o vtune
$module load intel/2021.4.0
$module load vtune/2022.3.0
$vtune-gui
- criar novo projeto para analise
- modificar localizacao do executavel para facilitar criacao do projeto
- modificar Makefile_r8 para utilizar o compilador ifort, com as flags -g -O0 -r8 (opcoes extras podem causar falha de segmentacao na execucao (que devem ser investigadas - podem indicar novos bugs)

O uso do software e' intuitivo , porem, apenas 2 opcoes de analise ficam disponiveis por conta na Egeon ter processadores AMD, e talvez devido a problemas com a instalacao do software, sao acessiveis: "hotspots" e "memoryaccess" (este pode ser muito util na analise de performance de um codigo com lista ligada).

Exemplos de uso do software analisam, por exemplo, a metrica CPUTIME:
![Screenshot 2023-02-27 at 20.50.16.png]
(https://images.zenhubusercontent.com/62b4d9a8a88d970b6d52f3f5/f9f7633c-9d94-4728-9a4d-c18cc21f227b) 
Tambem:

![Screenshot 2023-02-27 at 20.51.28.png](https://images.zenhubusercontent.com/62b4d9a8a88d970b6d52f3f5/83ba4f4f-8320-4a52-87dd-eeead8f2c255)

Ou acesso a memoria:

![Screenshot 2023-02-27 at 20.53.36.png](https://images.zenhubusercontent.com/62b4d9a8a88d970b6d52f3f5/6f80e922-3f0d-4289-bda3-e2514e2f509f)

**Comment by joaomas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GCC-MONAN-62a3a783cb59a00014ce8e70/issues/monanadmin/monan/178?planning-poker) with Zenhub @carlosrenatosouza2 @deniseiras @egkhamis

**Comment by joaomas** [comment]
- Adicionei as dependências #192, #193 e #194 e ajustei o User Story e Aceite considerando agora estas 3 dependências.

**Comment by joaomas** [comment]
Resultados apresentados ao PO na review do dia 27/3 que aprovou a sequência das ações de ajustes para melhoria dos pontos críticos.
