### ISSUE TITLE
GRC: Estudo de caso n.1 - Refatoração Automática (RA)

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#179]
User Story:

**COMO** Grupo GRC, **QUEREMOS** estudar e aplicar code review na etapa de refatoração automática (RA) no estudo de caso n.1 (Grell-Freitas) **PARA** validar o DTN03.

Critérios de aceite de conclusão da issue:

- (...)

**Comment by luflarois** [comment]
## Metodologia aplicada

os código fonte Fortran foram passados somente pela ferramenta fprettify que pode ser obtida em:

https://pypi.org/project/fprettify/ (instalada via  pip install)

Para cada código fonte fez-se o seguinte comando:

`fprettify --case 1 1 1 1 <nome_do_fonte_fortran>`

, exemplo: f

`prettify --case 1 1 1 1 modHenrysLawCts.F90`

O --case controle que tudo fique em mínúsculas. 

Apenas isso foi feito na etapa de RA.

> Importante: É necessário buscar uma ferramenta que permita fazer de forma automática aplicar os "intents" nas variáveis passadas nas chamadas.

> @klclaudio : Cabe estudar o fprettify para que ele possibilite as seguintes mudanças: 
> ao usar o -- case   ele tenha opção diferentes possíveis para nomes de subrotinas e módulos (camelCase), nomes de funções (PascalCase), variáveis (snake_case) parâmetros (prefixo p_ e depois snake_case) . Isso ajudaria bastante. 
--case CASE CASE CASE CASE
                        Enable letter case formatting of intrinsics by
                        specifying which of keywords, procedures/modules,
                        operators and constants (in this order) should be
                        lowercased or uppercased - 0: do nothing | 1:
                        lowercase | 2: uppercase (default: [0, 0, 0, 0])
