### ISSUE TITLE
[Chapéu] PAD: Aplicar solução para remoção do 'do - if - cycle' e remoção do indice do vetor [Run 1]

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#195]
### User Story (Original)

COMO PAD
QUEREMOS modificar o código Grell-Freitas (santd alone) estendendo a solução da issue #190 para o restante do código
PARA melhorar a perfomance do código.

### User Story (03-05-2023)

Esta issue foi subdividida.

### Critérios de aceite de conclusão da Issue (Original)

- Seguir as DTNs.
- Identificar todos os if cycles a serem removidos. (ok)
- Realizar o máximo de remoções dentro do tempo planejado da Sprint. (não - mudado)
- Realizar testes comparativos de tempo x execução.
- A saída deve bater "binário" ou analise visual acordada com PO. (Usando real 4)

### Critérios de aceite de conclusão da Issue (03-05-2023)

- As issues subdivididas abaixo devem estar finalizadas:

- [x] #239
- [x] #240
- [x] #241
- [x] #242
- [x] #243
- [x] #251 
- [x] #244

### Detalhamento adicional da atividade

- Código, namelists e arquivos de entrada enviados pelo PO. 
- Deve-se alterar a variável p_use_gate no modGate para False.
- Deve-se compilar com real 4 
- Manter o ierror e cerror
- Remover os if cycles e indices na ordem de execução do código 
- Fazer o teste de perfomance (após a remoção)

### Impactos

Não há impactos.

### Dependências

- Código GF alterado.

### Solução
Esta Issue foi subdividida (ver User Story de 03-05-2023), e estão listadas nas dependências desta.

Também foram feitas alterações abaixo, possivelmente não documentadas em outras issues:
- O código disponibilizado pelo PO foi armazenado em  http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/github_issues_files/monan-195-QI/ 
- O programa teste, gf_teste.f90 agora foi incorporado e colocado como programa principal no Makefile (o programa para 1 coluna continua, mas comentado)
- A antiga pasta datain, agora renomeada para datain_1 agora armazena os dados para 1 coluna. A pasta datain armazena os dados para na colunas. O arquivo gf.inp foi copiados da configuração de uma coluna para n colunas. Todos os binários foram removidos do git e transferidos para o ftp, nas pastas:
  - datain - dados para n colunas
  - datain_1_coluna - dados para 1 coluna
  - refs - referências originais para n colunas
  - refs_1_coluna - referências originais para 1 coluna
- A variável do módulo modGate, p_use_gate, foi alterada par False.

### Problemas encontrados

Nenhum

### Conclusão

Esta issue "Chapéu" foi concluída após a conclusão de todas as outras, passando por todos os critérios de aceite.

**Comment by deniseiras** [comment]
Luiz Flávio sobre novo test case:

"Pessoal,

Fiz um makefile específico para ese novo teste: Makefile_new

Para usar corretamente vcs precisam alterar a variável p_use_gate no modGate para False.

O arquivo de namelist precisa ser o do BRAMS, eu mandei o original que usamos (standalone) e o novo.

Tem ainda os arquivos binários de entrada e os grads de saída para referência. Dentro de refs.

Vejam se está tudo OK. E se der subam por favor."

**Comment by deniseiras** [comment]
```bash
#plano para  fazer a alteração codigo para excluir os 
#   if + cycle

#134 locais encontrados para fazer as substituições 
#
#onde houver   : do i = its, itf
#substituir por: do vtp_index = 1, get_num_elements()
#
#
#onde houver : if (ierr(i) /= 0) cycle
#substituir por: i=get_index_value(vtp_index)
#
#plano:
#1. encontrar os numeros das linhas que possuem:
#    do i = its, itf
#   e colocar em um arquivo linhasOcorr.txt
#
cp src/00modConvParGF.F90 src/modConvParGF.F90
padrao="if"; sep=":"
padrao="do"; sep="-"
grep -n "ierr(" src/modConvParGF.F90 -B6 | \
	grep -E "\(ierr.*cycle|\(ierr.*then|do.*itf" |head -259 |\
	grep -E -v "1432-|12901-|11693-|2121-|[ ][ ]\!|\:\\!|\-\\!|==" |\
	grep $padrao |awk -F${sep} '{print $1}' > linhasOcorr.txt

#grep -n "print.*cycle " -A 1  src/modConvParGF.F90 |\
#	grep ierr|\
#	grep -v -E "trim|or|loop|xk|==" |\
#	awk -F'-' '{print $1}' 

#head linhasOcorr.txt
#read

#2. percorrer as linhas e fazer as alterações:
novaLinha="do vtp_index = 1, get_num_elements() \\!BD_n"
for nl in $(head -5 linhasOcorr.txt);
  do
	  comando="sed     "\"${nl}s/^/\\!BD_r/\""        src/modConvParGF.F90";
	  comando="sed -i  "\"${nl}s/^/\\!BD_r/\""        src/modConvParGF.F90";
#	  echo $comando; #read; #
#	  eval $comando;
          comando="sed    -e '"${nl}"i\\' -e '${novaLinha}' src/modConvParGF.F90"
          comando="sed -i -e '"${nl}"i\\' -e '${novaLinha}' src/modConvParGF.F90"
#	  Incluir texto na linha N apagando o conteúdo existente
#OBS: troque o número 1 para a linha que você quiser
#	  sed '1s/.*/início do arquivo/' 
          comando="sed -i    '"${nl}"s/.*/${novaLinha}/'  src/modConvParGF.F90"
	  echo $comando; read; #
	  eval $comando;
  done

#alterações:

#2.1. incluir os caracteres !BD_r no inicio das  
#    linhas que serão substituidas
#
# entrada:     do i = its, itf
# saida  : !BD_r     do i = its, itf
#
#2.2. incluir uma nova linha abaixo desta com o conteudo:
# entrada: !BD_r     do i = its, itf
# saida: 
#    !BD_r     do i = its, itf
#    do vtp_index = 1, get_num_elements()  !BD
#
#
#3. experimentar o codigo para ver se bate binario
#
#4. remover as que possuem !BD_r nas primeiras colunas

padrao="do"; sep="-"
padrao="if"; sep=":"
grep -n "ierr(" src/modConvParGF.F90 -B6 | \
	grep -E "\(ierr.*cycle|\(ierr.*then|do.*itf" |head -259 |\
	grep -E -v "1432-|12901-|11693-|2121-|[ ][ ]\!|\:\\!|\-\\!|==" |\
	grep $padrao |awk -F${sep} '{print $1}' > linhasOcorr.txt


#2. percorrer as linhas e fazer as alterações:
novaLinha="i=get_index_value(vtp_index) \\!BD_n"
for nl in $(head -5 linhasOcorr.txt);
  do
	  comando="sed       "\"${nl}s/^/\\!BD_r/\""        src/modConvParGF.F90";
	  comando="sed -i    "\"${nl}s/^/\\!BD_r/\""        src/modConvParGF.F90";
#	  echo $comando; #read; #
#	  eval $comando;
          comando="sed    -e '"${nl}"i\\' -e '${novaLinha}' src/modConvParGF.F90"
          comando="sed -i -e '"${nl}"i\\' -e '${novaLinha}' src/modConvParGF.F90"
          comando="sed -i    '"${nl}"s/.*/${novaLinha}/'  src/modConvParGF.F90"
	  echo $comando; #read; #
	  eval $comando;
  done
```

**Comment by joaomas** [comment]
Esta issue foi subdividida em 03-05-2023.
