### ISSUE TITLE
PAD: EP-MT002 - Execução - WSM5

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#219]
### User Story

COMO PAD
QUEREMOS executar o WSM5
PARA para validar a compliação

### Critérios de aceite de conclusão da Issue

- Código rodando com os dados de entrada fornecidos
- Saída deve ser compatível com a referência

### Detalhamento adicional da atividade

- A referência foi gerada com gnu -O0. Deverá ser alterado o ctl:
  - cloud = rcp
  - rain = rcp
- A princípio será usada essa referência
- Mais valores poderão ser gerados à partir do BRAMS, a serem tratados em outras issues.

### Impactos

Não há impactos.

### Dependências

- [x] #218 

### Solução

CR:
- alterei o read do namelist para hardcoded: ../datain/wsm.inp. Restante do codigo fica lendo e escrevendo nos diretorios datain e dataout respectivamente, obedecendo as variáveis var_datain e var_dataout do namelis inseridas pelo Eduardo K.
- alterei o var_datain='../datain/' em /wsm.inp.

DE:
Criado script compare_local_modifications.sh
- Este utiliza o script WSM5_standalone.sh para compilar e executar.
- Usa o script compare_local_modifications.sh para gerar as diferenças e figuras com
- O ctl da referência foi alterado:
  - cloud = rcp
  - rain = rrp

#### Resultados:

Diferenças obtidas:

Nvidia:
![image](https://user-images.githubusercontent.com/6113640/232063754-da79cf80-0892-49fa-a159-9dea7c866ea3.png)

GNU:
![image](https://user-images.githubusercontent.com/6113640/232063902-34851f9b-397c-455d-8bcc-e6dda346371f.png)

Resultados com saída e figuras em:
http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/github_issues_files/monan-219-QI/
/pesq/share/dmdcc/dist/monan/github_issues_files/monan-219-QI

Criadas referências de resultados com gnu e nvidia na Egeon, na pasta
/pesq/share/dmdcc/dist/monan/standalone_codes/WSM5/refs_egeon/

#### Conclusão:

Algumas diferenças superaram os valores da diferença consideravelmente, como no exemplos:
 - GNU: var rrp em z=22, foi de 0.0001
 - NVD: var rrp em z=20, foi de 0.0009

Verifica-se uma maior diferença no caso do compilador da nvidia, mas analisando foram um ou poucos pontos com as diferenças.

Uma melhor análise sobre as diferenças deve ser feita nas próximas sprints.

### Problemas encontrados

(...)

**Comment by deniseiras** [comment]
Saulo (Watts 13/04)
[18:10, 4/13/2023] Saulo Freitas: Aqui    if(varmax>difmaxima) use difmaxima = 1.e-6
[18:11, 4/13/2023] Saulo Freitas: Aqui 'd abs(('var'-'var'.2)/('var'+'difmaxima'))' use difmaxima = 1.e-12

**Comment by deniseiras** [comment]
Saulo - reunião daily.
Verificar SPACING para menor diferença da máquina
CR: EPSILON para menor número
BIDU: fez teste com os dois: mesmo resultado

**Comment by deniseiras** [comment]
[11:07, 4/14/2023] Saulo Freitas: Aqui está o codigo modificado para incluir no diretório ./micro do BRAMS
[11:07, 4/14/2023] Saulo Freitas: /mnt/beegfs/saulo.freitas/for-Denis
[11:07, 4/14/2023] Saulo Freitas: mic_wsm_driver.f90
[11:07, 4/14/2023] Saulo Freitas: no Egeon

**Comment by deniseiras** [comment]
Bidu:

![image](https://user-images.githubusercontent.com/6113640/232100165-2fff1017-bfd0-4fc2-ae36-1c19964fcb28.png)

resultados de experimento com números pequenos.
gfortran e ifort diferenciam em caso extremo de extended precision

```fortran
PROGRAM test_spacing
  INTEGER, PARAMETER :: SGL = SELECTED_REAL_KIND(p=6, r=37)
  INTEGER, PARAMETER :: DBL = SELECTED_REAL_KIND(p=13, r=37+1)
  INTEGER, PARAMETER :: EXT = SELECTED_REAL_KIND(p=23, r=300)!foi chute de tentativa e erro
  REAL*4 EPSS
  REAL*8 EPSD
  REAL(KIND=EXT) :: EPSE
  character (100) :: formatoA='(a,g58.45)'
  character (100) :: formatoB='(a,g53.45)'
  integer :: i=0

  WRITE (*,formatoA) "A, spacing (1.0_SGL)  =", spacing(1.0_SGL)
  WRITE (*,formatoA) "B, spacing (1.0_DBL)  =", spacing(1.0_DBL)
  WRITE (*,formatoA) "C, spacing (1.0_EXT)  =", spacing(1.0_EXT)

  WRITE (*,formatoA) 'D, EPSILON(1.0e00)    =', EPSILON(1.0_SGL)
  WRITE (*,formatoA) 'E, EPSILON(1.0d00)    =', EPSILON(1.0_DBL)
  WRITE (*,formatoA) 'F, EPSILON(1.0_EXT)   =', EPSILON(1.0_EXT)

  EPSS=1.0_SGL
  do while (1.0_SGL+EPSS/2.0_SGL>1.0_SGL); EPSS=EPSS/2.0_SGL; end do
  WRITE (*,formatoB) 'G, Single EPSILON calculed =', EPSS

  EPSD=1.0_DBL
  do while (1.0_DBL+EPSD/2.0_DBL>1.0_DBL); EPSD=EPSD/2.0_DBL; end do
  WRITE (*,formatoB) 'H, Double EPSILON calculed =', EPSD

  EPSE=1.0_EXT
  do while (1.0_EXT+EPSE/2.0_EXT>1.0_EXT); EPSE=EPSE/2.0_EXT; end do
  WRITE (*,formatoB) 'I, ext    EPSILON calculed =', EPSE

  write(,) "A = D = G"; write(,) "B = E = h"; write(,) "C = F = I"
END PROGRAM
```
