### ISSUE TITLE
Documento com os passos de compilação do código-fonte do MPAS

### ISSUE THREAD

**Issue by monanadmin** [monanadmin/monan#22]

**Comment by robertopsouto** [comment]
@deniseiras  e @egkhamis , por favor, vocês poderiam testar estas instruções de compilação do MPAS no cluster Minerva? A ideia é usar as bibliotecas `netcdf-c`, `parallel-netcdf` e `parallelio` instaladas no Spack de minha conta no Minerva.
Enquanto isso vou preparando as instruções de execução do benchmark 10km. E também as instruções para compilação e execução em GPU, mas neste caso no cluster Rattler.
Muito obrigado.

**Comment by robertopsouto** [comment]
@luflarois , no arquivo `Compilacao_MPAS.md` deste *branch* estão as instruções de como compilar o MPAS, similar ao documento feito para o BRAMS.
