### ISSUE TITLE
PAD: EP-MT002 - Estudo do código WSM5 para adaptação de CPU para GPU

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#222]
### User Story

COMO PAD
QUEREMOS estudar o código WSM5 pensando em sua adaptação de CPU para GPU
PARA agregar conhecimento ao grupo e melhor aproveitamndo do treinamento da NVIDIA

### Critérios de aceite de conclusão da Issue

- Estudo do artigo (referenciado no README - DOI: 10.1109/JSTARS.2012.2188780)
- Encontrar e estudar o código que roda no WRF em GPU e comparar com o atual
- Entender as diretivas OpenACC que são aplicaveis

### Detalhamento adicional da atividade

(...)

### Impactos

Não há impactos.

### Dependências

(...)

### Solução

- Criada a branch lab/monan-222-QI para estudar o código.
- Pastas:
  - cpu : código serial (da develop)
  - gpu : código com OpenAcc. (Ver diretivas $acc)
- Foram verificados códigos com diretivas OpenACC sem Makefile para GPU
- Não foram testadas alterações com OpenACC
- Foram pesquisadas, identificadas e documentadas algumas opções de compilação OpenACC, no Makefile dentro da pasta "cpu"

### Problemas encontrados

(...)

**Comment by deniseiras** [comment]
Curso OpenACC-Cuda no colab. 
- Contém hello world funcional
- Link curso: https://enccs.github.io/OpenACC-CUDA-beginners/setup/
- Link colab: https://colab.research.google.com/github/ENCCS/OpenACC-CUDA-beginners/blob/colab_gcc/examples/openACC_CUDA_colab.ipynb#scrollTo=qeYvrnh4Kgvm

**Comment by egkhamis** [comment]
Alguns links:
https://www2.mmm.ucar.edu/wrf/WG2/GPU/
https://www2.mmm.ucar.edu/wrf/WG2/GPU/WSM5.htm
https://www2.mmm.ucar.edu/wrf/WG2/bench/
https://data1.gfdl.noaa.gov/multi-core/2013/presentations/michalakes_5.pdf
http://new.math.uiuc.edu/im2008/dakkak/proposal/papers/michalakes_lspp.pdf
https://www.olcf.ornl.gov/wp-content/training/CrayTech_XK6_2012/Porting_WRF_to_OpenACC.pdf
https://journals.ametsoc.org/view/journals/atot/30/12/jtech-d-12-00218_1.xml
https://www.sciencedirect.com/science/article/pii/S0098300420306051
https://github.com/kimjy-par/MPAS_wsm6_GPU_for_CAG/tree/master/MPAS-GPU-for_wsm6

**Comment by deniseiras** [comment]
Nesse curso tem uma seção de Q&A interessante, by João.
https://www.openacc.org/events/openacc-online-course-2018
