### ISSUE TITLE
Dev. Análise automática de código (bloco 3)

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#229]
### User Story

COMO Grupo GRC,
QUEREMOS desenvolver solução de regras do DTN 01 fazendo a análise automática de código,
PARA ser integrado a ferramenta final QA.

### Critérios de aceite de conclusão da Issue

- Desenvolvimento que abrange o máximo possível de regras do DTN 01.
- Testes e código do desenvolvimento validado para o máximo de regras possível.

### Detalhamento adicional da atividade

Finalização da regra 4.32, com verificação de nome do arquivo e nome do módulo. 
Verificação da extensão do arquivo.
Refatorar regra 4.17 mostrando somente nome do arquivo.
Estudo de como  verificar a palavra chave intent no código Fortran e busca no arquivo .xml.

### Impactos

Não há impactos.

### Dependências

Documento DTN01: (link)

### Solução
Implementou-se a regra 4.32, restando testes finais.
Foi refatorado a regra 4.17 criando uma função para extrair o nome do arquivo do endereço completo obtido do arquivo .xml. Foi criado uma função de verificação de extensão do arquivo(.F90) para aproveitamento em verificações posteriores.

Implementou-se a regra referente a deallocate, faltando fazer testes. Foi analisado as regras 4.23, 4.25  e 4.27 considerando os recursos do .xml descartou-se a implementação de verificação temporariamente. 

### Problemas encontrados
O arquivo .xml proveniente do parser não permitiu a implementação de  verificação de algumas regras.

### Conclusão

(...)

**Comment by deniseiras** [comment]
Reuniu-se Kléucio e Denis em 08/05:
Discussão:
- Quebra de código em módulos. Será iniciado por Kléucio
- Uso de padrões para "modernização" do código - separação entre regras e controle de regras
- Mais avanços serão feitos em seguida para melhoria e desacoplamento do código.
