### ISSUE TITLE
Revisão dos gráficos e textos de PEE MPAS x FV3

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#232]
### User Story

COMO PAD,
QUEREMOS revisar os gráficos e textos de PEE do MPAS x FV3 do relatório de avaliação,
PARA o workshop DIMNT de maio/2023.

### Critérios de aceite de conclusão da Issue

- Revisitar o trabalho de avaliação já apresentado.
- Revisão, correção e melhorias do relatório no tópico de PEE.

### Detalhamento adicional da atividade

(...)

### Impactos

Não há impactos.

### Dependências

Pontos a serem esclarecidos:
- consumo energético CPU/GPU/ARM (verificar soluções da RFI propostas pelos fabricantes)
- super escalabilidade do MPAS
- uso do núcleo dinâmicos em tempo e clima com acoplamentos

### Solução

Revisão das apresentações dos resultados da análise dos núcleos dinâmicos ao comitê científico pelo Luiz Flávio e Roberto:  
- https://youtu.be/dKyWDTfTm2w?t=1395
- https://youtu.be/OYq1sglZH_4?t=946

**Documento do Relatório Preliminar**
https://docs.google.com/document/d/1drJMJYJp5UZzjdjsbU5nRl4Rth7jzbmIYBrWLNW8uXw/edit

**Planilha geral**
Esta planilha apresenta resultados do Shield na Egeon, MPAS com CPU na Minerva com e GPU Na Rattler e SD(?).
https://docs.google.com/spreadsheets/d/1TocNvlf7pWlIplOj48DbQOHHA4q4OL-_4KxB7oEsTIk/edit?usp=sharing.

**FV3**

As execuções para avaliação foram executadas na Egeon e na máquina Minerva.

Egeon: 
- #30 
- Até 24 nós
- os resultados da Egeon foram encontrados a plainilha geral. 

Minerva: 
- #67 
- Até 64 nós - 72 ou 96 processadores
- Os resultados da Minerva foram encontrados na planilha: https://docs.google.com/spreadsheets/d/1SUu8INotNk4mqvmlk2-K8nraqr94tTXMQUTZb3iRTAM/edit?usp=sharing . Estes resultados apresentam os mesmos gráficos da issue #67.
- Os resultados foram gerados com 12h de processamente e multiplicados por 2, para se obter o equivalente aproximado em 24h. Isto está detalhando no relatório.

Gráficos dos experimentos na Minerva:
![image](https://user-images.githubusercontent.com/6113640/234928349-280c5ac8-1940-457e-92ca-563b8e457c45.png)
![image](https://user-images.githubusercontent.com/6113640/234928409-e0bd8181-cdeb-4c33-9cea-5a2e6970662c.png)
![image](https://user-images.githubusercontent.com/6113640/234928504-1637c905-d52e-49da-b3a4-64384120ac2a.png)

Gráficos do Relatório preliminar:
![image](https://user-images.githubusercontent.com/6113640/234685088-f27977ea-ac5f-40f5-afae-6d7448b8440e.png)
![image](https://user-images.githubusercontent.com/6113640/234685554-df2ae3a4-3540-4663-b570-0b79acabbe5c.png)

Verifica-se que os gráficos do relatório FV3 e dos experimentos na máquina Minerva estão condizentes. 

**MPAS**
- Verificou-se que o texto do relatório explica que foram executados 7 nós para GPUs e 64 nós para CPUS, e que foi feita extrapolação para 64 nós de GPU.
  - O gráfico de "performance" de GPU inclui 7 nós
  - O gráfico de "eficiência" de GPU exibe 64 nós (extrapolado)

Gráficos abaixo:

![image](https://user-images.githubusercontent.com/6113640/235923975-1e868a24-b3bf-4648-a75d-f2b7625317b0.png)

![image](https://user-images.githubusercontent.com/6113640/234935397-50c61623-7aa8-4a7e-b8a6-7352730f4e73.png)

### Problemas encontrados

(...)

### Conclusão

- Em geral, não foram identificados grandes problemas.
- Serão necessários maiores estudos em relação à super linearidade (#234) e consumo energético.

A corrigir:

- A tabela 10 do relatório exibe dados gerados ao usar 32 nós, como exemplo, o que pode ser questionado.
- São necessárias as seguintes alterações no gráfico de zoom da eficiências:
  - alterar os dois texto de "MPAS 13km (estimado) ..." para "extrapolado 13km"
  - incluir um comentário no gráfico para explicar que a execução com 64 nós de GPU foi uma estimativa
  - Aguardando a planilha do Luiz Flávio para as correções
  - Artigo para referência "The resolution of global spectral models" - https://pielkeclimatesci.files.wordpress.com/2009/09/nt-27a.pdf

**Comment by deniseiras** [comment]
![image](https://user-images.githubusercontent.com/6113640/234940050-3786c09f-1143-4168-9fd0-cf078cffb02f.png)
Minerva:
![image](https://user-images.githubusercontent.com/6113640/234940275-a3ac34a4-8885-4190-be05-8eb5e3d4cb5b.png)

**Comment by joaomas** [comment]
Energia:
- https://www.techspot.com/article/2540-rise-of-power/
