### ISSUE TITLE
PAD: Finalização script de remoção do 'do - if - cycle' e execução [Run 1]

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#239]
### User Story

COMO PAD
QUEREMOS finalizar o script de remoção do 'do - if cycle' e executar o script para o código Grell-Freitas
PARA melhorar a perfomance do código

### Critérios de aceite de conclusão da Issue

- Script finalizado com base na solução da issue #195.
- Execução do script para o código Grell-Freitas.
- O código deve ser compilado em GNU.
- (up) Comparação visual do código usando ferramenta apropriada.
- (up) Comitar o código F90 alterado e o script de remoção.

### Detalhamento adicional da atividade

_(... espaço para detalhar melhor o que deve ser realizado)_

### Impactos

_(... consequência técnica encontrada durante a execução da issue)_

### Dependências

_(... issues e requisitos que devem ser executados previamente)_

### Solução

A atividade está sendo realizada.
temos aproximadamente **140** locais onde a modificação deve ser feita
hoje, 09.05, o script ``modificarFonte.sh``, altera 99 e produz resultado identicos, batento binario.
comparação com arquivo grd no tempo  mais avançaodo  da simulação: 9600

o script procura as linhas com os ``ifs + ierr+ cycle`` usando grep e mostra 10 linhas anteriores
  onde podem estar as linhas com os inicios do laço de repetição  ``do i = its, itf``.

as linhas com os ``if `` possuem um ``: `` e as linhas com o ``do`` possuem um ``-``
```
1127-      do i = its, itf
1130:         if (ierr(i) /= 0) cycle
1225-         do i = its, itf
1227:            if (ierr(i) /= 0) cycle
1255-      do i = its, itf
1259:         if (ierr(i) /= 0) cycle
1305-      do i = its, itf
1307:         if (ierr(i) /= 0) cycle
1326-         do i = its, itf
1329:            if (ierr(i) /= 0) cycle
1357-      do i = its, itf
1359:         if (ierr(i) /= 0) cycle
1376-            do i = its, itf
1378:               if (ierr(i) /= 0) cycle
```

os locais de mudança estão identificados pelos número das linhas que  estão em arquivos: ``linhasOcorrDO.txt`` e ``linhasOcorrIF.txt``

o controle do numero de alterações está sendo feito atraves desta linha
``$(cat linhasOcorrDO.txt |head -100 )``

```fOrig=src/00modConvParGF.B90
fModif=src/modConvParGF.F90
cp $fOrig $fModif
padrao="do"; sep="-"
grep -n -E "ierr.*cycle"  src/modConvParGF.F90 -B 9|\
        grep -E "its, *itf|ierr.*\) cycle" |\
        grep -v -E "applyEnvSubs|Nunca| *! |or|1745" |\
        grep $padrao |awk -F${sep} '{print $1}' > linhasOcorrDO.txt

for nl in $(cat linhasOcorrDO.txt |head -100 )
  do
          comando="sed -i -e '"${nl}"i\\' -e '${novaLinha}' src/modConvParGF.F90"
          novaLinha=" do vtp_index = 1, get_num_elements() ; i=get_index_value(vtp_index) !BD_n"
          comandoSed="${nl}s/do i.*itf/${novaLinha}/"
          comando="sed -i    '$comandoSed'  src/modConvParGF.F90"
          echo $comando; #read; #
          eval $comando;
          novaLinha="i=get_index_value(vtp_index) !BD_n"
          comandoSed="${nl}a${novaLinha}"
          comando="sed -i    '$comandoSed'  src/modConvParGF.F90"
          echo $comando; #read; #
          eval $comando;
  done

padrao="if"; sep=":"
grep -n -E "ierr.*cycle"  src/modConvParGF.F90 -B 9|\
        grep -E "its, *itf|ierr.*\) cycle" |\
        grep -v -E "applyEnvSubs|Nunca| *! |or|1745" |\
        grep $padrao |awk -F${sep} '{print $1}' > linhasOcorrIF.txt

for nl in $(cat linhasOcorrIF.txt |head -100 )
  do
          comandoSed="${nl}s/^/!BD_n/"
          comando="sed -i    '$comandoSed'  src/modConvParGF.F90"
          echo $comando; #read; #
          eval $comando;
done
```
### Problemas encontrados

_(... problemas técnicos reais apresentados durante a execução das atividades)_

### Conclusão

_(... texto que sintetiza a finalização da issue, destacando aspectos positivos e negativos)_

**Comment by ebiduardo** [comment]
A atividade está sendo realizada.
temos aproximadamente **140** locais onde a modificação deve ser feita
hoje, 09.05, o script ``modificarFonte.sh``, altera 99 e produz resultado identicos, batento binario.
comparação com arquivo grd no tempo  mais avançaodo  da simulação: 9600

o script procura as linhas com os ``ifs + ierr+ cycle`` usando grep e mostra 10 linhas anteriores
  onde podem estar as linhas com os inicios do laço de repetição  ``do i = its, itf``.

as linhas com os ``if `` possuem um ``: `` e as linhas com o ``do`` possuem um ``-``
```
1127-      do i = its, itf
1130:         if (ierr(i) /= 0) cycle
1225-         do i = its, itf
1227:            if (ierr(i) /= 0) cycle
1255-      do i = its, itf
1259:         if (ierr(i) /= 0) cycle
1305-      do i = its, itf
1307:         if (ierr(i) /= 0) cycle
1326-         do i = its, itf
1329:            if (ierr(i) /= 0) cycle
1357-      do i = its, itf
1359:         if (ierr(i) /= 0) cycle
1376-            do i = its, itf
1378:               if (ierr(i) /= 0) cycle
```

os locais de mudança estão identificados pelos número das linhas que  estão em arquivos: ``linhasOcorrDO.txt`` e ``linhasOcorrIF.txt``

o controle do numero de alterações está sendo feito atraves desta linha
``$(cat linhasOcorrDO.txt |head -100 )``


```fOrig=src/00modConvParGF.B90
fModif=src/modConvParGF.F90
cp $fOrig $fModif
padrao="do"; sep="-"
grep -n -E "ierr.*cycle"  src/modConvParGF.F90 -B 9|\
        grep -E "its, *itf|ierr.*\) cycle" |\
        grep -v -E "applyEnvSubs|Nunca| *! |or|1745" |\
        grep $padrao |awk -F${sep} '{print $1}' > linhasOcorrDO.txt

for nl in $(cat linhasOcorrDO.txt |head -100 )
  do
          comando="sed -i -e '"${nl}"i\\' -e '${novaLinha}' src/modConvParGF.F90"
          novaLinha=" do vtp_index = 1, get_num_elements() ; i=get_index_value(vtp_index) !BD_n"
          comandoSed="${nl}s/do i.*itf/${novaLinha}/"
          comando="sed -i    '$comandoSed'  src/modConvParGF.F90"
          echo $comando; #read; #
          eval $comando;
          novaLinha="i=get_index_value(vtp_index) !BD_n"
          comandoSed="${nl}a${novaLinha}"
          comando="sed -i    '$comandoSed'  src/modConvParGF.F90"
          echo $comando; #read; #
          eval $comando;
  done

padrao="if"; sep=":"
grep -n -E "ierr.*cycle"  src/modConvParGF.F90 -B 9|\
        grep -E "its, *itf|ierr.*\) cycle" |\
        grep -v -E "applyEnvSubs|Nunca| *! |or|1745" |\
        grep $padrao |awk -F${sep} '{print $1}' > linhasOcorrIF.txt

for nl in $(cat linhasOcorrIF.txt |head -100 )
  do
          comandoSed="${nl}s/^/!BD_n/"
          comando="sed -i    '$comandoSed'  src/modConvParGF.F90"
          echo $comando; #read; #
          eval $comando;
done
```

**Comment by deniseiras** [comment]
Não foram removidos os `if(cycles)` e também não deverão ser ser removidos do vetor (`remove(i)` - task #240) no trecho de código da rotina cupCloudLimits onde se verifica códigos do tipo `exit loop`. Essas alterações estavam causando erros de execução. A ser investigado.
