### ISSUE TITLE
PAD: CCPP - Análise coletiva e resumo

### ISSUE THREAD

**Issue by deniseiras** [monanadmin/monan#256]
### User Story

COMO PAD
QUEREMOS Ler o artigo CCPP
PARA Avaliar seu possível uso

### Critérios de aceite de conclusão da Issue

- Ler o resumo do site https://dtcenter.org/community-code/common-community-physics-package-ccpp
- Ler o artigo - https://gmd.copernicus.org/articles/16/2235/2023/
- Documentar resumo para discussão em reunião do Kickoff

### Detalhamento adicional da atividade

N/A.

### Impactos

N/A.

### Dependências

N/A.

### Solução

Resumo Até Design (Denis)

**Introdução**

- Interoperabilidade entre diferentes tipos de físicas e modelos, através das interfaces de metadados pré-definidas
- Também pode ser estendido como acopladores de modelos - ex oceânico
- Metadados de física e de modelo para gerar código fortran que faz a comunicação, através de scripts Python
- Suite de físicas podem ser criadas
- Repositórios:
  - https://github.com/NCAR/ccpp-framework
  - https://github.com/NCAR/ccpp-physics/ - biblioteca de físicas no repositório https://github.com/NCAR/ccpp-physics/tree/main/physics
- conversão de unidades automatizada
- possibilidade de paralelismo nas chamadas
- debuggin features
- Doxygen

**Design**

![Image](https://github.com/monanadmin/monan/assets/6113640/e23a2d40-e0ee-4230-a65c-17c9c013aaa0)

---
Eduardo:

Encontrado código que já contempla otimização para GPU do código de GF (e módulos dependentes):

https://github.com/NCAR/ccpp-physics/blob/main/physics/cu_gf_driver.F90

Correções de bugs no histórico desse repositório também podem ser reutilizados em nosso repositório.

---
Alguns vídeos interessantes:
https://www.youtube.com/watch?v=wRsvspRetRw&t
https://www.youtube.com/watch?v=0KbZHyRe4IQ
https://www.youtube.com/watch?v=F-gxv8iHt_g
https://www.youtube.com/watch?v=CPHv5SS3GcA
https://www.youtube.com/watch?v=WlYF7gZommU
https://www.youtube.com/watch?v=V52uf9AYU5A
https://www.youtube.com/watch?v=5w20mciYSxU
https://www.youtube.com/watch?v=58vpLYRpWhw
https://www.youtube.com/watch?v=a9p9uHRCi08
https://www.youtube.com/watch?v=ut1mfK5K84w&t

### Problemas encontrados

- Dúvidas relacionado a seu uso por parte do INPE foram debatidos em reunião com o Saulo (#257).

### Conclusão

- Em reunião com o Saulo ficou como trabalho futuro uma reunião com a Ligia Bernardet da NOAA Federal para melhor entendimento da ferramenta.
- Continuidade da exploração interna pela equipe para melhor entendimento da ferramenta.
- Necessidade de alinhamento do padrão de codificação.

**Comment by deniseiras** [comment]
### User Story

COMO (...)
QUEREMOS (...)
PARA (...)

### Critérios de aceite de conclusão da Issue

_(... são os requisitos que a issue deve superar para ser considerada finalizada)_

### Detalhamento adicional da atividade

_(... espaço para detalhar melhor o que deve ser realizado)_

### Impactos

_(... consequência técnica encontrada durante a execução da issue)_

### Dependências

_(... issues e requisitos que devem ser executados previamente)_

### Solução

_(... descrição das etapas das tarefas executadas)_

### Problemas encontrados

_(... problemas técnicos reais apresentados durante a execução das atividades)_

### Conclusão

_(... texto que sintetiza a finalização da issue, destacando aspectos positivos e negativos)_

**Comment by joaomas** [comment]
Encontrei esta documentação: https://ccpp-techdoc.readthedocs.io/en/latest/Overview.html



![Image](https://github.com/monanadmin/monan/assets/41485190/4f0a046e-45bc-44e9-bae0-403bcebbc52c)

**Comment by joaomas** [comment]
Links Eduardo:

https://dtcenter.org/sites/default/files/events/2021/21-20210923-1230-ccpp-overview-carson.pdf
https://dtcenter.org/sites/default/files/events/2021/14-ufs-training-2021-ccpp-srw.pdf

**Comment by egkhamis** [comment]
Memorando de entendimento em que consta unificação do CCPP e CPF (Common Physics Framework) : https://www.weather.gov/media/sti/nggps/18-064553_SignedMOU.pdf

**Comment by joaomas** [comment]
Links e notas refernte a code patterns ou algo similar a isso temos:

Link 1: https://ccpp-techdoc.readthedocs.io/en/latest/CompliantPhysicsParams.html#coding-rules

Link 2: https://docs.google.com/document/d/1bjnyJpJ7T3XeW3zCnhRLTL5a3m4_3XIAUeThUPWD9Tg/edit#heading=h.21je8qtnh1hj - Encontramos uma tabela de "padrão para codificação".


//


**2.5. Coding Rules**

    Code must comply to modern Fortran standards (Fortran 90 or newer), where possible.

    Uppercase file endings (.F, .F90) are preferred to enable preprocessing by default.

    Labeled end statements should be used for modules, subroutines, functions, and type definitions; for example, module scheme_template → end module scheme_template.

    Implicit variable declarations are not allowed. The implicit none statement is mandatory and is preferable at the module-level so that it applies to all the subroutines in the module.

    All intent(out) variables must be set inside the subroutine, including the mandatory variables errflg and errmsg.

    Decomposition-dependent host model data inside the module cannot be permanent, i.e. variables that contain domain-dependent data cannot be kept using the save attribute.

    The use of goto statements is discouraged.

    common blocks are not allowed.

    Schemes are not allowed to abort/stop execution.

    Errors are handled by the host model using the two mandatory arguments errmsg and errflg. In the event of an error, a meaningful error message should be assigned to errmsg and errflg set to a value other than 0. For example:

errmsg = ‘Logic error in scheme xyz: ...’
errflg = 1
return

    Schemes are not allowed to perform I/O operations except for reading lookup tables or other information needed to initialize the scheme, including stdout and stderr. Diagnostic messages are tolerated, but should be minimal.

    Line lengths of no more than 120 characters are suggested for better readability.

Additional coding rules are listed under the Coding Standards section of the NOAA NGGPS Overarching System team document on Code, Data, and Documentation Management for NOAA Environmental Modeling System ([NEMS](https://ccpp-techdoc.readthedocs.io/en/latest/Glossary.html#term-NEMS)) Modeling Applications and Suites (available at https://docs.google.com/document/u/1/d/1bjnyJpJ7T3XeW3zCnhRLTL5a3m4_3XIAUeThUPWD9Tg/edit).

(...)

**2.7. Parallel Programming Rules**

Most often, shared memory (OpenMP: Open Multi-Processing) and distributed memory (MPI: Message Passing Interface) communication is done outside the physics, in which case the loops and arrays already take into account the sizes of the threaded tasks through their input indices and array dimensions.

The following rules should be observed when including OpenMP or MPI communication in a physics scheme:

    CCPP standards require that in every phase but the run phase, blocked data structures must be combined so that their entire contents are available to a given MPI task (i.e. the data structures can not be further subdivided, or “chunked”, within those phases). The run phase may be called by multiple threads in parallel, so data structures may be divided into blocks for that phase.

    Shared-memory (OpenMP) parallelization inside a scheme is allowed with the restriction that the number of OpenMP threads to use is obtained from the host model as an intent(in) argument in the argument list ([Listing 6.2](https://ccpp-techdoc.readthedocs.io/en/latest/HostSideCoding.html#mandatoryvariables)).

    MPI communication is allowed in the init, timestep_init, timestep_finalize, and finalize, phases for the purpose of computing, reading or writing scheme-specific data that is independent of the host model’s data decomposition.

    If MPI is used, it is restricted to global communications: barrier, broadcast, gather, scatter, reduction. Point-to-point communication is not allowed. The MPI communicator must be passed to the physics scheme by the host model, the use of MPI_COMM_WORLD is not allowed ([see list of mandatory variables](https://ccpp-techdoc.readthedocs.io/en/latest/HostSideCoding.html#mandatoryvariables)).

    An example of a valid use of MPI is the initial read of a lookup table of aerosol properties by one or more MPI processes, and its subsequent broadcast to all processes.

    The implementation of reading and writing of data must be scalable to perform efficiently from a few to thousands of tasks.

    Calls to MPI and OpenMP functions, and the import of the MPI and OpenMP libraries, must be guarded by C preprocessor directives as illustrated in the following listing. OpenMP pragmas can be inserted without C preprocessor guards, since they are ignored by the compiler if the OpenMP compiler flag is omitted.

#ifdef MPI
  use mpi
#endif
#ifdef OPENMP
  use omp_lib
#endif
...
#ifdef MPI
  call MPI_BARRIER(mpicomm, ierr)
#endif

#ifdef OPENMP
  me = OMP_GET_THREAD_NUM()
#else
  me = 0
#endif

    For Fortran coarrays, consult with the CCPP Forum (https://dtcenter.org/forum/ccpp-user-support).
