### ISSUE TITLE
PAD: Código ND MPAS v.8.0 standalone sem física

### ISSUE THREAD

**Issue by deniseiras** [monanadmin/monan#258]
### User Story

COMO Saulo,
QUEREMOS Encontrar um ND do MPAS,
PARA Iniciar os futuros desenvolvimentos.

### Critérios de aceite de conclusão da Issue

- Estudar a nova versão 8.0 com base no link: https://github.com/MPAS-Dev/MPAS-Model/tree/v8.0.0/src/core_test
- Explorar as possibilidades de extração do ND da nova versão 8.0 do MPAS

### Detalhamento adicional da atividade

_(... espaço para detalhar melhor o que deve ser realizado)_

### Impactos

_(... consequência técnica encontrada durante a execução da issue)_

### Dependências

_(...)_

### Solução

- Comentar no arquivo src/core_atmosphere/Makefile a linha com PHYSICS:
```
#
# To build a dycore-only MPAS-Atmosphere model, comment-out or delete
# the definition of PHYSICS, below
#
#PHYSICS=-DDO_PHYSICS
```
- Compilar o código seguindo os passos da tarefa #268 

- Serão gerados na compilação os namelists: namelist.atmosphere, streams.atmosphere, stream_list.atmosphere.diagnostics e stream_list.atmosphere.output para a resolução de 120km.

- Adicionar  em &nhyd_model do arquivo namelist.atmosphere a variável config_len_disp:
``` 
&nhyd_model
    config_time_integration_order = 2
    config_dt = 720.0
    config_start_time = '2010-10-23_00:00:00'
    config_run_duration = '0_12:00:00'
    config_split_dynamics_transport = true
    config_number_of_sub_steps = 2
    config_dynamics_split_steps = 3
    config_horiz_mixing = '2d_smagorinsky'
    config_visc4_2dsmag = 0.05
    config_scalar_advection = true
    config_monotonic = true
    config_coef_3rd_order = 0.25
    config_epssm = 0.1
    config_smdiv = 0.1
    config_len_disp = 120000.0
/
```
- Executar seguindo os passos da tarefa #269 com os arquivos de configuração obtidos na compilação. Para um nó com 128 processadores e previsão de 12 horas obtivemos:
<img width="1080" alt="Screenshot 2023-06-27 at 20 16 37" src="https://github.com/monanadmin/monan/assets/98923325/5f9165a3-1e33-47ec-bb12-ee5579783308">

### Problemas encontrados

Algumas dependências não isoladas do ND (pasta core_atmosphere) foram encontradas na solução:

 - Leitura de namelists: pasta tools/namelist_gen.c
 - Funções de timestamp: pasta external  
 - mpas_time_integration.F: pasta dynamics, rotina atm_divergence_damping_3d (aparece no log ao final da execução)
 - e outros a serem investigados.

### Conclusão

- Com a solução encontrada foi possível compilar e executar o ND separadamente, mas ainda com algumas dependências (ver problemas encontados) , que não necessariamente são um problema, e sim dependências que podem ser isoladas da pasta do core dinâmico e reutilizadas por outros módulos, ou que atuam como interfaces para outros módulos.

**Comment by egkhamis** [comment]
Código compilado seguindo os mesmos passos da tarefa #268 substituindo CORE=core_test.

Possibilidade de extração do ND com a ferramenta KGEN: https://www.sciencedirect.com/science/article/pii/S1877050916309504?via%3Dihub
https://github.com/NCAR/KGen

O software KGEN foi utilizado para extrair o núcleo dinâmico da versão serial 4.0 do MPAS: https://github.com/NCAR/kernelOptimization/tree/master/all/MPAS_atm_compute_solve_diagnostics/orig

**Comment by egkhamis** [comment]
[log.test.0000.out.txt](https://github.com/monanadmin/monan/files/11869412/log.test.0000.out.txt)

**Comment by deniseiras** [comment]
Pergunta feita no fórum:
https://forum.mmm.ucar.edu/threads/mpas-dyn-core-extraction.13522/
