### ISSUE TITLE
Avaliação do teste (BM) do BRAMS

### ISSUE THREAD

**Issue by luflarois** [monanadmin/monan#26]
# Descrição

Testar o caso de teste do BRAMS (BM) disponível na página [BM](http://ftp.cptec.inpe.br/pesquisa/bramsrd/toEgeon/bm/bm.tar.bz2). É uma rodada de 8km de resolução para 9 dias e deve ser rodada com muitos processadores (na Egeon se usa 1024). 

# Problemas Abordados

Teste do caso de uso para ser distribuído aos fabricantes

# Dependências

Não há.

# Impactos

Não há.

# Definição da Conclusão

1. Documentação utilizada

https://luflarois.github.io/brams/BRAMS_6.0_INSTALL_PREREQUISITES.html

https://luflarois.github.io/brams/BRAMS_6.0_-_INSTALL_MODEL.html

Aparentemente = a https://github.com/luflarois/brams/blob/master/doc

O https://github.com/luflarois/brams/blob/master/BRAMS_6.0_-_INSTALL_PREREQUISITES.md parece ser antigo. remover ?

2. Passos feitos

2.1 Pre-requisitos

Foi baixado com wget http://ftp.cptec.inpe.br/pesquisa/bramsrd/BRAMS/pre-requisites/prerequisites.tar

dos requisitos, somente a wgrib foi instalada, seguindo o tutorial, pois foram usados módulos na Minerva:

0_env_intel.sh
```
module load shared
module load DefaultModules
module load core
module load intel/compiler/19.1.3.304
module load intel/mpi/2019u12
module load hpc
#module load hwloc/2.5.0
module load netcdf/intel18/openmpi/4.7.4
module load netcdf/intel19/impi/4.7.4

export NETCDF_DIR=/cm/shared/apps/netcdf/gcc/64/4.7.3/
# Environment settings to run a MPI/OpenMP parallel program compiled with Intel MPI
export I_MPI_PMI_LIBRARY=/cm/shared/apps/slurm/20.02.7/lib64/libpmi.so

echo $PATH
echo $LD_LIBRARY_PATH
```

1_pre_requisites.sh
```
YOUR_DIR=$(pwd)
INSTALL_DIR=$YOUR_DIR/install
mkdir ${YOUR_DIR}
mkdir ${YOUR_DIR}/bin
mkdir ${YOUR_DIR}/lib
mkdir ${YOUR_DIR}/include
mkdir ${INSTALL_DIR}
# cd ${INSTALL_DIR}
```

2.2. - Configure the model

Não está especificado como baixar o código fonte. Ex: Clicar em Downloads e depois no github clicar em code gerar zip.

Sugestão: criar Tag e fazer o wget https://github.com/luflarois/brams/archive/refs/heads/master.zip (nesse caso é o master).

3_get_brams.sh
```
wget https://github.com/luflarois/brams/archive/refs/heads/master.zip
```

4_config_make_brams.sh
```
LANG=en_US.utf8
LC_ALL=en_US.utf8

YOUR_DIR=$(pwd)
YOUR_BIN_AREA=$YOUR_DIR/EXEC

cd $YOUR_DIR/brams-master/build

./configure --program-prefix=BRAMS_6.0 --prefix=${YOUR_BIN_AREA} --enable-jules    --with-chem=RELACS_TUV --with-aer=SIMPLE --with-fpcomp=${YOUR_DIR}/bin/mpif90    --with-cpcomp=${YOUR_DIR}/bin/mpicc --with-
fcomp=ifort --with-ccomp=icc --with-netcdff=/home/modules/hpc/netcdf/intel18/openmpi/4.7.4/ --with-netcdfc=/home/modules/hpc/netcdf/intel18/openmpi/4.7.4/

exec_file="$YOUR_BIN_AREA/bin/brams-6.0"
rm $exec_file

make
make install

if [ -f "$exec_file" ]; then

  echo "BRAMS build sucessfully !"
#  make pre-brams
#  make install

else

  echo "BRAMS BUILD FAILED !!! ****************************************************"

fi
```

3. Sugestões:

- Alterar o configure como no item acima e alterar as variáveis de linguagem: Pode ocorrer o erro "Catastrophic error: could not set locale "" to allow processing of multibyte characters"
- retirar o variables.csv do pacote do benchmark
- Corrigir o install do brams, copiando o variables.csv da pasta Bin_files (o install tenta copiar da pasta raiz): não é um arquivo de configuração de execução.
- Sugerir a alteração do arquivo sbatch BRAMS.INI.2022051500.sbatch usand o padrão abaixo:
  - diretório temporário. Ex: export TMPDIR=/work/$USER/brams/bm/tmp (criar o diretório antes)
  - caminho do executável
  - partição de execução

```
#!/bin/bash
#SBATCH --job-name=BO-INI
#SBATCH --nodes=8
#SBATCH --partition=batch
#SBATCH --tasks-per-node=128
#SBATCH --ntasks=1024
#SBATCH --time=02:00:00
#sbatch --mem-per-cpu=64000M
#SBATCH --output=./2022051500_ini_.txt
#SBATCH --exclusive

cd $SLURM_SUBMIT_DIR
echo $SLURM_SUBMIT_DIR

export EXEC_DIR="/work/$USER/brams/bm"
export TMPDIR="${EXEC_DIR}/tmp"

ulimit -s unlimited
export OMP_NUM_THREADS=1

mpirun $EXEC_DIR/brams-6.0 -f $EXEC_DIR../bm/RAMSIN_BASIC_INI_2022051500 >& $EXEC_DIR/2022051500_ini.out
```

No exemplo, a variável $USER retorna o nome de usuário logado.

- Sugestões para o manual de execução:
  - Incluir o texto abaixo:

```
O diretório do benchmark (ex: /work/$USER/brams/bm ) contém:
- RAMSINS
- arquivos de submissão (.sbatch)
- arquivos fixos de entrada (datafix_model)
- arquivos de entrada do dia 2022051500
- diretório tables

Deverá ser copiado para o diretório do benchmark os arquivos gerados na instalação do brams (make install):
- executável do brams
- arquivo variables.csv (acredito que este deveria ser removido do benchmark por ser um arquivo relacionado a versão)
- diretório jules.in
```
4. Erros encontrados:

Ao compilar com openmpi nenhum erro acontece, mas ocorre um erro ao executar, não solucionado:
```
error while loading shared libraries: libopen-orted-mpir.so: cannot open shared object file
```

Ao compilar com impi, ocorre um erro ao compilar (ainda não solucionado)
```
/work/denis.inpe/brams/bin/mpif90  -O3 -fc=ifort -ldl -I/work/denis.inpe/brams/brams-master/build/../src/utils/include -I/work/denis.inpe/brams/brams-master/build/../src/jules-v6.0/preprocess/include -I/work/denis.inpe/brams/brams-master/build/../src/jules-v6.0/preprocess/include/ -I/home/modules/hpc/netcdf/intel18/openmpi/4.7.4//include -DINTEL -DSIMPLE -DJULES -DSCMA -DBL_DIAG_HACK -DMPI_DUMMY -DINTEL_FORTRAN -Dcdf /work/denis.inpe/brams/brams-master/build/../src/brams/ccatt/TUV/mem_tuv.f90 mem_grid.o mem_globrad.o mem_grid_dim_defs.o ModTuv2.7.o ==  mem_tuv.o 
f951: Fatal Error: Reading module ‘modtuv’ at line 1 column 2: Unexpected EOF
compilation terminated.
make: *** [depend_model.mk:208: mem_tuv.o] Error 1

```

**Comment by deniseiras** [comment]
Os dados do referido link da descrição (http://ftp.cptec.inpe.br/pesquisa/bramsrd/toEgeon/bm/bm.tar.bz2)  parece estar corrompido. Erro abaixo.
...
bm/2022051500/dataout/POST/
bm/2022051500/dataout/POST/brams-ams8km-A-2022-05-15-190000-g1.ctl
... mais arquivos
bm/2022051500/dataout/POST/brams-ams8km-A-2022-05-19-070000-g1.gra

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

A primeira vista, o arquivo não foi finalizado durante o processo de compressão.

O sistema de arquivos ext4 suporta arquivos de tamanho de até 16TB. O arquivo em questão possui aproximados 16GB.
Uma pesquisa não identificou tamanho máximo de arquivo bzip2. No entanto, problemas com memória podem te ocorrido durante a gravação do arquivo. Ou o processo não finalizou.

Está sendo testada uma opção de descompressão, como última tentativa:  bunzip2 -v --best bm.tar.bz2
Se não for resolvido, deverá ser refeito o arquivo, idealmente particionado como part1, part2 ...

**Comment by deniseiras** [comment]
A tentativa do comando abaixo falhou. Conforme falado com Luiz Flávio, já está sendo preparada uma nova versão do arquivo.

bunzip2 -v --best bm.tar.bz2
  bm.tar.bz2: 

bunzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bunzip2: No such file or directory
	Input file = bm.tar.bz2, output file = bm.tar

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

**Comment by deniseiras** [comment]
Os arquivos foram disponibilizados em http://ftp.cptec.inpe.br/pesquisa/bramsrd/toEgeon/bm/
[   ]	bm-brams-basic.xz	2022-06-09 09:44	353M	 
[   ]	bm-brams-data.xz	2022-06-09 09:45	32G	 
[   ]	bm-brams-datafix.xz	2022-06-09 09:44	6.7G	 
[   ]	bm-brams-reference.xz	2022-06-09 09:48	124G
