### ISSUE TITLE
Finalizar Relatório de avaliação ND

### ISSUE THREAD

**Issue by deniseiras** [monanadmin/monan#263]
### User Story

COMO PAD
QUEREMOS Finalizar o relatório de avaliação do ND
PARA Entrega para o CC

### Critérios de aceite de conclusão da Issue

- Finalizar as figuras
- Aceitar últimas alterações
- Rever o texto e melhorar

### Detalhamento adicional da atividade

Link do doc em revisão: https://docs.google.com/document/d/10so1mJXFAi6Qkaq1TMsYOcEescfPI0coZ-fXJXFrN60/edit#heading=h.pgh675kc4e19

### Impactos

Nenhum.

### Dependências

Nenhuma.

### Solução

- Scripts e figuras geradas neles disponíveis em http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/github_issues_files/monan-245/

### Problemas encontrados

Nenhum.

### Conclusão

- Foi gerado um PDF a partir da versão do link acima disponível no Google Drive e entregue ao Saulo.
- Como trabalho futuro teremos uma nova versão no padrão da biblioteca INPE.

**Comment by joaomas** [comment]
Anotações feitas diretamente no DOC no GDrive.
