### ISSUE TITLE
PAD: Escalabilidade do MPAS v.8.0 na Egeon

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#270]
# User Story

COMO Saulo,
QUEREMOS Fazer a escalabilidade do MPAS v.8.0 na Egeon
PARA Realizar experimento de PEE a ser agregado na documentação de avaliação do ND ao Comitê Científico do MONAN.

# Critérios de aceite de conclusão da Issue

- Rodar modelo MPAS de 1 a 32 nós (step 1, 2, 4, 8, 16, 32) com resolução de 15km 
- Seguir com os parâmetros e metodologia do Relatório de avaliação do ND.

# Detalhamento adicional da atividade

N.A.

# Impactos

N.A.

# Dependências

- #269
- Interessante também consultar a tarefa #98 , que detalha o mesmo experimento para o MPAS versão  6.3.

# Solução

1. O primeiro experimento básico foi definido como:
- rodadas com período de previsão de 24h;
- Utilizando resolução de 15km, pacote de benchmark do próprio repositório do MPAS;
- Executável compilado com Intel+IMPI
- Utilizando 128 cores por nó;
- Medir a escalabilidade do MPASv8 em 1, 2, 4, 8, 16 e 32 nós, respectivamente: 128, 256, 512, 1024, 2048 e 4096 cores, utilizando como referencia o tempo de execução em 1 nó;
- Utilizando a média do tempo de execução de três instâncias da mesma previsão;

2. Utilizei um conjunto de dois scripts para submissão automática das três rodadas para cada configuração de cores:

- O script `run_make_submit.sh` configura as filas, walltime, quantidade de cores, nós, cores por nós, e touras séries de parâmetros para então chamar o próximo script:
~~~
#!/bin/bash 

SFILA="PESQ2"
BFILA="batch"

# cores: 2 4 8 16 32 64 128 256 512 1024 2048 4096
# nodes: 1 1 1  1  1  1   1   2   4    8   16   32

# E1: 128 cpn:
exp="E1v8"
ncpn=128; nthreads=1; label="${exp}${ncpn}cpn_SP_Int_PIO"; cpubind="cores"; dist="block:cyclic"

# 64cpn:
#for ncores in 64 #128 256 512 1024 2048

# 128cpn:
for ncores in 128 256 512 1024 2048 4096
do


   # encontra o numero de nos: 0.?? -> 1, 1->1, 2->2, ...
   nnodes=$(echo "scale=0; (${ncores}+${ncpn}-1)/${ncpn}" | bc -l)

   if [ ${nnodes} -lt 8 ]
   then
      fila=${SFILA}
   else
      fila=${BFILA}
   fi
   
   # 3 instancias de cada rodada:
   for i in 1 2 3
   do
      echo "make_submit.sh ${nnodes} ${ncpn} ${ncores} ${nthreads} ${fila} ${label} ${i} ${cpubind} ${dist} ${exp}"
      make_submit.sh ${nnodes} ${ncpn} ${ncores} ${nthreads} ${fila} ${label} ${i} ${cpubind} ${dist} ${exp}
      sleep 5
   done
   echo ""
   sleep 5
done

exit
~~~

- O script `make_submit.sh` listado abaixo chamado pelo script anterior e é responsável por construir o script de submissão `submit.sh` e submetê-lo no sistema:
~~~
#!/bin/bash

if [ $# -ne 10 ] 
then
   echo ""
   echo "Usage:"
   echo ""
   echo "${0} Nnodes NcoresPN totalNC nThreads FILA LABEL INST"
   echo ""
   echo "Nnodes   :: num. de nos."
   echo "NcoresPN :: num de cores por no."
   echo "totalNC  :: num total de cores."
   echo "nThreads :: num total de threads OMP"
   echo "FILA     :: PESQ1, PESQ2, batch, ..."
   echo "LABEL    :: nome para o experimento."
   echo "            ex: controle, debug1, etc..."
   echo "INST     :: instancia da rododa, p.ex: 1, 2, 3, ..."
   echo "cpu_bind :: cores (D) ou socket"
   echo "distrib  :: block:block, block:cyclic, cyclic:block ou cyclic:cyclic" 
   echo "exp      :: E3A1, ..."
   echo ""
   
   exit
fi

nnodes=${1}
cpn=${2}
ncores=${3}
nthreads=${4}
fila=${5}
label=${6}
inst=${7}
cpubind=${8}
dist=${9}
exp=${10}


# E1:
dirmodel=MPAS-A_benchmark_15km_L56; diroper=${dirmodel}_OPER;jobn="${exp}${ncores}"

dirtrab=${dirmodel}_${label}
dirrodada=run-${nnodes}-${cpn}-${ncores}-${inst}
dirroot=$(pwd)

#rm -fr  ${dirroot}/${dirtrab}
mkdir -p ${dirroot}/${dirtrab}/${dirrodada}

cd ${dirroot}/${diroper}
for i in *
do
   cd ${dirroot}/${dirtrab}/${dirrodada}
   ln -fs ${dirroot}/${diroper}/${i} ${i}
done

if [ ${fila} == "PESQ1" ]
then
   wtime="12:00:00"
fi
if [ ${fila} == "PESQ2" ]
then
   wtime="12:00:00"
fi
if [ ${fila} == "PESQ3" ]
then
   wtime="2:00:00"
fi
if [ ${fila} == "batch" ]
then
   wtime="4:00:00"
fi
if [ ${fila} == "proc" ]
then
   wtime="4:00:00"
fi

cd ${dirroot}/${dirtrab}/${dirrodada}
cat << EOF > ${dirroot}/${dirtrab}/${dirrodada}/submit_${label}.sh
#!/bin/bash
#SBATCH --nodes=${nnodes}           # numero de nos (-N)
#SBATCH --tasks-per-node=${cpn}     # numero de tarefas MPI por no
#SBATCH --ntasks=${ncores}          # numero total de tarefas MPI (-n)
#SBATCH --cpus-per-task=${nthreads} # numero de threads por tarefa MPI  (-c)
#SBATCH --partition=${fila}         # fila a ser utilizada (-p)
#SBATCH --job-name=${jobn}          # nome job (-J)
#SBATCH --time=${wtime}             # tempo estimado do job
#SBATCH --exclusive                 # aloca o no todo exclusivo pro job
#SBATCH --verbose                   # mais mensagens do slurm (-v)

executable=atmosphere_model

. /mnt/beegfs/carlos.souza/spack_mpas_intel/env_mpasv8.sh
export LC_ALL="en_US.UTF-8"

spack load --only dependencies mpas-model%intel@2021.4.0
spack load --list

module list
lscpu
env

resultdir=${dirroot}/${dirtrab}/results/partition-\${SLURM_JOB_PARTITION}/NUMNODES-\$SLURM_JOB_NUM_NODES/MPI-\${SLURM_NTASKS}/JOBID-\${SLURM_JOBID}

mkdir -p \${resultdir}

#export MPAS_DYNAMICS_RANKS_PER_NODE=2
#export MPAS_RADIATION_RANKS_PER_NODE=6
#export MALLOCSTATS=1

ulimit -s unlimited

export OMP_NUM_THREADS=\${SLURM_CPUS_PER_TASK}
export MKL_NUM_THREADS=\${SLURM_CPUS_PER_TASK}
export I_MPI_DEBUG=5
export MKL_DEBUG_CPU_TYPE=5
export I_MPI_FABRICS=shm:ofi

cd  \$SLURM_SUBMIT_DIR
#ls  \$SLURM_SUBMIT_DIR
#touch x1.2621442.init.nc 
echo \$SLURM_JOB_NUM_NODES

date
echo "mpirun ./\${executable}"
time mpirun ./\${executable}
date

cp slurm-\${SLURM_JOBID}.out \${resultdir}/
cp log.atmosphere.*.out \${resultdir}/
cp namelist.atmosphere \${resultdir}/
cp submit*.sh \${resultdir}/
mv x1.*.init.nc-*.lock \${resultdir}/
mv diag* \${resultdir}/
mv histor* \${resultdir}/ 

exit
EOF

chmod a+x ${dirroot}/${dirtrab}/${dirrodada}/submit_${label}.sh

sbatch submit_${label}.sh
~~~

3. Rodadas submetidas e executadas com sucesso.

**Observações**

- Foi testada também uma compilação com o parâmetro USE_PIO desligado, e esta funcionou, inclusive uma execução simples.
- Os tempos estranhos com 32 nós estão na leitura das condições iniciais: "initialize, read_ICs". comparando com 16 nós, todos os outros tempos estão coerentes.
- Encontrou-se o manual https://www2.mmm.ucar.edu/projects/mpas/mpas_atmosphere_users_guide_8.0.pdf
- O manual indica possíveis configurações:
  - O arquivo streams.atmosphere o i/o está configurado como: io_type="pnetcdf,cdf5". O parallel netcdf deveria escalar bem; outro teste possível seria alterar para netcdf4
  - na pagina 46 do manual temos a configuração do I/O com as variáveis config_pio_num_iotasks (default = 0) e config_pio_stride (default=1). Não estamos obtendo bom desempenho na leitura das condições iniciais pois deveríamos setar config_pio_num_iotasks= #MPI tasks... acredito que seja esse o problema quando vamos para 32 nós
  - verificar io_type da pagina 17/18 
# Problemas encontrados

- A máquina egeon não possui uma política de filas bem construída, dificultando o melhor aproveitamento dos recursos da máquina, isso acarreta em atraso nas execuções que exigem maiores recursos.

# Conclusão

- Rodadas submetidas e executadas com sucesso.
- Futuros testes (sugestões):
E1 = run 24h; PIO; Intel; inter-nós; 128cpn
E2 = run 24h; PIO; Intel; inter-nós; 64cpn
E3 = run 24h; PIO; Intel; inter-nós; 32cpn
E4 = run 24h; PIO; Intel; intra-nó;
E5 = run 24h; PIO; Intel; inter-nós; fixando ncores, variando nnodes
- Sugestões OpenMP.

**Comment by joaomas** [comment]
A issue referida sobre Compilar MPAS na Egeon é a #54 

Dica para a pesquisa:



![Image](https://github.com/monanadmin/monan/assets/41485190/eb8d3604-a915-4d5d-ad8d-98f67b2f296e)

**Comment by carlosrenatosouza2** [comment]
E1 = run 24h; PIO; Intel; inter-nós; 128cpn
E2 = run 24h; PIO; Intel; inter-nós; 64cpn
E3 = run 24h; PIO; Intel; inter-nós; 32cpn
E4 = run 24h; PIO; Intel; intra-nó; 
E5 = run 24h; PIO; Intel; inter-nós; fixando ncores, variando nnodes

**Comment by joaomas** [comment]
![Image](https://github.com/monanadmin/monan/assets/41485190/3f764c89-3aa5-4086-a577-28de2d91682b)

Fonte: https://www2.cisl.ucar.edu/sites/default/files/2021-10/KISTI%20-%20Joh%2C%20Kang%2C%20%26%20Kim.pdf
