### ISSUE TITLE
PAD: Pré-Execução MPAS v.8.0 do SDumont

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#277]
### User Story

COMO Saulo,
QUEREMOS Pré-Executar o MPAS v.8.0 no SDumont
PARA Realizar experimento de PEE a ser agregado na documentação de avaliação do ND ao Comite Científico do MONAN.

### Critérios de aceite de conclusão da Issue

- Pré-Executar o MPAS v.8.0 com resolução preparatória (e.g. 120km).
- Seguir com os parâmetros e metodologia do Relatório de avaliação do ND.

### Detalhamento adicional da atividade

_(... espaço para detalhar melhor o que deve ser realizado)_

### Impactos

_(... consequência técnica encontrada durante a execução da issue)_

### Dependências

_(... issues e requisitos que devem ser executados previamente)_

### Solução
**Esta solução é valida somente para usuários do _account_ `cenapadrjsd`**

- O executável do MPAS v.8.0 está no seguinte caminho no SDumont:
```bash
/scratch/cenapadrjsd/rpsouto/sequana/projetos/monan/dyncore/mpas/github/MPAS-Model_v8.0.0_intel/atmosphere_model 
```
- Copiar o benchmark de 15km para sua área de scratch:
```bash
cp /scratch/cenapadrjsd/rpsouto/sequana/projetos/monan/dyncore/mpas/benchmark/v7.0/MPAS-A_benchmark_15km_v7.0.tar.gz   $SCRATCH/
```
- Descompactar o arquivo do benchmark
```bash
cd $SCRATCH
tar zxvf MPAS-A_benchmark_15km_v7.0.tar.gz
```
- Entrar na pasta descompactada e criar o script de submissão `submit_atmosphere_v8_intel.sh` com este conteúdo:
```bash
#!/bin/bash
#SBATCH --nodes=1                                  #Número de Nós
#SBATCH --ntasks=1                                  #Numero total de tarefas MPI
#SBATCH -p sequana_gpu_dev                  #Fila (partition) a ser utilizada
#SBATCH -J mpas_v8                                    #Nome job
#SBATCH --time=00:20:00                         #Obrigatório

module load sequana/current
module load python/3.8.2_sequana
source /scratch/opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
source /scratch/opt/intel/compilers_and_libraries/linux//mkl/bin/mklvars.sh intel64
source /scratch/opt/intel/compilers_and_libraries/linux/mpi/intel64/bin/mpivars.sh intel64

. /scratch/cenapadrjsd/rpsouto/sequana/usr/local/spack/git/spack/share/spack/setup-env.sh
export SPACK_USER_CONFIG_PATH=/scratch/cenapadrjsd/rpsouto/sequana/.spack/v0.17.1

export NETCDF=$(spack location -i netcdf-c@4.8.1%intel@18.0.5)
export PNETCDF=$(spack location -i parallel-netcdf@1.12.2%intel@18.0.5)

export LD_LIBRARY_PATH=$NETCDF/lib:$PNETCDF/lib:$LD_LIBRARY_PATH

ldd ./atmosphere_model_v8_intel

cd  $SLURM_SUBMIT_DIR
mpirun -n $SLURM_NTASKS ./atmosphere_model_v8_intel

```
onde `atmosphere_model_v8_intel` pode ser um _link simbólico_ para o executável do MPAS 8, que está localizado no caminho previamente informado.

- Lembrar de copiar as tabelas `*.TBL` da versão 8 do MPAS, para esta mesma pasta do benchmark.
- Alterar o tempo de integração da rodada, para testar com 2h, no arquivo `namelist.atmosphere`:
```bash
   config_run_duration = '02:00:00'
```
- Submeter um job em 1 nó do SDumont:
```bash
sbatch -p sequana_cpu -N1 -n48 --time=04:00:00 submit_atmosphere_v8_intel.sh
```

### Problemas encontrados

_(... problemas técnicos reais apresentados durante a execução das atividades)_

### Conclusão

- Execução de teste executado com sucesso (João).

**Comment by robertopsouto** [comment]
@ebiduardo e @joaomas , coloquei na descrição da issue umas instruções para executar o MPAS 8 no SDumont, compilado com Intel-MPI. Bidu, poderia testar, por favor?

**Comment by ebiduardo** [comment]
O MPAS paraleo usa um arquivo de entrada criado pelo programa METIS que precisa existir antes da execução.
O arquivo é diferente par cada numero de processador usado na execução.

Qual será a melhor forma de incluir isso no fluxo de execução?

**Comment by joaomas** [comment]
Issue de execução na Egeon #269 - https://github.com/monanadmin/monan/issues/269
