### ISSUE TITLE
GRC: Estudo padrão de codificação MPAS

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#281]
### User Story

COMO Saulo,
QUEREMOS Fazer um estudo do padrão de codificação usado no MPAS,
PARA Alinhar os padrões utilizado no MONAN.

### Critérios de aceite de conclusão da Issue

- Fazer estudo do padrão de codificação do MPAS.
- Este estudo será utilizado na issue de comparação entre os padrões #265 

### Detalhamento adicional da atividade

_-

### Impactos

_-

### Dependências

_-

### Solução

**Regras MPAS** [1]

Development guidelines

As developers of MPAS, we attempt to make the code look as uniform as we can across the entire code-base. In order to enforce this, there are a set of guidelines developers should follow.

- Each core has a name, and an abbreviation. For example, the shallow water core is called sw and it’s abbreviation is sw, but the ocean core is called ocean and it’s abbreviation is ocn.
- All subroutines should be named in a manner which prevents namespace conflicts.
- Shared functions/subroutines are simply named mpas subroutine name. Core specific functions/subroutines are named mpas abbrev subroutine name (where abbrev is replaced with the cores abbreviation).e.g. mpas atm time integration
- Subroutine names should all be lower case, with underscores in place of spaces (e.g. see above).
- Variable names should be mixed case (e.g. cellsOnCell rather than cells on cell). 
- In general, variable names should be self-descriptive (e.g. nCells rather than n).
- Subroutines and modules should be appropriately documented. Shared portions of MPAS code use doxygen comments, but core developers are free to decide what method of documenting they prefer.
- Development of shared parts of MPAS need reviews from multiple core maintainers prior to a merge.
- Development within a core should be approved by other core developers before being merged into that core.
- Development within a core should follow the practices of that core’s developer group, for documentation etc.
- Core related testing is the responsibility of that core’s maintainers/developers. Core maintainers need to approve changes before the changes appear on the shared repository. Core maintainers are also responsible for reviewing changes to shared code that affect multiple cores.

**Referências:**
[1] https://mpas-dev.github.io/files/documents/MPAS-DevelopersGuide.pdf

### Problemas encontrados

_-

### Conclusão

As principais regras foram levantadas e serão agora utilizadas na issue de comparação com a DTN-01 e as demais regras do CCPP e NOAA.

**Comment by klclaudio** [comment]
> (...)

Elaboração de  documento com as regras de codificação.
