### ISSUE TITLE
PAD: Estudo sobre o acoplamento de nova física no ND do MPAS (Spike)

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#283]
### User Story

COMO Saulo,
QUEREMOS Entender como acoplar uma nova física no ND do MPAS (v8.0.1),
PARA Preparar futuro desenvolvimentos de novas físicas.

### Critérios de aceite de conclusão da Issue

- Estudar o código do ND referente ao acoplamento de nova física.
- Documentar o processo de acoplamento de uma nova física.

### Detalhamento adicional da atividade

_(... espaço para detalhar melhor o que deve ser realizado)_

### Impactos

_(... consequência técnica encontrada durante a execução da issue)_

### Dependências

_(... issues e requisitos que devem ser executados previamente)_

### Solução

Estão sendo abordadas duas frentes:
1. Análise do código de um modelo com MPAS 
2. Estudo estendido do CCPP

#### 1. Análise do código de um modelo com MPAS 

Primeiro passo: identificar a árvore de chamadas:
- executar o kprof para verificação da árvore de chamadas executada: Foi utilizado o MPAS com benchmark de 15 km, da tarefa #275, em `/mnt/beegfs/denis.eiras/monan_github_issues_workspace/275/MPAS-A_benchmark_15km_L56` . 
- O executável foi compilado com o comando `make.sh`, incluindo as flags`-g e -pg` na linha abaixo do arquivo Makefile em `/mnt/beegfs/denis.eiras/monan_github_issues_workspace/275/regional-demo/MPAS-Model_v8.0`:
~~~
"FFLAGS_OPT = -std=f2008 -O3 -ffree-line-length-none -fconvert=big-endian -ffree-form -g -pg" \
"LDFLAGS_OPT = -O3 -pg -g" \
~~~

- O MPAS foi executado usando na pasta do benchmark usando o submit_atmosphere.sh, com o namelist alterado para executar com 1h de previsão, gerando o arquivo gmon.out
- O kprof foi executado: `gprof --graph ./atmosphere_model > gprof.out`. O resultado está disponível em http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/github_issues_files/monan-283/gprof.out para investigação nas próximas tarefas, se encerra o tempo desta sprint.

#### 2. Estudo estendido do CCPP

Anteriormente o CCPP foi estudado em #256. Mais algumas informações foram compiladas aqui.

Home do CCPP
- https://dtcenter.org/community-code/common-community-physics-package-ccpp
- Contém links importantes à direita, como informações para desenvolvedores

Wiki
- https://github.com/NCAR/ccpp-framework/wiki

Informações para desenvolvedores
- https://dtcenter.org/community-code/common-community-physics-package-ccpp/developer-info 
- Existem dois documentos que ajudam a começar:
  - O Guia do Usuário do SCM (single column model) explica como configurar, compilar e executar um caso de teste simples usando o SCM: https://dtcenter.org/sites/default/files/paragraph/scm-ccpp-guide-v5.0.0.pdf
  - O guia técnico de uso do CCPP, como configurar uma nova física e como adapatar o modelo para tal. Documentação atualizada por versão: https://dtcenter.org/community-code/common-community-physics-package-ccpp/documentation
- Repositórios
  - O diretório do repositório contém todo o código e dados necessários para executar o CCPP SCM. Ele é funcionalmente separado em três subdiretórios que representam a infraestrutura do modelo SCM:
    - Infraestrutura do modelo SCM (diretório scm) https://github.com/NCAR/ccpp-scm
    - Infraestrutura CCPP (diretório ccpp/framework) - https://github.com/NCAR/ccpp-framework
    - Esquemas físicos CCPP (diretório ccpp/physics) - https://github.com/NCAR/ccpp-physics
    - Documentação Técnica - https://github.com/NCAR/ccpp-doc

Papers e informativos
- [Framework v6.0](https://gmd.copernicus.org/articles/16/2235/2023/)
- [System for Integrated Modeling of the Atmosphere (SIMA) project](https://sima.ucar.edu/)
  - [Resumo - Lead Story: SIMA: Constructing A Single Atmospheric Modeling System For Addressing Frontier Science Topics](https://dtcenter.org/news/2022/04/sima-constructing-single-atmospheric-modeling-system-addressing-frontier-science-topics)
  - Objetivo: "The System for Integrated Modeling of the Atmosphere (SIMA) project aims to unify existing NCAR community atmosphere modeling efforts across weather, climate, chemistry, and geospace research"
  - Uso do CCPP: "A suite of physics parameterizations from WRF and CAM are being modified to be CCPP compliant and thus, will become available as part of SIMA. Recently, software engineers and scientists at NCAR, the DTC, and NOAA held a series of discussions about the usefulness of CCPP for the physics suite in CAM as well as any future SIMA needs that CCPP does not yet address. In summary, the CCPP should improve the efficiency of future CAM code development and maintenance, which will enable other modeling system advancements. CCPP is easy to build upon, is explicit, and its implementation facilitates the detection of bugs and inconsistencies. At the same time, it is understood that the CCPP framework will not do everything needed or desired for the modeling system, and additional steps will need to be taken to achieve specific requirements."
 
- [Passos para adicinonar uma física - v3](https://dtcenter.ucar.edu/GMTB/v3.0/ccpp_tech_guide/AddingNewSchemes.html)

### Problemas encontrados

- A execução do Bench do MPAS com opções para executar com o gprof aparentemente está causando out of memory, ao executar com 128 processos. Executou com 256 processos.

### Conclusão

1. Analisada árvore de chamadas com o gprof/kprof , mas não houve tempo hábil para análise dos resultados. A ser incluído no backlog.
2. Maior compreensão do CCPP e mais documentação documentada aqui.

**Comment by ebiduardo** [comment]
podemos incluir esta imagem do arquivo log.atmosphere.0000.out
![Imagem do WhatsApp de 2023-07-19 à(s) 09 57 10](https://github.com/monanadmin/monan/assets/14222114/05ab7176-7dfd-4b7c-8b10-2b940c08502a)
