### ISSUE TITLE
CANCELADO - [GCC] PAD: Estudar as informações sobre o pós-processamento do MPAS

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#299]
### User Story

COMO Saulo,
QUEREMOS conhecer e entender o pós-processamento do MPAS,
PARA criar um ambiente de desenvolvimento do MPAS 30km no Egeon.

### Critérios de aceite de conclusão da Issue

- Ler os manuais, user guide e outros relacionados ao pós-processamento do MPAS;
- Coletar e documentar as informações encontradas.

### Detalhamento adicional da atividade

Interessante olhar a issue https://github.com/monanadmin/monan/issues/262

### Impactos

_(... consequência técnica encontrada durante a execução da issue)_

### Dependências

_(... issues e requisitos que devem ser executados previamente)_

### Solução

_(... descrição das etapas das tarefas executadas)_

### Problemas encontrados

_(... problemas técnicos reais apresentados durante a execução das atividades)_

### Conclusão

[João] - Será seguido o material do GAM.

**Comment by joaomas** [comment]
@ebiduardo e @robertopsouto aqui esta a Issue que o @egkhamis fez em relação ao pós da USP: https://github.com/monanadmin/monan/issues/262

**Comment by joaomas** [comment]
#297

**Comment by ebiduardo** [comment]
Encontrei o seguinte site:
https://mpas-dev.github.io/MPAS-Analysis/1.5.0/config/output.html
[MPAS-Analysis](https://mpas-dev.github.io/MPAS-Analysis/1.5.0/config/output.html)

**Comment by joaomas** [comment]
![Image](https://github.com/monanadmin/monan/assets/41485190/f2f198c8-f09c-4163-9411-fad2add55692)

**Comment by joaomas** [comment]
Será seguido o material do GAM.
