### ISSUE TITLE
[GCC] PAD: Teste e uso do guia de usuário do MPAS elaborado pelo GAM

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#304]
### User Story

COMO GAM
QUEREMOS testar e usar o guia de usuário do MPAS elaborado pelo GAM,
PARA contribuir na melhoria de sua qualidade.

### Critérios de aceite de conclusão da Issue

- Ler o guia de usuário do MPAS elaborado pelo GAM.
- Executar as etapas do documento no que diz respeito a parte computacional.
- Documentar possíveis correções ou melhorias no manual e enviar para o GAM

### Detalhamento adicional da atividade

Link do documento "Model for Prediction Across Scales-Atmosphere (MPAS-A) on INPE's EGEON System User's Guide" - https://www.researchgate.net/publication/367034083_Model_for_Prediction_Across_Scales-Atmosphere_MPAS-A_on_INPE's_EGEON_System_User's_Guide

Também foi enviado por e-mail o documento, que já tem modificações pela Ariane. Será usado este.

Tempo gasto: 1h

### Impactos

N.A.

### Dependências

- #296

### Solução

A resolução consistiu no upload do manual enviado por e-mail na pasta de issues do grupo GCC/Board_GCC_Monan/Milestones_Issues_docs/304, leitura do manual, executando os comandos na Egeon e atualizando o manual com sugestões no documento:
- https://docs.google.com/document/d/15BUnj6v_ON0hhJ4_Vr0bQnsPxewqPpZd/edit?usp=sharing&ouid=110017012627035408995&rtpof=true&sd=true

O manual foi atualizado, inserindo os scripts ao final, corrigidos comandos dentro do manual e feitas melhorias nos textos.

Os dados foram organizados na pasta /pesq/share/dmdcc/dist/monan/github_issues_files/304

Foram anotados comentários de onde se pode conseguir os arquivos originários dos sites do mpas e gfs para futura documentação e scripts que serão executados fora da Egeon.

O documento foi compartilhado com Pablo e Ariane.

### Problemas encontrados

Um problema no script envSpack.sh (diretórios temporários indefinidos - corrigido no documento) fez com que a compilação do MPAS7.1 falhasse (erro ao criar diretório temporário na raiz). 

Após a correção do script e compilação, tentou-se instalar o MPAS6.3, executando o script make_mpas_gnu.sh, mas duas versões do netcdf-c e netcdf-fortran foram encontradas, ocasionando um erro na parte do script abaixo:
~~~
export NETCDF=`spack location -i netcdf-c@4.8.1%${compiler}`
export PNETCDF=`spack location -i parallel-netcdf@1.12.2%${compiler}`
~~~

Logo, foi necessário desinstalar todos os pacotes, devido a complexidade de se desinstalar os pacotes netcdf corretos e suas as dependências.

~~~
spack uninstall -a
~~~
Em seguida, instalou-se novamente o MPAS@7.1 e prosseguiu-se com o manual.

Também foram encontrados erros no arquivo disponibilizados pelo Pablo. Por este motivo, os dados foram extraídos no diretório e nos passado em  /pesq/share/wrf/dist/EGEON/MPAS/data

Foi identificada a falta de arquivos invariant do ERA 5, e estes foram copiados e inseridos no tar de dados em /pesq/share/dmdcc/dist/monan/github_issues_files/304

### Conclusão

Manual executado e corrigido, scripts incluídos e dados organizados.
Foram anotados nos comentários de onde se pode conseguir os arquivos para futura documentação e scripts que serão executados fora da Egeon.

**Comment by deniseiras** [comment]
Aguardando liberação de área FTP ou Pablo disponibilizar os arquivos 


![Image](https://github.com/monanadmin/monan/assets/6113640/3e307a37-c26f-4f80-b24a-d46032c4a5e1)

**Comment by joaomas** [comment]
ok.. suporte da COIDS foi acionado.

**Comment by joaomas** [comment]
@deniseiras o suporte retornou informando que existe um bloqueio de segurança para arquivos ".xz", então não temos um "erro" e sim uma nova política de uso do storage. Neste caso, acredito que o melhor caminho é reportar ao GAM que não é possível seguir o manual devido a isso. Como o arquivo são de responsabilidade de lá, é mais assertivo a resolução por parte deles junto ao suporte, caso escolham o caminho da liberação "temporária" do arquivo.

**Comment by joaomas** [comment]
Suporte fez uma liberação na área com autorização da chefia do SESUP-COIDS.

**Comment by deniseiras** [comment]
tentando resolver problema da VPN. continuando como blocked

**Comment by deniseiras** [comment]
Uma das tentativas que manteve a vpn conectada foi a abaixo. No entanto, a conexão com a Egeon cai, e é preciso relogar
~~~bash
#!/bin/bash

# To use --ping-restart need to move keepalive 30 100 from the .openvpn file
EGEON='egeon.cptec.inpe.br'
VPN_CONFIG_FILE='/media/denis/dados/_COM_BACKUP/inpe/VPN_HPC/VPN_HPC_v2_4.ovpn' 
CREDENTIALS_FILE="credentials.txt"

# credentials.txt file must be readable only by you and looks like:
# myusername
# mypass

while true; do

  # Check if VPN server is reachable
  keyscan_output=$(ssh-keyscan $EGEON 2>&1)

  # Check the exit status of ssh-keyscan
#  if [ $? -eq 0 ]; then
#     echo "EGEON server is reachable."

#  else         
     echo "VPN server is not reachable."
     # Disconnect existing VPN connection (if any)
     #     sudo killall openvpn
            
     # Reconnect VPN
     sudo openvpn --config "$VPN_CONFIG_FILE" --auth-user-pass $CREDENTIALS_FILE --ping-restart 20

 # fi    

  # wait a bit before restarting ...
  sleep 10  # Check every x secs

done
~~~

**Comment by deniseiras** [comment]
Outra tentativa foi atualizar a versão da vpn, pois encontrou-se esse tipo de erro em fóruns, com versões 2.3.8 e 2.4, mas esta já está em sua última versão possível para o Ubunt 18.04 bionic, que é a 2.4.4.

**Comment by deniseiras** [comment]
conseguiu-se atualizar para a v 2.5.9 , mas não resolveu.

**Comment by deniseiras** [comment]
Output de conexão em outro WIFI que não resulta em queda de VPN (VPN 2.5):

~~~
denis@denis-dell:~$sudo openvpn /media/denis/dados/_COM_BACKUP/inpe/VPN_HPC/VPN_HPC_v2_5_newer.ovpn
2023-08-14 09:21:19 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
2023-08-14 09:21:19 OpenVPN 2.5.9 i686-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 14 2023
2023-08-14 09:21:19 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
Enter Auth Username: denis.eiras
Enter Auth Password: *****************
2023-08-14 09:21:34 WARNING: normally if you use --mssfix and/or --fragment, you should also set --tun-mtu 1500 (currently it is 9000)
2023-08-14 09:21:34 TCP/UDP: Preserving recently used remote address: [AF_INET]150.163.160.254:1195
2023-08-14 09:21:34 UDP link local (bound): [AF_INET][undef]:0
2023-08-14 09:21:34 UDP link remote: [AF_INET]150.163.160.254:1195
2023-08-14 09:21:35 [SSLVPN Server Certificate HPC] Peer Connection Initiated with [AF_INET]150.163.160.254:1195
2023-08-14 09:21:36 TUN/TAP device tun0 opened
2023-08-14 09:21:36 /sbin/ip link set dev tun0 up mtu 9000
2023-08-14 09:21:36 /sbin/ip link set dev tun0 up
2023-08-14 09:21:36 /sbin/ip addr add dev tun0 172.20.128.10/17
2023-08-14 09:21:36 Initialization Sequence Completed
~~~


Próximo comentário incluirá o output de conexão do WIFI problemático.

**Comment by joaomas** [comment]
Necessidade de abertura de OS junto ao provedor. Dica extra é a verificação dos logs do modem do provedor, pois nele existe um firewall próprio.

**Comment by deniseiras** [comment]
trabalhando em WIFI alternativo - Issue desbloqueada. Será aberta OS junto ao provedor para solucionar a VPN.

**Comment by deniseiras** [comment]
Visita técnica para problema com VPN agendada para dia 18/08 das 11h as 14h.

**Comment by deniseiras** [comment]
Visita técnica antecipada para 15/08. Foram 3 acionamentos de técnicos mas o problema não foi resolvido.
- Tentou-se resetar modem e limpar cache
- Tentou-se alterar a criptografia de WPA2 - PSK para WPA 2
- Finalmente um procedimento de "liberação para empresas" foi efetuado (acredito que se refira a WPA 2 para empresas, pois após a alteração a tela de configuração da rede WPA 2 aparecia solicitando mais configurações e não conectava. Por esse motivo, fiquei sem internet. A solução foi voltar a configuração para WPA2 - PSK.

**Comment by joaomas** [comment]
Verifiquem a possibilidade de não ser restrição de arquivos do NetApp neste erro de descompactação.. é possível que tenhamos alguns milhares de extensões de arquivos bloqueadas pela COIDS.

**Comment by deniseiras** [comment]
Pablo responde com área descompactada.

**Comment by deniseiras** [comment]
Pessoal,
Como no protocolo dos modelos regionais. No caso do MPAS 
cd /mnt/beegfs/$USER
descompactar os *.xz e criaram as arvores de diretórios respectivos. 

MPAS/testcase
MPAS/exec
MPAS/data

**Comment by deniseiras** [comment]
Denis,
Os dados do *.xz estão disponíveis em:

 /pesq/share/wrf/dist/EGEON/MPAS/data

Abraço,

Pablo

**Comment by deniseiras** [comment]
Denis,
Os dados básicos no seguinte link:

https://www2.mmm.ucar.edu/wrf/src/wps_files/geog_high_res_mandatory.tar.gz

Pablo


On Fri, Aug 18, 2023 at 4:45 PM Denis Magalhães de Almeida Eiras <[denis.eiras@inpe.br](mailto:denis.eiras@inpe.br)> wrote:

    Qual seria a opção de download dentro desta página ?


    Em 18/08/2023 16:44, Julio Pablo Reyes Fernandez escreveu:
>     Denis,
>     Os dados são fornecidos pelo NCAR e usado pelos seus modelos (WRF/MPAS/CESM etc.). O site a seguir:
>
>     https://www2.mmm.ucar.edu/wrf/users/download/get_sources_wps_geog.html
>
>     Pablo

**Comment by deniseiras** [comment]
Ola Denis,

Para o demo modificar o prec.gs para 3 horas, simplesmente mudar:: 
... 
*'set t 13'
*'pr12=rainc+rainnc'
*'set t 37'
*'pr36=rainc+rainnc'
'set t 4'
'pr03=rainc+rainnc'
...
*'d pr36-pr12'
'd pr03'
*'draw title MPAS APCP+36 12Z02JAN2021'
'draw title MPAS APCP+03 03Z01JAN2021'
...

Sobre ser genérico o script, sim. Por exemplo, nos scripts operacionais/pesquisa se pode mudar o horizonte de previsão, tipo de dado, resolução, etc e adicionar o pos. Por exemplo, meu script:

./run_mpas_gnu.egeon GFS 2021010100 240 15km

Abraço,

Pablo

On Fri, Aug 25, 2023 at 8:22 AM Denis Magalhães de Almeida Eiras <denis.eiras@inpe.br> wrote:

    Olá Pablo, bom dia!

    Obrigado pelo suporte!

    Faz sentido adaptar o prec.gs para 3h, por exemplo ?

    Penso também que nós podemos adaptar os scripts para uma configuração genérica de tempo de rodada, isto é, modificá-los previamente dentro do run_mpas_egeon.sh por exemplo. Isto faria sentido para termos scripts que podem ser genéricos para diferentes use cases. O que acha?

    Abs,
    Denis

    Em 25/08/2023 07:59, Julio Pablo Reyes Fernandez escreveu:
>
>     Prezado Eduardo,
>
>     No draft do ano passado faltaram alguns detalhes. O script ngrid2latlon.sh foi criado pensando numa rodada mais longa (3-4 dias), os 2 primeiros passos não deve ter problema para criar os dados *.nc, o 3ro não faz porque a integração foi ate 3 horas e as saídas history*.nc são a cada 3 horas (nesse demo). O prec.gs não gera corretamente a figura porque deveria ter um surface.nc de ate 36 horas. Se modificar no prec.gs as seguintes valores deve conseguir uma figura ou também, integrar ate 36 h modificando no namelist.atmosphere :
>
>     config_run_duration = '0_03:00:00'    para    config_run_duration = '3_00:00:00'         (3 dias)
>
>     Para o 3ro exemplo do script ngrid2latlon.sh mudar no streams.atmosphere (para saídas horarias do history):
>
>     ....
>     <stream name="output"
>             type="output"
>             filename_template="history.$Y-$M-$D_$h.$m.$s.nc"
>             output_interval="1:00:00" >                                  <====
>     ... 
>
>     Por outro lado, os dados completos do ERA5 para o período 6/2021 a 5/2022 estão em:
>
>     /mnt/beegfs/julio.fernandez/ERA4IC
>
>     Abraço,
>     Pablo
>
