### ISSUE TITLE
[GCC] PAD: Criar, executar e validar os scripts de PRÉ-PROCESSAMENTO

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#309]
### User Story

COMO Saulo,
QUEREMOS Criar, executar e validar os scripts de pré-processamento,
PARA Criar o ambiente padronização de desenvolvimento.

### :clipboard: Critérios de aceite de conclusão da Issue

- Criar script com base do GAM;  (Sprint 45 - OK)
- Usar dados da área nova; (Sprint 45 - OK)
- Dados de pré-processamento gerados e validados na versão do MPAS 8.0.1 com grade uniforme de 24km.
- Ambiente da EGEON
- O script deve solicitar a URL para o fork do desenvolvedor (Sprint 46).

### Detalhamento adicional da atividade

- Dados do pré com base na grade 24km.
- #275 

### Impactos

N/A

### Dependências

- #304 

### Solução

A tarefa abordou os scripts:
1. Instalação (adicionalmente)
2. Pré-processamento

Os  arquivos foram criados:
- README - instruções
- 1.install_spack.bash
- 2.install_wps.bash
- 3.install_mpas.bash
- 4.pre_mpas.bash

A solução consiste em executar os scripts na sequência do repositório:
 - https://github.com/monanadmin/MONAN-scripts.git

Até esse momento, decidiu-se que os scripts acima versionados no github baixam o testcase MPAS_testcase.v1.0.tgz e dados MPAS_data_v1.0_ADDED_ERA5_INVARIANT.tgz disponíveis em /mnt/beegfs/monan/dados/MPAS_v8.0.1/ e sobrescrevem os scripts que estão disponibilizados no testcase. 

Os logs foram verificados em :
- /mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/testcase/runs/ERA5/static/logs
- /mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/testcase/runs/ERA5/2021010100/logs

sem problemas identificados

Os arquivos foram gerados:
- /mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/testcase/runs/ERA5/static/x1.1024002.static.nc
- /mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/testcase/runs/ERA5/2021010100/x1.1024002.init.nc

Alguns arquivos como ungrib, convermpas, executáveis do mpas foram removidos do testcase, pois devem ser são usados os gerados

### Problemas encontrados

N/A

### Conclusão

Os scripts foram testados e foram disponibilizados no github, executados desde o primeiro (1) ao último script (4). 
Melhoria a fazer:
- poder executar novamente o test case sem precisar fazer tudo do zero. Talvez solicitar ao usuário quais passos fazer, por exemplo.

**IMPORTANTE**
Scripts já versionados em https://github.com/monanadmin/MONAN-scripts.git , sobrescrevem os scripts do testcase automaticamente na execução.

**Comment by deniseiras** [comment]
Abaixo, os passos iniciais da tarefa sem considerar os passos da #304, foram movidos da solução para cá.

---

Os passos abaixo precisam ser melhor detalhados e escritos:

- Foram usados os executáveis da compilação da tarefa #275 (
Seguindo manual do tutorial disponível em:
https://mpas-dev.github.io/atmosphere/atmosphere_download.html
https://www2.mmm.ucar.edu/projects/mpas/tutorial/Boulder2019/index.html
(que também foi documentado na tarefa #275)

- Seguindo o tutorial os seguintes arquivos foram baixados para resolução de 24Km (slide 4):
https://www2.mmm.ucar.edu/projects/mpas/atmosphere_meshes/x1.1024002.tar.gz
https://www2.mmm.ucar.edu/projects/mpas/atmosphere_meshes/x1.1024002_static.tar.gz


- foram extraídos os arquivos conforme manual do Pablo mas obteve-se um erro ao extrair o tar.
- Então, pablo disponibilizou os dados em /pesq/share/wrf/dist/EGEON/MPAS/data   
~~~
/mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS :-) cp -fr /pesq/share/wrf/dist/EGEON/MPAS/data .
~~~

Em seguida foi compilado o init_atmosphere
- Executa-se o static.sh, que gera os arquivos na pasta testcase/RUNS/ERA5/static , que gerou o make_static.sh. Este precisou ser alterado para contemplar o mpas compilado com gnu na tarefa #275. Foi alterado o script para fazer o export do netcdf e PIO como abaixo:

**TODO - corrigir static.sh**

make_static.sh
~~~
#!/bin/bash
#SBATCH --job-name=static
#SBATCH --nodes=1              # Specify number of nodes
#SBATCH --partition=batch
#SBATCH --tasks-per-node=1     # Specify number of (MPI) tasks on each node
####SBATCH --ntasks=2048
#SBATCH --time=02:00:00        # Set a limit on the total run time
#SBATCH --output=/mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS/testcase/runs/ERA5/static/logs/my_job.o%j    # File name for standard output
#SBATCH --error=/mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS/testcase/runs/ERA5/static/logs/my_job.e%j     # File name for standard error output

# Bind your OpenMP threads
export OMP_NUM_THREADS=1
ulimit -s unlimited
ulimit -c unlimited
##ulimit -m unlimited
ulimit -v unlimited

#export OMPI_MCA_btl_openib_allow_ib=1
#export OMPI_MCA_btl_openib_if_include="mlx5_0:1"
export PMIX_MCA_gds=hash
export LC_ALL="en_US.UTF-8"
YOUR_INSTALL_ROOT=/mnt/beegfs/denis.eiras/monan_github_issues_workspace/275/mpas_libs/install
export NETCDF=${YOUR_INSTALL_ROOT}/netcdf
export PNETCDF=${YOUR_INSTALL_ROOT}/PnetCDF
export PIO=


#. /mnt/beegfs/carlos.souza/spack_mpas_intel/env_mpasv8.sh

# Carregar os pacotes necessários para o MPAS@GNU:
#spack load --only dependencies mpas-model%gcc@9.4.0
#spack load --list

cd /mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS/testcase/runs/ERA5/static

#ldd ./init_atmosphere_model

#export MPI_TYPE_DEPTH 16

echo  "STARTING AT `date` "
Start=`date +%s.%N`
echo $Start > /mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS/testcase/runs/ERA5/static/Timing

date
mpirun -np 1 ./init_atmosphere_model
#wait

End=`date +%s.%N`
echo  "FINISHED AT `date` "
echo $End   >> /mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS/testcase/runs/ERA5/static/Timing
echo $Start $End | awk '{print $2 - $1" sec"}' >> /mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS/testcase/runs/ERA5/static/Timing

grep "Finished running" log.init_atmosphere.0000.out >& /dev/null

if [ $? -ne 0 ]; then
   echo "  BUMMER: Static generation failed for some yet unknown reason."
   echo " "
   tail -10 /mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS/testcase/runs/ERA5/static/log.init_atmosphere.0000.out
   echo " "
   exit 21
fi
   echo "  ####################################"
   echo "  ### Static completed - $(date) ####"
   echo "  ####################################"
   echo " "
#
# clean up and remove links
#

mv log.init_atmosphere.0000.out /mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS/testcase/runs/ERA5/static/logs
mv Timing  /mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS/testcase/runs/ERA5/static/logs

find /mnt/beegfs/carlos.souza/pre_mpas/manual_gam/MPAS/testcase/runs/ERA5/static -maxdepth 1 -type l -exec rm -f {} \;

date
exit 0

~~~

copiar os arquivos abaixo, dentro src/core_atmosphere/physics/physics_wrf/files, para a pasta de execução testcase/runs/ERA5/2021011000

VEGPARM.TBL
SOILPARM.TBL
LANDUSE.TBL

- Executou-se o modelo
  - um erro de memória inválida ocorreu. Acredita-se um possível diferença de namelists
  - **Verificou-se que foi compilado com kprof. Remover as opções -g e -g tanto do FFLAGS como do LDFLAGS. e tentar novamente**

**Comment by deniseiras** [comment]
**LOGS DA EXECUÇÃO**
Usando scripts github até o final do dia 12/09/23

Em /mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/testcase/runs/ERA5/static/logs

~~~
[denis.eiras@headnode logs]$ tail log.init_atmosphere.0000.out
  2  initialize                                        230.76208         1      230.76208      230.76208      230.76208     8.09       8.09       1.00
 
 -----------------------------------------
 Total log messages printed:
    Output messages =                 8582
    Warning messages =                  12
    Error messages =                     0
    Critical error messages =            0
 -----------------------------------------
 Logging complete.  Closing file at 2023/09/12 18:22:47
[denis.eiras@headnode logs]$ more my_job.e276313 
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
[denis.eiras@headnode logs]$ more my_job.o276313 
STARTING AT Tue Sep 12 17:35:13 -03 2023 
Tue Sep 12 17:35:13 -03 2023
FINISHED AT Tue Sep 12 18:22:49 -03 2023 
  ####################################
  ### Static completed - Tue Sep 12 18:22:49 -03 2023 ####
  ####################################
 
Tue Sep 12 18:22:49 -03 2023

~~~

Arquivo static gerado em 
/mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/testcase/runs/ERA5/static/x1.1024002.static.nc

Em /mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/testcase/runs/ERA5/2021010100/logs:

~~~
[denis.eiras@headnode logs]$ more my_job_ic.e276317
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
Abort(1734831948) on node 17 (rank 17 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1734831948) - process 17
Abort(1734831948) on node 3 (rank 3 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1734831948) - process 3
Abort(1734831948) on node 19 (rank 19 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1734831948) - process 19
Abort(1734831948) on node 2 (rank 2 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1734831948) - process 2
Abort(1734831948) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1734831948) - process 1
Abort(1734831948) on node 20 (rank 20 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1734831948) - process 20
Abort(1734831948) on node 9 (rank 9 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1734831948) - process 9
Abort(1734831948) on node 24 (rank 24 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1734831948) - process 24
mv: cannot move 'log.init_atmosphere.0000.out' to '/mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/testcase/runs/ERA5/2021010100/logs/log.init_atmosphere.0000.out': Device or resource busy
mv: cannot move 'streams.init_atmosphere' to '/mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/testcase/runs/ERA5/2021010100/scripts/streams.init_atmosphere': Device or resource busy
[denis.eiras@headnode logs]$ more my_job_ic.o276317
STARTING AT Tue Sep 12 18:24:06 -03 2023 
FINISHED AT Tue Sep 12 18:24:21 -03 2023 
Tue Sep 12 18:24:21 -03 2023
[denis.eiras@headnode logs]$ more my_job_ungrib.e276316
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/var/spool/slurm/d/job276316/slurm_script: line 22: /mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/spack_wps/env_wps.sh: No such file or directory
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
mpirun: error while loading shared libraries: libhwloc.so.15: cannot open shared object file: No such file or directory
mv: cannot stat 'ungrib.log': No such file or directory
mpirun: error while loading shared libraries: libhwloc.so.15: cannot open shared object file: No such file or directory
mv: cannot stat 'ungrib.log': No such file or directory
mpirun: error while loading shared libraries: libhwloc.so.15: cannot open shared object file: No such file or directory
cat: 'FILE:2021-01-01_00': No such file or directory
cat: 'LSM:1979-01-01_00': No such file or directory
cat: 'GEO:1979-01-01_00': No such file or directory
tail: cannot open '/mnt/beegfs/denis.eiras/MONAN-scripts/egeon/MPAS/testcase/runs/ERA5/2021010100/logs/ungrib.log' for reading: No such file or directory
[denis.eiras@headnode logs]$ tail my_job_ungrib.o276316
	libgcc_s.so.1 => /opt/ohpc/pub/compiler/gcc/9.4.0/lib64/libgcc_s.so.1 (0x000014f2d15d7000)
	libquadmath.so.0 => /opt/ohpc/pub/compiler/gcc/9.4.0/lib64/libquadmath.so.0 (0x000014f2d1390000)
	libc.so.6 => /lib64/libc.so.6 (0x000014f2d0fcb000)
	libjpeg.so.62 => /mnt/beegfs/denis.eiras/MONAN-scripts/egeon/spack_wps/opt/spack/linux-rhel8-zen2/gcc-9.4.0/libjpeg-turbo-2.1.3-a7r7uf4lkzdafbtocihflfmlwaeyye4w/lib64/libjpeg.so.62 (0x000014f2d0d24000)
	/lib64/ld-linux-x86-64.so.2 (0x000014f2d26af000)
2021-01-01_00
FINISHED AT Tue Sep 12 18:23:35 -03 2023 
  BUMMER: Ungrib generation failed for some yet unknown reason.
~~~

Arquivo x1.1024002.init.nc não gerado
