### ISSUE TITLE
Escalabilidade - Rattler - MPAS - GPU

### ISSUE THREAD

**Issue by luflarois** [monanadmin/monan#31]
# Descrição

Rodar modelo MPAS de 2 a 7 nós (step 1) com resolução de 15km (usar a tarefa de execução anterior) com previsão de 12 horas e gráfico extrapolando para 24 horas. Tempo da dinâmica.

Estimativa:  6h

# Impactos

Não há impactos.

# Dependências

- [x] #45 
- [x] #53 

...

# Solução

- Rodar o MPAS com CPU e GPU, variando-se o número de nós de **2 a 7**, pois com 1 nó não há memória suficiente em GPU para o benchmark de 15km.
- Em cada nó há 4 GPUs NVIDIA A100
- Na época em que foram obtidos os resultados, cada nó da fila xe8545 continha 2 processadores AMD EPYC 7543 32-Core, totalizando 64 núcleos/nó. Atualmente, cada nó contém 2 processadores AMD EPYC 7713 64-Core, ou seja, 128 núcleos/nó. As instruções consideram a configuração de CPU anterior dos nós da fila xe8545 (64 núcleos/nó).
- Preparação da rodada com 2 nós: total de 128 processos MPI, sendo 120 em CPU e 8 em GPU
```bash
$ module load hpc
$ metis/gcc93/5.1.0
$ gpmetis -minconn -contig -niter=200 x1.2621442.graph.info 8
$ gpmetis -minconn -contig -niter=200 x1.2621442.graph.info 120
```
-  A execução paralela será com o _script_ já descrito na issue #53 
```bash
$ sbatch -N2 -n128 submit_atmosphere_rattler_xe8545.sh 4 60 4
```
onde o terceiro parâmetro do script é o número de núcleos alocados por cache L3 da arquitetura por nó. 
Como há 16 caches L3 em cada nó, chega-se ao total de 64 núcleos alocados (1 por processo MPI).
- Para a preparação das demais rodadas (3 a 7 nós), adota-se procedimento similar. Por exemplo, para 7 nós:
```bash
$ gpmetis -minconn -contig -niter=200 x1.2621442.graph.info 28 (para GPU)
$ gpmetis -minconn -contig -niter=200 x1.2621442.graph.info 420 (para CPU)
$ sbatch -N7 -n448 submit_atmosphere_rattler_xe8545.sh 4 60 4
```

- Os tempos, _speed-ups_ e eficiências alcançados estão na tabela a seguir:

**_15km @RATTLER%NVIDIA_**

<google-sheets-html-origin><style type="text/css"></style>

#nós | #cores | tempo(s) | su_ideal | su_obtido | ef (%)
-- | -- | -- | -- | -- | --
2 | 128 | 746 | 1,00 | 1,00 | 100,00
3 | 192 | 506 | 1,50 | 1,47 | 98,24
4 | 256 | 386 | 2,00 | 1,94 | 96,77
5 | 320 | 314 | 2,50 | 2,38 | 95,18
6 | 384 | 266 | 3,00 | 2,80 | 93,35
7 | 448 | 230 | 3,50 | 3,25 | 92,73

...

# Problemas encontrados
- Com 1 nó não há memória suficiente em GPU para o benchmark de 15km.

**Comment by monanadmin** [comment]
- Verificar resoluções compatíveis entre MPAS e FV3 para usar nos testes. 

> Resoluções próximas são aceitas, por exemplo: 13km para MPAS e 15km FV3

- Escolhidas as resoluções iniciar os testes de performance. Esses testes podem ser associados diretamente a escalabilidade. Por exemplo, rodar com 1,2,4,8 ... e com as GPUS disponíveis e guardar:
1. O tempo de janela da rodada para cada número de núcleos
2. A curva de escalabilidade com o ganho em cada número de cores
3. Os valores de eficiência para cada ponto da curva.

## Escalabilidade:

Tempo de execução com 1 processador: $T_1$
Tempo de execução com P processadores: $T_P$
Speedup Paralelo com P processadores: 
$S_p={{T_1} \over {T_p}}$
**Situação ideal**: 
$T_P = {{T_1} \over {P}}$, então
$S_P = P$

## Eficiência:

$E_P = {{S_P} \over  {P}}$
**Situação ideal**: 
$S_P = P$
$E_P = 1.0$
