### ISSUE TITLE
[GCC] PAD: Criar, executar e validar os scripts de PÓS-PROCESSAMENTO

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#310]
### User Story

COMO Saulo,
QUEREMOS Criar, executar e validar os scripts de pós-processamento,
PARA Criar o ambiente padronização de desenvolvimento.

### :clipboard: Critérios de aceite de conclusão da Issue

- Criar script com base do GAM (as 5 variáveis do manual); 
- Usar dados da área nova; 
- Dados de pós-processamento gerados e validados na versão do MPAS 8.0.1 com grade uniforme de 24km.
- Experimento fixo de 24 horas ERA5.
- Gerar uma imagem da saída.

### Detalhamento adicional da atividade

N.A.

### Impactos

N.A.

### Dependências

- #311 
- versionamento dos scripts ngrid2latlon.sh e prec.gs

### Solução

- Criado script 6.pos_monan.bah e versionado em https://github.com/monanadmin/MONAN-scripts/egeon que compila o executável convert_mpas, pós processa as saídas do modelo e gera uma figura com a precipitação de 24 horas de previsão através do scripr prec.gs versionado em https://github.com/monanadmin/MONAN-scripts/egeon/MPAS_ori/testcase/scripts.

- Variáveis processadas descritas nos arquivos:

_include_fields.diag_:
````
vorticity_250hPa
vorticity_850hPa
precipw
rainnc
rainc
mslp
t2m
u10
v10
````

_include_fields.history_:
```
u10
v10
precipw
t2m
rainnc
rainc
```

- Figura gerada (rainc+rainnc): 

![Image](https://github.com/monanadmin/monan/assets/98923325/9d69fa91-79f9-4549-b160-1ac04cddf05b)

### Problemas encontrados

N.A.

### Conclusão

- Script criado que gera figura para 24 horas de previsão;
- Utiliza estrutura de dados criada por outro script que utiliza dados da área nova;
- Scripts de dependência ajustados e versionados;
- Variáveis utilizadas detalhadas.

**Comment by egkhamis** [comment]
Atual metodologia de interpolação: "Integer fields are remapped to the target grid using a nearest-neighbor scheme. For all real-valued (single- or double-precision) fields, the 'convert_mpas' program employs a barycentric interpolation, the output of which is C0 continuous. Cell-based fields in the MPAS mesh are sampled from the three cell centers that form the vertices of the Delaunay triangle containing the target point. Vertex- and edge-based fields are sampled from the corners or faces, respectively, of the Voronoi cell containing the target point."
