### ISSUE TITLE
[GCC] PAD: Apresentar o ambiente de dev padrão no Workshop da DMINT

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#318]
### User Story

COMO Saulo,
QUEREMOS Realizar a apresentação do ambiente de desenvolvimento padrão do MONAN,
PARA que os pesquisadores e desenvolvedores da DIMNT possam iniciar seus trabalhos e também para atender ao Key-Result (Meta) 4 do OKR-GCC-1.

### :clipboard: Critérios de aceite de conclusão da Issue

- Apresentação do tipo "Hands-on", execução na "prática";
- Explicação das áreas de dados de uso comum do MONAN;
- Pensar na apresentação também no contexto da comunidade externa;
- A apresentação deverá ter logo do MONAN e INPE.

### Detalhamento adicional da atividade

![Image](https://github.com/monanadmin/monan/assets/41485190/eb524907-993d-4a91-a54f-b3f42ba37a3d)

- Doc QuickStart: https://docs.google.com/document/d/1Rg7gQGeaDsMHC8ocdubdH--u54ca1Xu8VwTPFyKnl1M/edit?usp=sharing

### Impactos

_(... consequência técnica encontrada durante a execução da issue)_

### Dependências

_(... issues e requisitos que devem ser executados previamente)_

### Solução

- Link da apresentação: https://docs.google.com/presentation/d/1bBiPXDX4Go8VS_5mIs57d9kkJaMxydOT/edit?rtpof=true

### Problemas encontrados

-.

### :white_check_mark: Conclusão

- [João] Apresentação feita com sucesso.
- [João] Melhorias nos scripts serão realizados na Sprint seguinte.

**Comment by carlosrenatosouza2** [comment]
- PDF disponivel
- mencionar que o usuario precisa ter feito um fork antes
- criar a TAG no repo MONAN-Model

**Comment by joaomas** [comment]
Tag criada na issue #327
