### ISSUE TITLE
[GCC] PAD: Melhoria dos scripts do ambiente de desenvolvimento padrão

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#319]
### User Story

COMO Saulo,
QUEREMOS aperfeiçoar os scripts de pré-processamento, execução e pós-processamento do ambiente de dev padrão, 
PARA entregar o melhor ambiente possível de desenvolvimento.

### :clipboard: Critérios de aceite de conclusão da Issue

- Acrescentar a funcionalidade de atender ao URL do git-fork externo do usuário; 
- Correções dos erros estruturais com base no feedback dos testes de validação da issue #315 

### Detalhamento adicional da atividade

N/A

### Impactos

N/A

### Dependências

- #309
- #310
- #311 
- #313

### Solução

Foram corrigidos:
- mpas_exe.sh : estava executando mpirun ./  sem o executável
- verificação de erro na rodada do MPAS (script 5): se der erro, não move ou apagar arquivos
- reforços nos avisos sobre comandos que devem ser executados ao final de algum passo
- alterado pós para executar 24h ao invés de 3 dias.

commits: 
~~~
commit 0a05e6a20bd81755bb0dbc96e7658b72460f0346 (HEAD -> main, origin/main, origin/HEAD)
Author: Denis Eiras <denis.eiras@gmail.com>
Date:   Mon Sep 25 09:36:42 2023 -0300

    bar no prec.gs

commit 2b6ca6d983245ab064af431fff522dba47f5cffe
Author: Denis Eiras <denis.eiras@gmail.com>
Date:   Mon Sep 25 09:17:54 2023 -0300

    pos 24h ok

commit 47ced064e9f31c5ecd72e860938873fc301270d2
Author: Denis Eiras <denis.eiras@gmail.com>
Date:   Fri Sep 22 14:51:49 2023 -0300

    fix check mpas run ok: tests diag.2021-01-02_00.00.00.nc

commit ea56c55092766f5282fdbfe03de7aba1b85e866b
Author: Denis Eiras <denis.eiras@gmail.com>
Date:   Fri Sep 22 14:44:17 2023 -0300

    do not move or delete file on MPAS error

commit a4bdaad8688c8828e6568fb2489415217f8dc0ba
Author: Denis Eiras <denis.eiras@gmail.com>
Date:   Fri Sep 22 14:34:30 2023 -0300

    fix mpirun executing ./ instead of ./atmosphere_model

commit d60bc55e9b44488ea27e754883478b56e0a08182
Author: Denis Eiras <denis.eiras@gmail.com>
Date:   Fri Sep 22 12:32:02 2023 -0300

    improve attention on message spack not loaded

commit a0c0ff2de46667610fbd3278598774428a2c170f
Author: Denis Eiras <denis.eiras@gmail.com>
Date:   Fri Sep 22 12:29:26 2023 -0300

    compilatio ok message
~~~

Figura final gerada:
![image](https://github.com/monanadmin/monan/assets/6113640/eed2a364-a437-4b7b-a369-9a248969d97e)

### Problemas encontrados

Descritos na solução

### :white_check_mark: Conclusão

Foram feitas correções nos scripts. Aguardando validação na #315 para encerramento.

**Comment by joaomas** [comment]
Apresentação do Git Fork - https://docs.google.com/presentation/d/16hyQ5RbuTVr86qu1FwiEbeTT2uNdjAC5FjscR0azGRE/edit#slide=id.g1e614f8462c_2_11

**Comment by ebiduardo** [comment]
colegas,
sobre melhoria de scripts, tenho a dizer:
estou  convicto que usar funcoes ajuda muito na compreenção e manipulação.
as funções não precisam ter muitas linhas. 
a escolha de um bom nome é o que faz um grande diferencial.
o que facilita dar um nome é ser uma tarefa especifica.

outro ponto é o main, ou driver , cliente das funcoes dá uma clareza 
  no funcionamento da tarefa global.

**Comment by deniseiras** [comment]
Boa dica Bidu, vamos considerar nas proximas fases !

*Denis Eiras*





Em ter., 26 de set. de 2023 às 10:26, eduardo lucio mendes garcia <
***@***.***> escreveu:

**Comment by deniseiras** [comment]
é bash mesmo. Ele faz a submissão dentro desse bash

*Denis Eiras*





Em ter., 26 de set. de 2023 às 15:54, Denis Eiras ***@***.***>
escreveu:
