### ISSUE TITLE
[GCC] PAD: Correção Scripts Ambiente Dev. Egeon - Parte 2

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#324]
### User Story

COMO Saulo,
QUEREMOS corrigir os scripts do ambiente de desenvolvimento do MONAN na Egeon após a apresentação no Workshop,
PARA entregar um ambiente com melhor organização e eficiência para o inicio dos trabalhos com o MONAN.

### :clipboard: Critérios de aceite de conclusão da Issue

- [x] MOD 1: Alterar o script do "init_atm" (static) para rodar em paralelo (testar escalabilidade em um nó com 16..128 cores]. 

### Detalhamento adicional da atividade

NA

### Impactos

NA

### Dependências

NA

### MOD 1:

- Estudo simplificado de escalabilidade do init_atmosphere_model para gerar o arquivo `x1.1024002.static.nc`. Os seguintes tempos aproximados foram obtidos:

| cores  |   tempo  |
| ------ | -------- |
|     1      | 45m20s |
|    16     | 10m44s |
|    32    | 9m         |
|    64    | 7m47s   |
|  128    | 10m        |

- Alterado o script `static.sh` para permitir processamento paralelo. Para isso, foi alterado o carregamento dos módulos pelo script `load_monan_app_modules.sh` e alterada a criação de `make_static.sh` de modo a utilizar 32 processadores de um único nó. Também foi incluída a criação de um link simbólico para o arquivo `ln -sf ${NMLDIR}/x1.${RES}.graph.info.part.${cores} ` para futura mudança do número de cores.

### Problemas encontrados

NA

### :white_check_mark: Conclusão

Testes de escalabilidade feitos e alteração da geração do arquivo `x1.1024002.static.nc` utilizando processamento paralelo.

**Comment by deniseiras** [comment]
- [ ] Verificar se os arquivos foram gerados com sucesso ou não. 
  movido para #323

**Comment by egkhamis** [comment]
- [] Remover comentários. 
- [] Trocar MPAS por MONAN.
movidos para #323
