### ISSUE TITLE
[GCC] PAD: Criar Branch Develop MONAN-Scripts

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#326]
### User Story

COMO Saulo,
QUEREMOS criar uma branch develop, seguindo o workflow da DTN06 no repositório MONAN-Scripts,
PARA melhorar a qualidade e organização do repositórios colocando-o no padrão estabelecido de desenvolvimento.

### :clipboard: Critérios de aceite de conclusão da Issue

- [x] Branch 'develop' criada seguindo a DTN06.

### Detalhamento adicional da atividade

- Link da DTN06: https://docs.google.com/document/d/1IG3lIBkdtQKAISxFl8NGW-Hfh8De9HNeq_Pm5qHq_s0/edit

### Impactos

_(... consequência técnica encontrada durante a execução da issue)_

### Dependências

_(... issues e requisitos que devem ser executados previamente)_

# Solução

Seguindo a DTN06, página 14, resumindo:

- Caso 2: O repositório remoto não tem a branch develop criada:
- a branch main deverá iniciar a branch develop:
~~~
git pull (ou git clone) // para garantir o último estado do repositório remoto
git flow init
git checkout develop // entra na branch develop -- apos git flow init
git merge main // atualiza a develop à partir da main
git push // envia a develop atualizada com o main para o repositório remoto

git flow feature start monan-scripts-323-QI
~~~

# Problemas encontrados

[CR]: Não consegui fazer funcionar o comando `git feature start monanscripts-323-QI`. Usei o comando `git checkout -b monanscripts-323-QI`. Enquanto a develop for igual a main, esse atalho funciona, mas o correto seria usar o git flow. 

[CR]: SOLUÇÃO ==> Para o comando `git feature start monanscripts-323-QI` da DTN06 funcionar precisa ser feito dessa forma: `git flow feature start monan-scripts-323-QI`

### :white_check_mark: Conclusão

Git flow usado com sucesso, branchs criadas e prontas para serem usadas em diferentes features. Atualização/correção do manual DTN06 foi feita em forma de sugestão, precisa ser corrigido.

**Comment by carlosrenatosouza2** [comment]
Quando finalizar uma MOD na feature e atualizar o develop:
~~~
git add .
git commit -m "..."
git push
git checkout develop
git merge feature/monanscripts-323-QI
git push
