### ISSUE TITLE
[GCC] Disponibilizar os documentos do Manual corrigido

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#329]
### User Story

COMO Saulo, 
QUEREMOS Disponibilizar os documentos do Manual corrigido,
PARA entregar aos colegas da DIMNT, aos alunos da PGMET e a todos os usuários da Egeon envolvidos no projeto MONAN para inicio dos trabalhos.

### :clipboard: Critérios de aceite de conclusão da Issue

- [x] Disponibilizar os documentos em local centralizado.

### Detalhamento adicional da atividade

-.

### Impactos

-.

### Dependências

- #328 

### Solução

- Página https://github.com/monanadmin/monanadmin.github.io/blob/main/index.md atualizado.

### Problemas encontrados

-.

### :white_check_mark: Conclusão

- Página atualizada.

**Comment by joaomas** [comment]
Página criada para divulgação do workshop, aguardando aprovação do Saulo.

**Comment by joaomas** [comment]
Usar o Quick Start: https://drive.google.com/drive/u/3/folders/1unL63ROHPp3klBwXyuQqopHtHqyF3vE6

**Comment by deniseiras** [comment]
https://github.com/monanadmin/MONAN-scripts/blob/0.2.1/egeon/MONAN_v.0.2.1_QuickStart.pdf

*Denis Eiras*





Em qua., 18 de out. de 2023 às 06:17, João Messias ***@***.***>
escreveu:
