### ISSUE TITLE
[GCC] PAD: MOD 2: Remoção de arquivos temporários MONAN-Scripts

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#340]
### User Story

COMO Saulo,
QUEREMOS corrigir os scripts do ambiente de desenvolvimento do MONAN na Egeon após a apresentação no Workshop,
PARA entregar um ambiente com melhor organização e eficiência para o inicio dos trabalhos com o MONAN.

### :clipboard: Critérios de aceite de conclusão da Issue

- [x] MONAN-Scripts atualizado com esta nova feature de permitir que o usário execute o modelo (fase 3 e 4) mais de uma vez.
- [x] Realizar o merge para disponibilizar a nova versão dos scripts a equipe de testes para validação da feature.

### Detalhamento adicional da atividade

NA

### Impactos

Foi facilitada a execução do modelo e pós processamento mais de uma vez.

### Dependências

NA

### Solução

- Gerada a branch *monanscripts-340-QI* e foi feito o merge dessa branch com a *develop* usando o padrão do git flow e DTN06.
- Parte do script *4.pos_monan.bash* foi incorporado no script *run_monan_gnu_egeon.bash* de modo a reorganizar o pós processamento e aproveitar os caminhos exportados pelos demais scripts e passos. Além disso, arquivos de entrada/saída foram copiados ou movidos para permitir esse processo.

### Problemas encontrados

Ao remover os links simbólicos após a execução do pós processamento, o passo 2 deve ser executado novamente para recriar estrutura de diretórios e scripts de rodadas. Para evitar isso, antes de executar o passo 4, comentar no script *PostAtmos_exe.sh* as linhas correspondentes abaixo (o caminho ${EXPDIR} estará diferente para cada usuário):

```
mv ${EXPDIR}/namelist.atmosphere ${EXPDIR}/scripts
mv ${EXPDIR}/monan_exe.sh ${EXPDIR}/scripts
mv ${EXPDIR}/stream* ${EXPDIR}/scripts
find ${EXPDIR} -maxdepth 1 -type l -exec rm -f {} \;
```  
Outra possibilidade seria incluir uma _flag_ no passo 4 oferecendo a possibilidade de apagar ou não todos os scripts e links simbólicos utilizados pelo modelo. Ou seja, incluir um _if_ nessas linhas acima e uma leitura de _flag_ no script *4.pos_monan.bash*. Pode-se deixar como padrão uma ou outra escolha, assim nenhuma _flag_ seria necessária.

### :white_check_mark: Conclusão

- Scripts modificados permitem a execução dos passos 3 e 4 mais de uma vez. Há dúvidas quanto à necessidade de limpar saídas e scripts do pós processamento, entretanto é simples de implementar essa funcionalidade.
- O modelo pode ser executado quantas vezes se queira antes de executar o pós processamento.
- A utilização do novo script gerado *PostAtmos_exe.sh* permite ao usuário/desenvolvedor realizar experimentos com o pós-processamento comentando algumas linhas desse script sem realizar o modelo (passo 3) novamente.
- No momento, a branch criada ainda não foi fechada.

### :spiral_calendar: Trabalhos Futuros

_(... caso a issue demande trabalhos futuros detalhar aqui e marcar o campo "Future Work" ao lado para "Sim")_

- [João] Criar tag da nova versão.
- [João] Atualizar manual indicando a nova tag, conforme apontado no comentário abaixo e na issue #352

**Comment by egkhamis** [comment]
Checar se o manual de _quick start_ deve ser alterado devido as mudanças aqui presentes.

**Comment by joaomas** [comment]
A equipe GRC deverá executar um novo teste para validar.

**Comment by egkhamis** [comment]
Será importante começarmos a pensar num ambiente pré-operacional na utilização desses testes e scripts, e até mesmo começarmos a utilizar o ecflow.

**Comment by joaomas** [comment]
@egkhamis e @deniseiras no manual cita para dar o comando "git checkout 0.2.1" esta nova feature acredito que não foi "tageado" ainda, conferem? Vou ignorar este comando do manual para seguir.

`commit f189b8d11e84d2b4133af3c0fb846a8c85621ffa (HEAD -> main, origin/main, origin/HEAD)
Merge: 3216ce8 250cb41
Author: Eduardo Khamis <98923325+egkhamis@users.noreply.github.com>
Date:   Fri Oct 20 11:21:51 2023 -0300

    Merge pull request #2 from monanadmin/feature/monanscripts-340-QI
    
    Feature/monanscripts 340 qi

**Comment by joaomas** [comment]
**Scripts 3 rodando separadamente novamente não funcionou. Sem submissão de job no slurm e sem alteração dos arquivos de log na área indicada.**

//

joao.messias@headnode:/mnt/beegfs/joao.messias/MONAN-scripts/egeon$ time ./3.run_monan.bash
==> Submitting MONAN and waiting for finish before exit ... 

==> Logs being generated at /mnt/beegfs/joao.messias/MONAN-scripts/egeon/MONAN/testcase/runs/ERA5/2021010100/logs ... 

sbatch /mnt/beegfs/joao.messias/MONAN-scripts/egeon/MONAN/testcase/runs/ERA5/2021010100/monan_exe.sh
sbatch: error: Unable to open file /mnt/beegfs/joao.messias/MONAN-scripts/egeon/MONAN/testcase/runs/ERA5/2021010100/monan_exe.sh
==> Please, check the output log files at /mnt/beegfs/joao.messias/MONAN-scripts/egeon/MONAN/testcase/runs/ERA5/2021010100/logs to be sure that MONAN ended successfully. 

==> Script ./3.run_monan.bash completed. 


real	0m0.067s
user	0m0.003s
sys	0m0.005s

//

joao.messias@headnode:/mnt/beegfs/joao.messias/MONAN-scripts/egeon$ squeue -a
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)

**Comment by joaomas** [comment]
@deniseiras e @egkhamis 

**Script 4** com erro novamente.

joao.messias@headnode:/mnt/beegfs/joao.messias/MONAN-scripts/egeon$ time ./4.pos_monan.bash

==> Executing post processing...

mv: cannot stat '/mnt/beegfs/joao.messias/MONAN-scripts/egeon/MONAN/testcase/runs/ERA5/2021010100/namelist.atmosphere': No such file or directory
mv: cannot stat '/mnt/beegfs/joao.messias/MONAN-scripts/egeon/MONAN/testcase/runs/ERA5/2021010100/monan_exe.sh': No such file or directory
mv: cannot stat '/mnt/beegfs/joao.messias/MONAN-scripts/egeon/MONAN/testcase/runs/ERA5/2021010100/stream*': No such file or directory
==>  Script ./4.pos_monan.bash completed. 

==>  Log file: /mnt/beegfs/joao.messias/MONAN-scripts/egeon/MONAN/testcase/runs/ERA5/2021010100/postprd/logs/pos.out . End of script. 


real	0m39.759s
user	0m18.055s
sys	0m1.877s
