### ISSUE TITLE
[GCC] PAD:  Analisar os resultados das ferramentas de analise [Run 2] - HPCToolkit - i, k [Spike]

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#345]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS analisar os resultados gerados pelas ferramentas de analise,
PARA definir os próximo passos de atuação no código e continuar com a validação do DTN-03 a partir deste "estudo de caso".

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Verificar a perfomance de cada subrotina e gerar um relatório de gargalos.
- ~~Usar HPCToolkit para o laço i, k.~~  (Denis 16/11)
- [x] Usar HPCToolkit para o laço (i,k) e (k,i)  (Denis 16/11)
 
## :pencil: Detalhamento adicional da atividade

O detalhamento abaixo foi sendo inserido com o andamento da atividade:

- [X] - Investigar performance (CPU_TIME)
- [x] - Investigar performance (L1 cache misses) 

**FW**
Para códigos KI e IK:
- Variar i entre 1/5 a 5/5 - investigar performance L1 / CICLOS
- Limitar o tamanho final do vetor ite no gf_teste, a cada execução (1 executável para cada alteração)

- Se sobrar tempo ...    
  - Testar o impacto do uso do inline (gfortran "-lto") na performance do get_data_value do vetor
  - Investigar a perda de performance (cache misses) devido à ordem inversa do loop sobre o vetor vtp_index no código do GF.

## :comet: Impactos

_(... consequência técnica encontrada durante a execução da issue)_

## :link: Dependências

- #344 

## :hammer_and_wrench: Solução

A solução deste agrega a #346 

#### SOLUÇÃO 1. Análise usando somente o tempo gasto (CPU_TIME)

Esta solução baseou-se na execução do hpcrun somente com a flag que gera as medições de CPU_TIME.

O código utilizado na geração das instruções executam o loop principal 100 vezes. Nas próximas soluções (investigações) será usado somente 1 loop, o que faz mais sentido em termos de investigação de métricas PAPI ou PERF.

Iniciando a visualização com hpcviewer:

- Entrou-se na pasta de scripts da branch develop e feito `source env_hpctoolkit_gprof.sh` 
- copiada a pasta /pesq/share/dmdcc/dist/monan/github_issues_files/344/executions_hpctoolkit_ik para a pasta de scripts, apenas para não correr o risco de corromper os dados originais.
- executado hpcviewer executions_hpctoolkit_ik/exec_1/hpctoolkit-gf.x-database/

Usando os dados gerados previamente na tarefa #344, e usando o conhecimento adquirido do HPCViwer de outras tarefas do GF, usou-se a estratégia usar a guia "Bottom-up view" e ordenar por tempo gasto por função (CPU_TIME (sec): SUM(E)) - segunda coluna - de onde se obteve alguns possíveis gargalos (PG).

Ordenando os gargalos dos piores para os menores:

![image](https://github.com/monanadmin/monan/assets/6113640/15f322fe-947e-4d85-a07e-f19acb83e954)

![image](https://github.com/monanadmin/monan/assets/6113640/8d51bc65-7998-454e-830c-d66c336900ab)

PG1) Subrotina get_interp 
- chamada de um loop duplo da cup_env_clev 
- não é grande
- alguns cálculos podem ser pesados. INVESTIGAR MELHOR

PG2) Subrotina cup_env_clev 
- função enorme, chamada de 3 pontos da cup_gf, com muitos loops

PG3) Função satur_spec_hum 
- chamada em um dos loops da cup_env
- consome tempo provavelmente por ser chamada muitas vezes

PG4) Subrotina cup_env 
- chamada de 3 pontos da cup_gf
- muitas inicializações; 2 loops

PG5) Subrotina convpargfdriver 
- função enorme, chamada do teste, com muitos loops

PG6) Subrotina get_cloud_bc 
- função pequena mas chamada de diversos pontos

PG7) Subrotina get_dellas 
- inicialização de muitas variáveis - função grande
- chamada da cup_gf
- a função precisaria ser quebrada para melhor investigação

PG8) Subrotina reset_2d
- gargalo em alocação de recursos?
- chamado somente no loop da cup_gf
- Poderia ser melhorado? Ex, não instanciar novamente, usar variável na gup_gf e apenas resetar os valores ?

PG9) Subrotina get_data_value da mod_vector
- Tempo usado ao obter valor do vetor da instância singleton "instance":
- Obviamente que este é um ponto que consome um tempo razoável, pois é constantemente executado ao fazer a validação 

Um comparativo com a análise da tarefa #346. 
Tempo ik 4.02 e+03
Tempo ki 4.05 e+03

Observa-se que o código ki executa em 0,75% mais tempo de CPU que o ik.

346 - KI

![image](https://github.com/monanadmin/monan/assets/6113640/8d51bc65-7998-454e-830c-d66c336900ab)

OBS: A subrotina reset_2d parece ser a que mais tem sensibilidade na mudança IK - KI.

#### SOLUÇÃO 2. Análise de registradores de cache miss L1

Após reunião com @deniseiras @robertopsouto e @carlosrenatosouza2 , definiu-se uma primeira estratégia:
- Analisar os cache misses de dados do L1 e L3 , que são as disponíveis no PERF da Egeon
- O código utilizado na geração das instruções foi modificado para executar o loop principal 1 vez. 

Não foi possível analisar o L3 através de LLC-LOAD-MISSES , um erro ocorre ao executar o gf.x.Logo, foi analisado somente o L1 cache

<ins>**L1 cache miss**</ins>

**Análise KI**

Total de cache misses KI = 2.82e+09

Usando uma estratégia de fazer a ordenação por "Top-down view" (1a coluna) descendente, a árvore de chamadas foi investigada até onde se encontram códigos finais (coluna SUM(I) e SUM(E) tem mesmos valores) com cache misses.

Abaixo, verifica-se que, descendo a árvore, 8,6% dos cache misses estão relacionados ao loop da linha 2660, onde 4,7% está na linha 2662. Por quê ocorre o cache miss da linha 2662? 
- a) Em reunião com GCC considerou-se a hipótese que o cache armazena as colunas, por ser implementação Fortran. Logo, variando as colunas (i), a cada iteração, o cache armazena toda a coluna (todas os valores de linha da coluna), e ocorre o cache miss na próxima iteração.
- b) Qual o impacto em cache misses devido a ordem inversa do loop na coluna (i)? Isto é, na primeira vez que o loop é acessado na posição i, i, i+1, i+2 ... i+n são armazenados em cache. Na segunda passagem do loop, i-1 é acessado, mas este não está em cache!
- Qual código causa maior impacto entre os casos a e b ?

![image](https://github.com/monanadmin/monan/assets/6113640/e037e648-15d2-4668-8108-9fea4ae76922)

Também verifica-se que 1,9% está na função get_data_value. Dentro desta ramificação, 1% aponta para a linha 165:
 - @luflarois em reunião: Devido à passagem dos dados para a pilha. Ver comentários na Issue.

E a linha 164 corresponde a 0.8% dos cache misses (somente dentro desse loop) , o que sugere uma investigação na maneira como o valor do vetor está sendo resgatado. Isto poderia estar acontecendo devido à ordem inversa do loop na linha 2660 da figura acima? 

![image](https://github.com/monanadmin/monan/assets/6113640/0d5089a2-7371-406d-b712-81270eb1e4cd)

**Análise IK**

Total de cache misses IK = 5.37e+09

Comparando a quantidade de cache misses do caso do loop final da rotina cup_env:
código KI = 2.96e08
código IK = 8.24e06
Isto é, o código KI têm 35x mais cache misses nesse loop. 
![image](https://github.com/monanadmin/monan/assets/6113640/8ae8cfe3-5f0f-4550-bb88-127aff85cc38)

Apesar de termos mais cache misses no total em IK, verifica-se que a mudança para KI afeta consideravelmente esse loop. 

Analisando o código com mais cache misses na estratégia top down para IK, verificamos uma concentração de cache misses em alguns pontos da get_interp:

![image](https://github.com/monanadmin/monan/assets/6113640/89cdd026-95f9-4690-bec7-01dcad70cbf6)

É preciso entender melhor o motivo destes cache misses.

## :rotating_light: Problemas encontrados

_(... problemas técnicos reais apresentados durante a execução das atividades)_

## :white_check_mark: Conclusão

O código IK têm 1,9x mais cache misses no total do que KI.

## :spiral_calendar: Trabalhos Futuros

_(... caso a issue demande trabalhos futuros detalhar aqui e marcar o campo "Future Work" ao lado para "FW Yes")_

**FW**
Para códigos KI e IK:
- Variar i entre 1/5 a 5/5 - investigar performance L1 / CICLOS
- Limitar o tamanho final do vetor ite no gf_teste, a cada execução (1 executável para cada alteração)

- Se sobrar tempo ...    
  - Testar o impacto do uso do inline (gfortran "-lto") na performance do get_data_value do vetor
  - Investigar a perda de performance (cache misses) devido à ordem inversa do loop sobre o vetor vtp_index no código do GF.

**Comment by deniseiras** [comment]
Notas pré-análise:

Como interpretar os dados ?

Analisando o manual http://hpctoolkit.org/manual/HPCToolkit-users-manual.pdf 
A seção 3.1.6 Effective Performance Analysis Techniques mostra duas estratégias de análise, mais detalhadas no cap 4. A estratégia "waste metric" parece ser mais apropriada, detalhada na seção 4.3.

Feita a leitura do grupo das seções 4.1, 4.2 e 4.3, e escolher a melhor estratégia.

Um problema identificado é que os dados de eventos, como PAPI, não foram gerados na execução do hpcrun. Somente foi usada a opção -t "hpcrun -t ../bin/${executable}" que faz: "Generate a call path trace in addition to a call profile.", ou seja, mede apenas os tempos de execução da árvore de chamadas.

É preciso avaliar a estratégia "waste metric" e verificar quais eventos devemos usar com hpcrun -e <nomedoevento>. Para uma lista de eventos: hpcrun --list-events


Obs: não foram gerados dados do gprof (opção -pg) nos executáveis instrumentados para Hpctoolkit, logo essa opção não é necessária: --disable-gprof , mas ela pode ser útil para gerar somente um código que seja útil para ambos, usando o -pg para gprof e hpctoolkit.


Outros pontos possíveis de investigação baseados na documentação do HPCToolkit

1. Análise usando registradores como PAPI
- 4.1 Monitoring High-Latency Penalty Events . 
  - Ex: usando as métricas de cache miss do papi (Renato) para investiga se pode ser problema de cache miss.

2. Análise usando métricas derivadas
- 4.2 Computing Derived Metrics
  - Ex: a cycles/instruction derived metric from measured metrics PAPI_TOT_CYC and PAPI_TOT_INS: PAPI_TOT_CYC/PAPI_TOT_INS

3. Análise usando estratégia "waste metric"
- 4.3 Pinpointing and Quantifying Inefficiencies

**Comment by deniseiras** [comment]
Anotações de Reunião Denis, Renato, Roberto

Carlos Renato Souza11:08 AM
PAPI_L1_TCM  0x80000006  No    No   Level 1 cache misses
PAPI_L2_TCM  0x80000007  No    No   Level 2 cache misses
PAPI_L3_TCM  0x80000008  No    No   Level 3 cache misses
Carlos Renato Souza11:09 AM
PAPI_L1_DCM  0x80000000  No    No   Level 1 data cache misses
PAPI_L1_ICM  0x80000001  No    No   Level 1 instruction cache misses
PAPI_L2_DCM  0x80000002  No    No   Level 2 data cache misses
PAPI_L2_ICM  0x80000003  No    No   Level 2 instruction cache misses
PAPI_L3_DCM  0x80000004  No    No   Level 3 data cache misses
PAPI_L3_ICM  0x80000005  No    No   Level 3 instruction cache misses
PAPI_L1_TCM  0x80000006  No    No   Level 1 cache misses
PAPI_L2_TCM  0x80000007  No    No   Level 2 cache
Roberto Pinto Souto11:55 AM
Computer Architecture: A Quantitative Approach Capa comum – 23 novembro 2017
Edição Inglês  por John L Hennessy (Autor), David A Patterson (Autor)

http://acs.pub.ro/~cpop/SMPA/Computer%20Architecture%20A%20Quantitative%20Approach%20(5th%20edition).pdf

**Comment by deniseiras** [comment]
Anotações estudo Denis:

CACHE MISS
==========

Dados ou instruções não encontradas na cache do processador.

- L1-DCACHE-LOAD-MISSES: Number of L1 data cache load misses.
- L1-ICACHE-LOAD-MISSES: Number of L1 instruction cache load misses.
- LLC-load-misses: Number of last-level cache load misses.


TLB MISS
========

TLB (Data Translation Lookaside Buffer): É responsável por auxiliar na tradução de endereços de memória virtual para endereços de memória física durante o carregamento de dados.

Uma falha de carregamento do dTLB ocorre quando a tradução para um endereço de memória virtual solicitado pelo processador não é encontrada no dTLB, exigindo que o processador busque a tradução na tabela de páginas armazenada na memória principal.

- DTLB-LOAD-MISSES: Number of data TLB load misses.
- ITLB-LOAD-MISSES: Number of instruction TLB load misses.


PAGE FAULT MISS
===============

Falhas de busca por dados na memória RAM

MINOR Page Faults - acesso a uma página que não está na memória, mas está alocada no espaço de endereço do processo.
MAJOR Page Faults - acesso a uma página que não está na memória e deve ser recuperada do disco. Falhas MAJOR são mais caras em termos de desempenho em comparação com falhas MINOR.

- PERF_COUNT_SW_PAGE_FAULTS_MIN
- PERF_COUNT_SW_PAGE_FAULTS_MAJ

**Comment by deniseiras** [comment]
@luflarois :
- Variar o tamanho de i no loop -ik. Ex 1/5 a 5/5
  - Observar L1 cache misses de acordo com perf::TOT_CYCLES

- Verificar o uso de inline - lto - gfrotran (talvez usar o PURE resolva em alguns casos) para o domínio total.

- Verificar o uso do PURE para transformação de rotinas inline . Ex: get_data_value
