### ISSUE TITLE
[GCC] PAD:  Analisar os resultados das ferramentas de analise [Run 2] - HPCToolkit - k, i [Spike]

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#346]
### User Story

COMO Saulo,
QUEREMOS analisar os resultados gerados pelas ferramentas de analise,
PARA definir os próximo passos de atuação no código e continuar com a validação do DTN-03 a partir deste "estudo de caso".

### :clipboard: Critérios de aceite de conclusão da Issue

- ~~Verificar a perfomance de cada subrotina e gerar um relatório de gargalos.~~ (Denis 16/11)
- ~~Usar HPCToolkit para o laço k, i.~~ (Denis 16/11)
- [x] Concluir tarefa #345 (Denis 16/11)
 
### Detalhamento adicional da atividade

Na tarefa #345 

### Impactos

Na tarefa #345 

### Dependências

- #344 

### Solução

Todo detalhamento na tarefa #345 

### Problemas encontrados

Na tarefa #345 

### :white_check_mark: Conclusão

Na tarefa #345 

### :spiral_calendar: Trabalhos Futuros

Na tarefa #345

**Comment by deniseiras** [comment]
Notas pré-análise:

Como interpretar os dados ?

Analisando o manual http://hpctoolkit.org/manual/HPCToolkit-users-manual.pdf 
A seção 3.1.6 Effective Performance Analysis Techniques mostra duas estratégias de análise, mais detalhadas no cap 4. A estratégia "waste metric" parece ser mais apropriada, detalhada na seção 4.3.

Feita a leitura do grupo das seções 4.1, 4.2 e 4.3, e escolher a melhor estratégia.

Um problema identificado é que os dados de eventos, como PAPI, não foram gerados na execução do hpcrun. Somente foi usada a opção -t "hpcrun -t ../bin/${executable}" que faz: "Generate a call path trace in addition to a call profile.", ou seja, mede apenas os tempos de execução da árvore de chamadas.

É preciso avaliar a estratégia "waste metric" e verificar quais eventos devemos usar com hpcrun -e <nomedoevento>. Para uma lista de eventos: hpcrun --list-events


Obs: não foram gerados dados do gprof (opção -pg) nos executáveis instrumentados para Hpctoolkit, logo essa opção não é necessária: --disable-gprof , mas ela pode ser útil para gerar somente um código que seja útil para ambos, usando o -pg para gprof e hpctoolkit.

**Comment by deniseiras** [comment]
Carlos Renato Souza11:08 AM
PAPI_L1_TCM  0x80000006  No    No   Level 1 cache misses
PAPI_L2_TCM  0x80000007  No    No   Level 2 cache misses
PAPI_L3_TCM  0x80000008  No    No   Level 3 cache misses
Carlos Renato Souza11:09 AM
PAPI_L1_DCM  0x80000000  No    No   Level 1 data cache misses
PAPI_L1_ICM  0x80000001  No    No   Level 1 instruction cache misses
PAPI_L2_DCM  0x80000002  No    No   Level 2 data cache misses
PAPI_L2_ICM  0x80000003  No    No   Level 2 instruction cache misses
PAPI_L3_DCM  0x80000004  No    No   Level 3 data cache misses
PAPI_L3_ICM  0x80000005  No    No   Level 3 instruction cache misses
PAPI_L1_TCM  0x80000006  No    No   Level 1 cache misses
PAPI_L2_TCM  0x80000007  No    No   Level 2 cache
Roberto Pinto Souto11:55 AM
Computer Architecture: A Quantitative Approach Capa comum – 23 novembro 2017
Edição Inglês  por John L Hennessy (Autor), David A Patterson (Autor)

http://acs.pub.ro/~cpop/SMPA/Computer%20Architecture%20A%20Quantitative%20Approach%20(5th%20edition).pdf

**Comment by deniseiras** [comment]
Anotações estudo Denis:

CACHE MISS
==========

Dados ou instruções não encontradas na cache do processador.

- L1-DCACHE-LOAD-MISSES: Number of L1 data cache load misses.
- L1-ICACHE-LOAD-MISSES: Number of L1 instruction cache load misses.
- LLC-load-misses: Number of last-level cache load misses.


TLB MISS
========

TLB (Data Translation Lookaside Buffer): É responsável por auxiliar na tradução de endereços de memória virtual para endereços de memória física durante o carregamento de dados.

Uma falha de carregamento do dTLB ocorre quando a tradução para um endereço de memória virtual solicitado pelo processador não é encontrada no dTLB, exigindo que o processador busque a tradução na tabela de páginas armazenada na memória principal.

- DTLB-LOAD-MISSES: Number of data TLB load misses.
- ITLB-LOAD-MISSES: Number of instruction TLB load misses.


PAGE FAULT MISS
===============

Falhas de busca por dados na memória RAM

MINOR Page Faults - acesso a uma página que não está na memória, mas está alocada no espaço de endereço do processo.
MAJOR Page Faults - acesso a uma página que não está na memória e deve ser recuperada do disco. Falhas MAJOR são mais caras em termos de desempenho em comparação com falhas MINOR.

- PERF_COUNT_SW_PAGE_FAULTS_MIN
- PERF_COUNT_SW_PAGE_FAULTS_MAJ

**Comment by deniseiras** [comment]
@luflarois :
- Variar o tamanho de i no loop -ik. Ex 1/5 a 5/5
  - Observar L1 cache misses de acordo com perf::TOT_CYCLES

- Verificar o uso de inline - lto - gfrotran (talvez usar o PURE resolva em alguns casos) para o domínio total.

- Verificar o uso do PURE para transformação de rotinas inline . Ex: get_data_value
