### ISSUE TITLE
[GCC] PAD: Adaptação dos scripts para o SDumont - Passo 2 (Pré)

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#348]
### User Story

COMO Saulo,
QUEREMOS criar um ambiente de desenvolvimento do MONAN no SDumont (LNCC),
PARA ampliar a oferta de recursos para a equipe de desenvolvedores e pesquisadores.

### :clipboard: Critérios de aceite de conclusão da Issue

- [x] Ambiente dev no SDumont em funcionamento para o Passo 2 (Pré).
- [x] Script atualizado no repositório seguindo a DTN06.

### Detalhamento adicional da atividade

_(... espaço para detalhar melhor o que deve ser realizado)_

### Impactos

_(... consequência técnica encontrada durante a execução da issue)_

### Dependências

A branch que está sendo usada no desenvolvimento desta tarefa é a `feature/monan-scripts-334-QI` e a tarefa principal que reúne todo o processo de adaptação dos scripts no ambiente SDumont é a #334 ;.

# Solução

Neste segundo passo, o script `2.pre_monan.bash` precisa obter dois pacotes de dados os quais eram obtidos através de uma área de dados comum criada pelo GCC para esta finalidade. NO Sdumont não existe essa área comum de dados, a solução adotada foi disponibilizar os pacotes de dados dentro de uma pasta exclusiva na área de ftp do GCC dentro da Egeon, e o script faz o download dos pacotes via `wget`:

- Area de dados ftp criada no http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/MONAN_v0.1.0/
- Pacote de dados estão sendo obtidos via wget: OK!

Próxima fase desse script é criar e submeter o script `make_static.sh` através do `static.sh` : 

- `static.sh`: rodando e gerando o make_static.sh OK! 
- `sbatch make_static.sh`: apresentou um erro ao executar o `init_atmophere_model`: ao carregar bibliioteca `libmpi_usempi.so.20`:
> essa biblioteca esta num diretório carregado pelo openmpi versão 2.* carregado automaticamente pelo pnetcdf da máquina. Mas para compilar o `init_atmospherer_model` foi necessário um openmpi mais moderno, versão 4.*. 
 - Vamos testar uma configuração ideal para resolver este problema:
 > Sugestão do RPS:
 > Carregar os dois pacotes: `openmpi-2` e `openmpi-4` juntamente com `gcc-9.3`, e tente executar para ver se ao solicitar a biblioteca de qualquer das versões o programa encontra pra usar, ja que as duas versões estão carregadas. 
 > Testado! Não deu certo.
 > Sugestão do CR: Vamos tentar compilar os executáveis (`init_atmospherre`) usando essa estratégia de ter as duas versões de openmpi carregados pra ver: COmpilamos! Submetemos! MAs a fila cptec está muito cheia, finalizamos o trabalho aguardando o job ser executado para ver se deu algum erro ou não. 
 > Enquanto isso, o suporte esta instalando o pnetcdf com openmpi-4.

---

Enquanto o helpdesk do SD instala os pacotes solicitados, iniciei a instalação do WRF+WPS via spack para obtenção do degrib.exe:

- Instalando spack padrão:
~~~
git clone https://github.com/spack/spack.git spack_wps
git checkout tags/v0.21.0 -b branch_v0.21.0
~~~

- Script environment do spack:
~~~
module purge
export MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/scratch/app/modulos
module load sequana/current
module load gcc/13.2_sequana
module list

. /scratch/cptec/carlos.souza4/GitHub/spack_wps/share/spack/setup-env.sh

export SPACK_USER_CONFIG_PATH=/prj/cptec/carlos.souza4/.spack/spack_wps
export SPACK_USER_CACHE_PATH=/prj/cptec/carlos.souza4/.spack/spack_wps/tmp
export TMP=/prj/cptec/carlos.souza4/.spack/spack_wps/tmp
export TMPDIR=/prj/cptec/carlos.souza4/.spack/spack_wps/tmp
mkdir -p /prj/cptec/carlos.souza4/.spack/spack_wps/tmp
~~~

- Modules carregados para esta tarefa:
~~~
Currently Loaded Modulefiles:
  1) /scratch/app/modulos/sequana/current   2) gcc/13.2_sequana
~~~

- Instalando WPS:
~~~
spack compiler find
==> Added 1 new compiler to /prj/cptec/carlos.souza4/.spack/spack_wps/linux/compilers.yaml
    gcc@13.2.0
==> Compilers are defined in the following files:
    /prj/cptec/carlos.souza4/.spack/spack_wps/linux/compilers.yaml

spack versions wps
=> Safe versions (already checksummed):
  4.5  4.4  4.3.1  4.3  4.2
==> Remote versions (not yet checksummed):
  4.1  4.0.3  4.0.2  4.0.1  4.0
~~~

Escolhido a versão mais recente confiável para teste 2: `wps@4.5`

~~~
module avail gcc

--------------------------------------------------------- /scratch/app_sequana/modulos ---------------------------------------------------------
gcc/10.2_sequana            gcc/4.9.2-petrobras_sequana gcc/6.5_sequana             gcc/7.4_sequana
gcc/11.1_sequana            gcc/4.9.2_sequana           gcc/6.5_sequana_teste       gcc/8.3_sequana
gcc/13.2_sequana            gcc/4.9.3_sequana           gcc/7.4.0_sequana           gcc/9.3_sequana
~~~

Escolhido a versão mais recente confiável para teste 2:  `gcc@13.2.0`

~~~
spack spec wps@4.5%gcc@13.2.0
Input spec
--------------------------------
   wps@4.5%gcc@13.2.0

Concretized
--------------------------------
   wps@4.5%gcc@13.2.0 build_system=generic build_type=serial patches=62c1bcc,92c2511,e86d029 arch=linux-rhel7-skylake_avx512
       ^jasper@2.0.32%gcc@13.2.0+jpeg~opengl+shared build_system=generic build_type=Release arch=linux-rhel7-skylake_avx512
           ^cmake@3.27.7%gcc@13.2.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rhel7-skylake_avx512
               ^curl@8.4.0%gcc@13.2.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-rhel7-skylake_avx512
                   ^nghttp2@1.57.0%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
           ^libjpeg-turbo@3.0.0%gcc@13.2.0~ipo~jpeg8+shared+static build_system=cmake build_type=Release generator=make arch=linux-rhel7-skylake_avx512
               ^nasm@2.15.05%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
       ^libtool@2.4.7%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
           ^gmake@4.4.1%gcc@13.2.0~guile build_system=generic arch=linux-rhel7-skylake_avx512
       ^m4@1.4.19%gcc@13.2.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-rhel7-skylake_avx512
           ^diffutils@3.9%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
               ^libiconv@1.17%gcc@13.2.0 build_system=autotools libs=shared,static arch=linux-rhel7-skylake_avx512
           ^libsigsegv@2.14%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
       ^netcdf-c@4.9.2%gcc@13.2.0+blosc~byterange~dap~fsync~hdf4~jna+mpi~nczarr_zip+optimize~parallel-netcdf+pic+shared+szip+zstd build_system=autotools patches=0161eb8 arch=linux-rhel7-skylake_avx512
           ^bzip2@1.0.8%gcc@13.2.0~debug~pic+shared build_system=generic arch=linux-rhel7-skylake_avx512
           ^c-blosc@1.21.5%gcc@13.2.0+avx2~ipo build_system=cmake build_type=Release generator=make arch=linux-rhel7-skylake_avx512
               ^lz4@1.9.4%gcc@13.2.0+pic build_system=makefile libs=shared,static arch=linux-rhel7-skylake_avx512
               ^snappy@1.1.10%gcc@13.2.0~ipo+pic+shared build_system=cmake build_type=Release generator=make arch=linux-rhel7-skylake_avx512
           ^hdf5@1.14.3%gcc@13.2.0~cxx+fortran+hl~ipo~java~map+mpi+shared~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-rhel7-skylake_avx512
           ^libaec@1.0.6%gcc@13.2.0~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-rhel7-skylake_avx512
           ^zlib-ng@2.1.4%gcc@13.2.0+compat+opt build_system=autotools arch=linux-rhel7-skylake_avx512
           ^zstd@1.5.5%gcc@13.2.0+programs build_system=makefile compression=none libs=shared,static arch=linux-rhel7-skylake_avx512
       ^netcdf-fortran@4.6.1%gcc@13.2.0~doc+pic+shared build_system=autotools arch=linux-rhel7-skylake_avx512
       ^openmpi@4.1.6%gcc@13.2.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-pmix~java~legacylaunchers~lustre~memchecker~openshmem~orterunprefix+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-rhel7-skylake_avx512
           ^hwloc@2.9.1%gcc@13.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-rhel7-skylake_avx512
               ^libpciaccess@0.17%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
                   ^util-macros@1.19.3%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
               ^libxml2@2.10.3%gcc@13.2.0+pic~python+shared build_system=autotools arch=linux-rhel7-skylake_avx512
                   ^xz@5.4.1%gcc@13.2.0~pic build_system=autotools libs=shared,static arch=linux-rhel7-skylake_avx512
           ^numactl@2.0.14%gcc@13.2.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-rhel7-skylake_avx512
               ^autoconf@2.69%gcc@13.2.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-rhel7-skylake_avx512
               ^automake@1.16.5%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
           ^openssh@9.5p1%gcc@13.2.0+gssapi build_system=autotools arch=linux-rhel7-skylake_avx512
               ^krb5@1.20.1%gcc@13.2.0+shared build_system=autotools arch=linux-rhel7-skylake_avx512
                   ^bison@3.8.2%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
                   ^findutils@4.9.0%gcc@13.2.0 build_system=autotools patches=440b954 arch=linux-rhel7-skylake_avx512
                   ^gettext@0.22.3%gcc@13.2.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-rhel7-skylake_avx512
                       ^tar@1.34%gcc@13.2.0 build_system=autotools zip=pigz arch=linux-rhel7-skylake_avx512
                           ^pigz@2.7%gcc@13.2.0 build_system=makefile arch=linux-rhel7-skylake_avx512
               ^libedit@3.1-20210216%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
               ^libxcrypt@4.4.35%gcc@13.2.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-rhel7-skylake_avx512
               ^openssl@3.1.3%gcc@13.2.0~docs+shared build_system=generic certs=mozilla arch=linux-rhel7-skylake_avx512
                   ^ca-certificates-mozilla@2023-05-30%gcc@13.2.0 build_system=generic arch=linux-rhel7-skylake_avx512
           ^perl@5.38.0%gcc@13.2.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-rhel7-skylake_avx512
               ^berkeley-db@18.1.40%gcc@13.2.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rhel7-skylake_avx512
               ^gdbm@1.23%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
                   ^readline@8.2%gcc@13.2.0 build_system=autotools patches=bbf97f1 arch=linux-rhel7-skylake_avx512
           ^pkgconf@1.9.5%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
           ^pmix@5.0.1%gcc@13.2.0~docs+pmi_backwards_compatibility~python~restful build_system=autotools arch=linux-rhel7-skylake_avx512
               ^libevent@2.1.12%gcc@13.2.0+openssl build_system=autotools arch=linux-rhel7-skylake_avx512
       ^tcsh@6.24.00%gcc@13.2.0 build_system=autotools patches=3a4e60f arch=linux-rhel7-skylake_avx512
           ^ncurses@6.4%gcc@13.2.0~symlinks+termlib abi=none build_system=autotools arch=linux-rhel7-skylake_avx512
       ^time@1.9%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
       ^wrf@4.5.1%gcc@13.2.0~adios2~chem~netcdf_classic+pnetcdf build_system=generic build_type=dmpar compile_type=em_real nesting=basic patches=29af725,68548f6,908c718,e07c39c,e4971f6,e6f3db3,f3dd50d arch=linux-rhel7-skylake_avx512
           ^libpng@1.6.39%gcc@13.2.0~ipo~pic build_system=cmake build_type=Release generator=make libs=shared,static arch=linux-rhel7-skylake_avx512
           ^libtirpc@1.3.3%gcc@13.2.0 build_system=autotools arch=linux-rhel7-skylake_avx512
           ^parallel-netcdf@1.12.3%gcc@13.2.0~burstbuffer+cxx+fortran+pic+shared build_system=autotools arch=linux-rhel7-skylake_avx512



spack install wps@4.5%gcc@13.2.0

~~~

- Verificando se o executável alvo foi gerado: `ungrib.exe` :
~~~
export WPSDIR=$(spack location -i wps@4.3.1%gcc@9.3.0)
if [ ! -s ${WPSDIR}/ungrib.exe ]
then
   echo "Erro:: ${WPSDIR}/ungrib.exe not installed."
   exit
fi
~~~
- Executável obtido com sucesso!

- Executável inserido na pasta `MONAN/exec` com o nome de `ungrib_SD.exe` no pacote de dados ` MONAN_testcase.v1.0.tgz` e já disponível tanto na área de ftp original do inpe @egeon: `XXX` quanto na área TMP do sdumont18 `/tmp/pesquisa/dmdcc/monan/MONAN_v0.1.0/`.

Próximos passos:

- rodar o make_static.sh usando novos pacotes instalados pelo helpdesk  
 
 
- Rodamos o make_static.sh usando o novo pacote PNETCDF instalado pelo helpdesk no SD: `pnetcdf/1.12.3_openmpi-4.1.6_gnu_sequana`  :
~~~
Currently Loaded Modulefiles:
  1) /scratch/app/modulos/sequana/current       4) pnetcdf/1.12.3_openmpi-4.1.6_gnu_sequana
  2) gcc/13.2_sequana                           5) netcdf/4.6_openmpi-2.0_gnu_sequana
  3) openmpi/gnu/4.1.6_sequana
~~~

Mas agora vamos precisar do pacote NETCDF mais atual e com as mesmas dependências do pacote PNETCDF recém instalado.

O atual NETCDF carrega os seguintes pacotes dependentes:

~~~
module load netcdf/4.6_openmpi-2.0_gnu_sequana
module list
Currently Loaded Modulefiles:
  1) /scratch/app/modulos/sequana/current   4) pnetcdf/1.10_openmpi-2.0_gnu_sequana
  2) openmpi/gnu/2.0.4.2_sequana            5) netcdf/4.6_openmpi-2.0_gnu_sequana
3) hdf5/1.8_openmpi-2.0_gnu_sequana
~~~

Então solicitamos ao helpdesk a gentileza de instalar o NETCDF 4.6 porém com as seguintes dependências:
~~~
openmpi/gnu/4.1.6_sequana
gcc/13.2_sequana
pnetcdf/1.12.3_openmpi-4.1.6_gnu_sequana
~~~

Usando agora as versões mais recentes do `netcdf`, `pnecdf` e `openmpi` do SDumont no arquivo `load_monan_app_modules.sh`
```bash
#module purge command doesn't working correctly
module purge
export MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/scratch/app/modulos

module load sequana/current
module load netcdf/4.9.2_openmpi-4.1.6_gnu_sequana
module load pnetcdf/1.12.3_openmpi-4.1.6_gnu_sequana
#module unload openmpi/gnu/2.0.4.2_sequana pnetcdf/1.10_openmpi-2.0_gnu_sequana

# Preencher os caminhos abaixo com o comando module show pacote:
export PNETCDF=/scratch/app_sequana/pnetcdf/1.12.3_openmpi-4.1.6_gnu
export NETCDF=/scratch/app_sequana/netcdf/4.9.2

module list

export OMP_NUM_THREADS=1
export INIT_ATM_PART=sequana_cpu_dev
```

Fazendo executar com 32 processos MPI em 32 núcleos (*cores*), no arquivo `MONAN_ori/testcase/scripts/static.sh`, 
```bash
    cores=32
```

Resultado da execução do script `2.pre_monan.bash`

```bash
 ls MONAN/testcase/runs/ERA5/static/ -l
total 3450736
drwxr-xr-x 2 rpsouto cenapadrjsd       4096 Mar  1 16:49 logs
-rwxr-xr-x 1 rpsouto cenapadrjsd       2897 Mar  1 16:39 make_static.sh
-rw-r--r-- 1 rpsouto cenapadrjsd       1304 Mar  1 16:39 namelist.init_atmosphere
-rw-r--r-- 1 rpsouto cenapadrjsd        669 Mar  1 16:39 streams.init_atmosphere
-r--r--r-- 1 rpsouto cenapadrjsd    2752016 Mar  1 16:39 x1.1024002.graph.info.part.32
-r--r--r-- 1 rpsouto cenapadrjsd 1630211184 Mar  1 16:39 x1.1024002.grid.nc
-rw-r--r-- 1 rpsouto cenapadrjsd 1900562836 Mar  1 16:49 x1.1024002.static.nc
```
O resultado esperado, geração do arquivo `x1.1024002.static.nc` foi alcançado.

# Problemas encontrados

1. **Erro ao executar**  **[EM ANDAMENTO]**
 Erro ao executar o `init_atmophere_model`: ao carregar bibliioteca `libmpi_usempi.so.20`:
> essa biblioteca esta num diretório carregado pelo openmpi versão 2.* carregado automaticamente pelo pnetcdf da máquina. Mas para compilar o `init_atmospherer_model` foi necessário um openmpi mais moderno, versão 4.*.  
- Foi solicitado ao helpdesk do SD que instalasse o pnetcdf utilizando uma versão mais moderna do openmpi/gcc. 
- Helpdesk respondeu solicitando detalhes dos pacotes que precisam ser instalados, vamos levantar os detalhes e enviar pra eles de volta ASAP: [_Respondido_ ao helpdesk do SD]

> Para efetuarmos uma instalação, é necessário que nos envie as informações abaixo:
> 
> Versão desejada: _1.12/_
> Compilador (Intel ou GCC): _GCC(v.13/)_
> Versão de MPI (se for necessário): _openmpi v.5/_
> Funcionalidades e recursos adicionais que devem ser habilitados durante a compilação: _--_
> URL para download: _parallel-netcdf.github.io/_
> Caso seja um software proprietário, que dependa de licença, cabe ao usuário fornecer a licença para ser utilizado no SDumont.
> Em caso de dúvidas, estamos à disposição.

- Aproveitando a oportunidade, também inclui no pedido ao helpdesk a instalação do Git-Flow no SD. 

Tarefa em **Blocked**.

---

2. **Disk quota exceeded**  **[AGUARDANDO SOLUÇÃO]**
Disk quota exceeded.
Paramos o desenv da tarefa por falta de espaço no disco do grupo cptec.
- Email enviado ao Luiz Flavio solicitando providencia.
- Email enviado ao suporte do SD que respondeu orientando que os usuários do projeto CPTEC fizessem uma limpeza em seus diretórios para liberar espaço em disco, pois não haveria previsão de liberação de espaço em disco adicional por parte do LNCC.
Tarefa em **Blocked**.

3. **Executável `degrib.exe`não gerado**   **[RESOLVIDO]**
Instalando a versão igual à versão utilizada no Egeon `spack install wps@4.3.1%gcc@9.3.0`, todos os pacotes dependentes foram instalados com sucesso mas o ultimo passo do wps não gerou o executável alvo `degrib.exe`, outras versões de `wps` e de `gcc` serão testadas e conseguimos obter o executável com a seguinte versão:  `wps@4.5%gcc@13.2.0`. 

4. **Alteração no arquivo `MONAN_src/MONAN-Model_v0.1.0_sdumont.gnu/Makefile`para resolver o erro de compilação**

    ```bash
    ifdef MPAS_EXTERNAL_CPPFLAGS
            override CPPFLAGS += $(MPAS_EXTERNAL_CPPFLAGS)
    endif
    ####################################################
    
    override LIBS += -lstdc++
    
    override CPPFLAGS += -DMPAS_BUILD_TARGET=$(BUILD_TARGET)
    ```

5. **Muita demora ao baixar o arquivo de dados `MONAN_data_v1.0.tgz` no script `2.pre_monan.bash`**
    - Solução é baixar previamente estes dados e deixar disponível em uma área compartilhada entre os usuários do mesmo grupo/projeto no SDumont. No caso, o projeto é ` cenapadrjsd`, e o arquivo de dados `MONAN_data_v1.0.tgz` está armazenado em local definido na variável ` DIRDADOS_LOCAL=/scratch/cenapadrjsd/monan/datain`
    - Para o grupo/projeto `cptec`, os dados devem estar em um local onde todos usuários do CPTEC no SDumont também tenham acesso.
    - De todo modo, a descompactação do arquivo `MONAN_data_v1.0.tgz` é igualmente bastante demorada. O ideal seria ter os arquivos de dados também previamente descompactados na pasta compartilhada.
      - Se a pasta `MONAN`  já existir, então o arquivo `MONAN_data_v1.0.tgz` não é descompactado.

6. **Erro de execução devido a falha de leitura dos arquivos `x1.1024002.graph.info.part.32` e `x1.1024002.grid.nc`** 

    - Este erro é devido a incompatibilidade do [Simple MPAS IO Layer - SMIOL](https://github.com/MPAS-Dev/SMIOL) com o sistema de arquivos `Lustre`, em que a leitura de ***links simbólicos*** não funciona.
      ```bash
      $ cat /scratch/cenapadrjsd/rpsouto/sequana/projetos/monan/github/monanadmin/MONAN-scripts_sdumont/sdumont/MONAN/testcase/runs/ERA5/static/logs/my_job.o10938232
      
      STARTING AT Mon Feb 26 13:44:27 -03 2024
      Mon Feb 26 13:44:27 -03 2024
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      MPI error (MPI_File_open) : MPI_ERR_OTHER: known error not in list
      FINISHED AT Mon Feb 26 13:44:39 -03 2024
        BUMMER: Static generation failed for some yet unknown reason.
      
      CRITICAL ERROR: Decomposition file: x1.1024002.graph.info.part.16 contains more than -1 cells
      
       -----------------------------------------
       Total log messages printed:
          Output messages =                   35
          Warning messages =                   9
          Error messages =                     2
          Critical error messages =            1
       -----------------------------------------
       Logging complete.  Closing file at 2024/02/26 13:44:36
      ```
    
      ```bash
      $ cat /scratch/cenapadrjsd/rpsouto/sequana/projetos/monan/github/monanadmin/MONAN-scripts_sdumont/sdumont/MONAN/testcase/runs/ERA5/static/logs/my_job.e10938232
      Loading SEQUANA Software environment
      Currently Loaded Modulefiles:
        1) /scratch/app/modulos/sequana/current
        2) gcc/13.2_sequana
        3) openmpi/gnu/4.1.6_sequana
        4) pnetcdf/1.12.3_openmpi-4.1.6_gnu_sequana
        5) hdf5/1.14.3_openmpi-4.1.6_gnu_sequana
        6) netcdf/4.9.2_openmpi-4.1.6_gnu_sequana
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      get_stripe failed: 61 (No data available)
      --------------------------------------------------------------------------
      MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
      with errorcode 1734831948.
      
      NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
      You may or may not see output from other processes, depending on
      exactly when Open MPI kills them.
      --------------------------------------------------------------------------
      
      real    0m11.232s
      user    0m0.037s
      sys     0m0.090s
      ```
    
    - Efetuando a correção no arquivo `MONAN_ori/testcase/scripts/static.sh`, copiando os arquivos de grade no lugar de usar link simbólico
      ```bash
      #ln -sf ${DATADIR}/meshes/x1.${RES}.grid.nc .
      cp ${DATADIR}/meshes/x1.${RES}.grid.nc .
      
      #ln -sf ${NMLDIR}/x1.${RES}.graph.info.part.${cores} .
      cp ${NMLDIR}/x1.${RES}.graph.info.part.${cores} .
      ```

### :white_check_mark: Conclusão

_(... texto que sintetiza a finalização da issue, destacando aspectos positivos e negativos)_

- As alterações efetuadas nos scripts originais, para adaptação ao ambiente do SDumont, foram bem sucedidas.

### :spiral_calendar: Trabalhos Futuros

_(... caso a issue demande trabalhos futuros detalhar aqui e marcar o campo "Future Work" ao lado para "Sim")_

- Aprimorar a verificação de compilação dos executáveis gerados.
  - Mesmo quando ocorre erro na compilação de algum executável, o script `1.install_monan.bash` prossegue adiante.
  - O ideal seria a interrupção total do script `1.install_monan.bash`, a fim de chamar a atenção para o erro que ocorreu.
- Incluir as demais fases de execução do MONAN 
  - *Run the model*
  - *Run the post-processing model*
  - *Run one single simple forecast figure example*

**Comment by joaomas** [comment]
Blocked ciente. Aguardando retorno do Luiz Flávio.

**Comment by joaomas** [comment]
Ticket#2023120710000322] Confirmação de abertura de chamado
Recebemos sua mensagem referente ao assunto netcdf-c + netcdf-fortran e seu chamado foi gerado.
O número do chamado é : 2023120710000322

**Comment by joaomas** [comment]
1. 
Date: sex., 17 de nov. de 2023 11:08
Subject: [Ticket#2023110710000351] Chamado em atendimento
To: <bidu@lncc.br>
[Ticket#2023110710000351] Chamado em atendimento
Prezado(a) Eduardo Lucio Mendes Garcia,
Seu chamado número 2023110710000351 ­com título "modulo pnetcdf" está em andamento.

2.
seg., 4 de dez., 18:20 (há 2 dias)
[Ticket#2023112910000177] Chamado em atendimento

**Comment by ebiduardo** [comment]
Novos módulos de netcdf, netcdff e pnetcdf foram instalados e novos executáveis de atmosphere_model e init_atmosphere_model precisam ser instalados.
Retornar a issue 348

Em seguida deve-se voltar a esta issue para a execução do novo init_atmosphere_model

**Comment by deniseiras** [comment]
> colegas, ainda estou agarrado na execução do 1.install_monan.bash. hoje percebi um funcionamento do script que passei a achar errado...

Ótimo Bidu. Vc está usando qual versão do MONAN scripts ? Digo, em algum momento copiou uma versão da pasta "egeon" pro SD e está editando localmente lá ?

Uma coisa que precisamos fazer é criar a pasta "santos_dummont" (irmã de egeon), onde vc pode colocar e alterar os scripts mais especificamente para o SD. Então, essas correções genéricas que citou, nós replicamos depois para a pasta "egeon".
Obrigado!

**Comment by ebiduardo** [comment]
Opa.

Não tenho certeza se foi criada uma Sdumont.
Vou procurar me informar

Em qui., 25 de jan. de 2024 11:20, Denis Eiras ***@***.***>
escreveu:

**Comment by robertopsouto** [comment]
@ebiduardo , por favor, poderia verificar a descrição de **Solução**, **Problemas encontrados**, **Conclusão** e **Trabalhos Futuros**? Estaria faltando algo para descrever, ou precisaria modificar alguma coisa na descrição?
