### ISSUE TITLE
[GCC] PAD: Gerar condições iniciais para analise de desempenho do GF

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#376]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS gerar as condições iniciais,
PARA testar o GF.

## :clipboard: Critérios de aceite de conclusão da Issue

- Ter as condições iniciais geradas para o domínio:
- [X] 20x20
- [x] 30x30
- 40x40 (sem necessidade - nova abordagem)
- 50x50 (sem necessidade - nova abordagem)
- [x] 60x60
- [X] Testar no GF o domínio 20x20.
- [x] Alterar os critérios de aceite e detalhamento das issues 366 e 367.
- Para cada uma das condições, rodar o GF standalone e replicar as colunas enviados pelo Saulo (1 coluna) para cada uma das grades. (sem necessidade - nova abordagem)
- Salvar os dados no FTP (ao final). (sem necessidade - nova abordagem)

## :pencil: Detalhamento adicional da atividade

o modelo BRAMS foi usado para gerar as condições iniciais. Para isso foi acrescentada uma mudança no código de brams/src/brams/cuparm/cup_grell3.F90 de forma a gerar as condições. A modificação está antes da chamada de convParGFDriver e depois da chamada da mesma. O trecho de código é mostrado abaixo:

ANTES DA CHAMADA:
```fortran
!LFR Gera os dados de entrada para testes
   write(ctime,fmt="(I4.4)") int(time)
   write(45,*) "lons: ", lons
   write(45,*) "lats: ", lats
   open(newunit = l_unit,file = "gf_dataIn-"//ctime//".bin",ACCESS = "stream", action="write", status="replace")
   write(l_unit) confrq
   write(l_unit) mxp,myp,mzp,mtp ,nmp, time, itime1, maxiens
   write(l_unit) ims,ime, jms,jme, kms,kme
   write(l_unit) its,ite, jts,jte, kts,kte
    
		write(l_unit) flip       
   write(l_unit) fscav_int 
   write(l_unit) mynum     
   write(l_unit) dtlt     
   write(l_unit) dx2d     
   write(l_unit) stochastic_sig
   write(l_unit) zm3d   
   write(l_unit) zt3d   
		write(l_unit) dm3d   
   write(l_unit) lons   
   write(l_unit) lats   
   write(l_unit) aot500 
   write(l_unit) temp2m 
   write(l_unit) turb_g(ngrid)%sflux_r 
   write(l_unit) turb_g(ngrid)%sflux_t 
   write(l_unit) grid_g(ngrid)%topt    
   write(l_unit) xland                 
   write(l_unit) sfc_press             
   write(l_unit) kpbl                  
   write(l_unit) tke_pbl               
   write(l_unit) col_sat
   write(l_unit) up     
   write(l_unit) vp     
   write(l_unit) wp     
   write(l_unit) temp   
   write(l_unit) press  
   write(l_unit) rvap   
		write(l_unit) mp_ice 
		write(l_unit) mp_liq 
		write(l_unit) mp_cf  
   write(l_unit) rvap   
   write(l_unit) TRACER   
   write(l_unit) buoy_exc 
		write(l_unit)  gsf_t   
		write(l_unit)  gsf_q   
   write(l_unit) advf_t   
		write(l_unit) sgsf_t   
		write(l_unit) sgsf_q   
   write(l_unit) cuparm_g(ngrid)%conprr  
   write(l_unit) g3d_g(ngrid)%lightn_dens
   write(l_unit) g3d_g(ngrid)%rh_dicy_fct
   write(l_unit) g3d_g(ngrid)%thsrc      
   write(l_unit) g3d_g(ngrid)%rtsrc      
   write(l_unit) g3d_g(ngrid)%clsrc      
   write(l_unit) g3d_g(ngrid)%nlsrc      
   write(l_unit) g3d_g(ngrid)%nisrc      
   write(l_unit) g3d_g(ngrid)%usrc       
   write(l_unit) g3d_g(ngrid)%vsrc       
    write(l_unit) sub_mpqi     
    write(l_unit) sub_mpql     
    write(l_unit) sub_mpcf     
    write(l_unit) src_buoy    
    write(l_unit) src_chem   
    write(l_unit) revsu_gf    
    write(l_unit) prfil_gf     
		write(l_unit) do_this_column
    write(l_unit) ierr4d_tmp    
    write(l_unit) jmin4d_tmp    
    write(l_unit) klcl4d_tmp    
    write(l_unit) k224d_tmp     
    write(l_unit) kbcon4d_tmp   
    write(l_unit) ktop4d_tmp    
    write(l_unit) kstabi4d_tmp  
    write(l_unit) kstabm4d_tmp  
    write(l_unit) cprr4d_tmp    
    write(l_unit) xmb4d_tmp     
    write(l_unit) edt4d_tmp     
    write(l_unit) pwav4d_tmp    
    write(l_unit) sigma4d_tmp   
    write(l_unit) pcup5d_tmp        
    write(l_unit) up_massentr5d_tmp 
    write(l_unit) up_massdetr5d_tmp 
    write(l_unit) dd_massentr5d_tmp 
    write(l_unit) dd_massdetr5d_tmp 
    write(l_unit) zup5d_tmp         
    write(l_unit) zdn5d_tmp         
    write(l_unit) prup5d_tmp        
    write(l_unit) prdn5d_tmp        
    write(l_unit) clwup5d_tmp       
    write(l_unit) tup5d_tmp         
    write(l_unit) conv_cld_fr5d_tmp 
    write(l_unit) AA0,AA1,AA2,AA3,AA1_BL,AA1_CIN,TAU_BL,TAU_EC
    write(l_unit) VAR2d,VAR3d_aGF,VAR3d_bGF,VAR3d_cGF,VAR3d_dGF
    close(l_unit)


    wlpool = 5.
    qexp   = 0.
    hexcp  = 0.
```
DEPOIS DA CHAMADA:

```fortran
!LFR Gera os dados de saida para testes

    glon= lons*180./3.14159
    glat= lats*180./3.14159

    rec_size = mxp*myp*4
    print *, rec_size
    open(newunit = l_unit, file="gf_dataOut-ref-"//ctime//".gra", form='unformatted', &
             access='direct', status='replace', recl=rec_size)
    irec=1
    do nz=1,mzp
       write(l_unit,rec=irec) g3d_g(ngrid)%thsrc(nz,:,:)
       irec=irec+1
    enddo
    do nz=1,mzp
       write(l_unit,rec=irec) g3d_g(ngrid)%rtsrc(nz,:,:)
       irec=irec+1
    enddo         
    do nz=1,mzp
       write(l_unit,rec=irec) g3d_g(ngrid)%clsrc(nz,:,:)
       irec=irec+1
    enddo       
    do nz=1,mzp
       write(l_unit,rec=irec) g3d_g(ngrid)%nlsrc(nz,:,:)
       irec=irec+1
    enddo  
    do nz=1,mzp
       write(l_unit,rec=irec) g3d_g(ngrid)%nisrc(nz,:,:)
       irec=irec+1
    enddo  
    do nz=1,mzp
       write(l_unit,rec=irec) g3d_g(ngrid)%usrc(nz,:,:)
       irec=irec+1
    enddo  
    do nz=1,mzp
       write(l_unit,rec=irec) g3d_g(ngrid)%vsrc(nz,:,:)
       irec=irec+1
    enddo  
    write(l_unit,rec=irec) cuparm_g(ngrid)%conprr(:,:)
    close(l_unit)

    open(newunit = l_unit, file="gf_dataOut-ref-"//ctime//".ctl", action='write', status='replace')

    write(l_unit,*) 'dset ^'//"gf_dataOut-ref-"//ctime//".gra"
    !writing others infos to ctl
    write(l_unit,*) 'undef -0.9990000E+34'
    write(l_unit,*) 'title GF_teste'
    write(l_unit,*) 'xdef ',mxp,' linear ',glon(1,1),glon(2,1)-glon(1,1)
    write(l_unit,*) 'ydef ',myp,' linear ',glat(1,1),glat(1,2)-glat(1,1)
    write(l_unit,*) 'zdef ',mzp,'levels',flip
    write(l_unit,*) 'tdef 1 linear 00:00Z01JAN200 1mo'
    write(l_unit,*) 'vars ',8
    write(l_unit,*) 'thsrc',mzp,'99 ','K'
    write(l_unit,*) 'rtsrc',mzp,'99 ','K'
    write(l_unit,*) 'clsrc',mzp,'99 ','K'
    write(l_unit,*) 'nlsrc',mzp,'99 ','K'
    write(l_unit,*) 'nisrc',mzp,'99 ','K'
    write(l_unit,*) 'usrc ',mzp,'99 ','K'
    write(l_unit,*) 'vsrc ',mzp,'99 ','K'
    write(l_unit,*) 'conprr ','01',' 99 ','K'
    write(l_unit,*) 'endvars'
    close(l_unit)
```
Após a modificação é preciso compilar o BRAMS. Com o novo código deve ser feito a rodada com os diversos domínios.

## :comet: Impactos

_(... consequência técnica encontrada durante a execução da issue)_

## :link: Dependências

- [ ] Envio dos dados pelo Saulo (1 coluna)

#### Domínio central e rodada 20 x 20 pontos:

O domínio foi definido em região amazônica com ponto central em 2s e 60w, conforme a figura abaixo, que plota a magnitude(ou direção) do vento saída do brams:

![Image](https://github.com/monanadmin/monan/assets/10886652/65a7cb59-ae42-458a-8a1d-e38a7ccc16e4)

Foi criado um script python para gerar os RAMSINS SFC/VFL/INI e sbatch'es correspondentes em:
https://github.com/monanadmin/MONAN_GCC_issues/tree/main/376

Foram alteradas posições e acrescentadas algumas variáveis na escrita da saída do brams, e alerada a posição da inicialização das variáveis wlpool, qexp e hexcp . Esse código encontra-se anexado nos comentários. O trecho do código corrigido antes da chamada da subrotina convParGFDriver.

- Diferenças de *cup_grell3.F90* corrigidas do lado esquerdo mostradas a seguir:

![Image](https://github.com/monanadmin/monan/assets/98923325/e5f46a32-8239-4d78-be6e-633cbee4c3a6)

- Checagem visual da escrita em *cup_grell3.F90* com leitura de *gf_teste.F90* mostrada a seguir:

![Image](https://github.com/monanadmin/monan/assets/98923325/9c5a0752-8fef-49f9-9348-0add7d674121)

- Após a correção, a saída do GF foi verificada e é mostrada a seguir:

![Image](https://github.com/monanadmin/monan/assets/98923325/6e40d355-fbb1-4c5e-a2ef-4e7e93c56a4d)

- Também foi verificada a saída do GF com o hpctoolkit:

![Image](https://github.com/monanadmin/monan/assets/98923325/6c434bad-1132-43ca-8a93-2795b317f02f)

## :rotating_light: Problemas encontrados

- Não é possível rodar com 10 x 10 pontos devido a Runge Kupta (Mínimo seria 11 x 11)
- Ao testar o GF com a saída do brams 20x20, houve erro na leitura desse arquivo. Para corrigir o erro, o arquivo *cup_parm.F90* foi modificado, conforme solução.

As rodadas necessárias foram executadas. Mas foi verificado que as saídas (em sua maioria) estavam zeradas. Investigações posteriores mostraram que havia uma diferença entre as versões usadas no BRAMS (que foi usado para a geração dos dados iniciais) e as no repositório github.

Discutiu-se então levar o problema ao Saulo para que ele dê uma posição sobre versionamento entre os códigos. Saulo esclareceu que são códigos distintos e que deveria ser usado o anterior para geração dos dados. Logo o BRAMS não serviria.

## :white_check_mark: Conclusão

Para efeito de resolver a geração dos dados adotou-se uma nova estratégia. Saulo gerou os dados em 1 coluna e criou um fonte que permite se ajustar a quantidade de colunas em cada simulação (10, 20, 30, etc). O código gerado pelo Saulo está em https://github.com/saulorfreitas/GF_standalone_SRF e funciona da seguinte maneira. 

1) Escolher o tamanho do problema: deve-se editar o arquivo 1d-gf-test.f90 na linha 10 (em diante) e alterar "mxp" e "myp"

```fortran  
! integer,parameter :: mxp=1    ,myp=1,  mtp =1 , nmp = 1 , mynum=1
  ! integer,parameter :: mxp=10   ,myp=10, mtp =1 , nmp = 1 , mynum=1
   integer,parameter :: mxp=50   ,myp=50, mtp =1 , nmp = 1 , mynum=1
```
2) recompilar o código:  ir para o diretório "Bin" e rodar o makefile:

```bash
 make gnu
```
3) ir para o diretório scripts e rodar o script **GF_standalone_1D.sh**

Com isso o driver convParGFDriver é chamado com o tamanho "i" escolhido. 

> Observação:  para efeito de testes de performance  que gerou essa issue, é preciso ajustar qual arquivo deve ser chamado, de o editado para a direção KI ou IK.

 

## :spiral_calendar: Trabalhos Futuros

- FAzer os testes de performance conforme especificado na issue  apropriada e medir os cache miss para cada número de colunas.
-

**Comment by egkhamis** [comment]
Código *cup_parm,F90* alterado para gerar saída do brams compatível com a entrada do GF lida pelo código *gf_teste.F90*:

[cup_grell3.F90.txt](https://github.com/monanadmin/monan/files/13893714/cup_grell3.F90.txt)

**Comment by deniseiras** [comment]
Olá Saulo, bom dia!

Ficamos com dúvidas com relação à compatibilidade da versão do BRAMS e do GF_StandAlone quando executarmos o BRAMS para gerar as condições iniciais para o GF_StandAlone.

- o arquivo que modificamos no BRAMs: https://github.com/monanadmin/MONAN_GCC_issues/blob/main/376/cup_grell3.F90
- pasta de rodada do BRAMS: /mnt/beegfs/luiz.rodrigues/bin
- Template do RAMSIN usado nas rodadas do BRAMS: https://github.com/monanadmin/MONAN_GCC_issues/blob/main/376/RAMSIN_BASIC_GF_10KM__TEMPLATE
- GF_ConvPar_nml do BRAMS: /mnt/beegfs/luiz.rodrigues/bin/GF_ConvPar_nml
- GF_ConvPar_nml do GF_Standalone: /mnt/beegfs/eduardo.khamis/issues/363/GF_standalone/datain/GF_ConvPar_nml
- Saídas da rodada do BRAMS-cup_grell3 (Egeon): /mnt/beegfs/luiz.rodrigues/bin , pastas 20x20 , 30x30 ... 60x60 .


Exemplo: saídas 20x20 do BRAMS (thsrc na figura):
![image](https://github.com/monanadmin/monan/assets/6113640/296aab0f-ad19-40ef-a012-d5e4ba4ac65d)



Saídas 20x20 do GF_Standalone (thsrc na figura):
![image](https://github.com/monanadmin/monan/assets/6113640/21e0e528-29a2-4c95-bb93-7b491c8f01f5)


Saídas 20x20 do GF_Standalone (conprr na figura):
![image](https://github.com/monanadmin/monan/assets/6113640/99c33751-77df-45af-8de9-5aadd39bf537)


Não sabemos dizer se podemos as saídas geradas no BRAMS  no GF_Standalone, porquem por exemplo, conprr sai com valor constante = 0 no BRAMS. Ainda, verificamos que o GF_ConvPar_nml estão diferentes e temos dúvidas da compatibilidade do código GF_Standalone x BRAMS.

Podemos discutir sobre isso na nossa reunião de planejamento da próxima sprint, segunda-feira (15/01) às 09h:30?
