### ISSUE TITLE
[GCC] GRC: Escolha de mais um template para o site MONAN no GitHub

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#378]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS atualizar o site do MONAN no GitHub,
PARA melhor organizar as informações e documentação sobre o MONAN.

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Escolher mais um template para teste do novo site MONAN no GitHub.

## :pencil: Detalhamento adicional da atividade

- Para o template será utilizado o jekyll. A saber:
Jekyll - Jekyll é um gerador de site estático escrito em Ruby.
Ruby - Ruby é uma linguagem de programação interpretada multiparadigma, de tipagem dinâmica e forte, com gerenciamento de memória automático.
Gem - frontend do RubyGem que é um serviço de hospedagem de gems da comunidade Ruby.
Bundler - Gerenciador de pacotes/depêndencia do Ruby

## :comet: Impactos

-.

## :link: Dependências

-.

## :hammer_and_wrench: Solução

- Template 1(issue anterior): https://joaomas.github.io/repotst/
- Template 2 (issue atual): https://joaomas.github.io/repotst3/

**Outros templates para analise futura:**
. https://jekyllthemes.io/theme/reverie
. https://jekyllthemes.io/theme/feeling-responsive
. https://jekyllthemes.io/theme/agency-jekyll-theme
. https://jekyllthemes.io/theme/minimal-mistakes
. https://kitian616.github.io/jekyll-TeXt-theme/

**Procedimento para instalação - Template Minima:**

$ sudo dnf install ruby ruby-devel
$ sudo dnf group install "Development Tools"

$ echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
$ echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
$ echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
$ source ~/.bashrc

$ gem install jekyll bundler

Na pasta do repositório do site digitar

$ git rm -rf .
$ jekyll new --skip-bundle .

Editar o arquivo 'Gemfile'

$ vim Gemfile
- Adicionar "#" ao início da linha que começa com gem "jekyll" para remover o comentário dessa linha.
- Adicionar o 'gem github-pages' editando a linha que começa com # gem "github-pages". Mudar esta linha para:

gem "github-pages", "~> GITHUB-PAGES-VERSION", group: :jekyll_plugins

Substitua GITHUB-PAGES-VERSION pela última versão compatível do gem github-pages. Encontre esta versão aqui: "Versões de dependência". GITHUB-PAGES-VERSION = 228 para o dia 14/01/24 (deste procedimento)

gem "github-pages", "~> 228", group: :jekyll_plugins

$ bundle install

Testar o site localmente

$ bundle add webrick
$ bundle exec jekyll serve

Abrir o browser e digitar o endereço: "http://localhost:4000"

Comitar tudo:

$ git add .
$ git commit -m 'Initial GitHub pages site with Jekyll'
$ git push -u origin BRANCH

Referências: 
https://docs.github.com/pt/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll
https://docs.github.com/pt/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll
https://jekyllrb.com/docs/installation/other-linux/
https://jekyllrb.com/docs/themes/#overriding-theme-defaults
https://docs.github.com/pt/pages/setting-up-a-github-pages-site-with-jekyll/adding-content-to-your-github-pages-site-using-jekyll

**Procedimento para instalação - Template Minimal:**

$ git clone https://github.com/pages-themes/minimal.git .
$ cp -r * ../repotst3/
$ cd repotst3/
$ bundle install
$ bundle add webrick
$ bundle exec jekyll serve

## :rotating_light: Problemas encontrados

- Complexidade na curva de aprendizado para usar o jekyll.

## :white_check_mark: Conclusão

- Template básico instalado para aprendizado e testes.

## :spiral_calendar: Trabalhos Futuros

-.

**Comment by cfbastarz** [comment]
Olá @joaomas, há também o https://www.mkdocs.org/ que suporta vários temas (inclusive o https://squidfunk.github.io/mkdocs-material/) - ambos são utilizados no site do comitê científico do MONAN. Há uma lista de temas disponíveis para o MkDocs em https://github.com/mkdocs/catalog.

Abs!
