### ISSUE TITLE
[GCC] PAD: Investigações Condição Inicial (CI) - Testes Contínuos - MONAN-MPAS [SPIKE]

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#387]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS iniciar o processo de testes contínuos do MONAN-MPAS começando pelas condições iniciais,
PARA melhor avaliação do modelo e uso do Egeon.

## :clipboard: Critérios de aceite de conclusão da Issue

- [X] Levantar o que tem atualmente referente a CI para uso com o GFS.
- [X] Levantar os dados do GFS que serão utilizados (dados do IO).
- [X] Ao final ter um levantamento sobre as próximas atividades.

## :pencil: Detalhamento adicional da atividade

**E-mail Saulo - 15/01**

O plano tem a seguinte configuração:

1) 24 km horizontal uniforme
2) GFS para ci atmosférica, superfície (umid do solo e temp) e SST
3) saídas a cada 1h com as variáveis a serem definidas pelo GAM e SFC
4) configuração física: aquela do relatório técnico de avaliação com o GF em vez do Tiedtke.
5) Deixar preparado o mesmo sistema mas com 10 km de espaçamento horizontal/uniforme.
 
Demandas:
1) GAM : passar os scripts que criam a CI com o GFS para o grupo do GCC
2) GAM/SFC : produzir a lista de variáveis de saída.

## :comet: Impactos

_(... consequência técnica encontrada durante a execução da issue)_

## :link: Dependências

_(... issues e requisitos que devem ser executados previamente)_

### EGK- Alguns apontamentos:

https://github.com/NCAR/WPS ::

**ungrib.exe**

- edit namelist.wps for start_date and end_date, output file prefix 
  (&share and &ungrib sections)
- link correct Vtable:
  ls -l ungrib/Variable_Tables
  For example, for NCEP GFS (or AVN, FNL) data,
  ln -sf ungrib/Variable_Tables/Vtable.GFS Vtable
- link grib data files:
  link_grib.csh /data-directory/file*
- type 'ungrib.exe >& ungrib.out' to run
- check output in ungrib.log and ungrib.out

https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compilation_tutorial.php ::

wget https://ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.20230201/00/atmos/gfs.t00z.pgrb2.0p25.f000

/oper/dados/ioper/tempo/GFS/0p25/brutos/2024/01/01/00

gfs.t00z.pgrb2.0p25.anl.2024010100.grib2
gfs.t00z.pgrb2.0p25.f000.2024010100.grib2 ...

/oper/dados/ioper/tempo/NCEP/input/2024/01/01/00

gblav.T00Z.atmanl.netcdf.2024010100 ...

wget https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.$1$2$3/00/atmos/gfs.t00z.pgrb2.0p25.f000
mv gfs.t00z.pgrb2.0p25.f000 $4/gfs.t00z.pgrb2.0p25.f000.$1$2$3.grib2

- Modificado o script 2 de modo a ter como entrada o nome do experimento (GFS), a resolução (1024002- 24km) e a data (por exemplo, 2024010100)
- Condição inicial proveniente da operação com datas disponíveis a partir de dezembro/2023
- Scripts 3 e 4 incorporados em run_monan_gnu.egeon, assim como a cópia da condição inicial da operação (link simbólico não funciona numa submissão de job se a CI original está no diretório da operação -rw-r-r, funciona localmente sem submeter pros nós de processamento)
- Reestruturação do passo a passo pensando na utilização do ecflow
- Idéia de quebrar os scripts de modo mais estratégico

-  Movidas as variáveis de ambiente comuns dos scripts para load_monan_app_modules.sh
- Removidas variáveis de ambiente desnecessárias
- Incluída a variável de entrada FCST (número de horas de previsão) do script 2: facilitou a checagem se a rodada do modelo ocorreu com sucesso
- Inclusão do cálculo da data final após 24 horas de previsão para checar as saídas do modelo (data contida no nome do arquivo diag*.nc
- Movida a checagem das saídas do modelo de monan_exe.sh para o script 2
- 
- Incluída uma checagem se o passo static já foi feito de modo a não repetir o procedimento para datas iguais;
- Movida a cópia e descompressão dos dados e testcase para o script 1 (de compilação);
- Incluída a resolução RES no script run_monan_gnu.egeon para permitir rodar em 10km (estava fixo em 24km); 
-
- Instalado na conta monan o pacote MONAN-scripts/egeon_oper e testado
- 
- próximos passos: usar sed para incluir FCST no namelist.atmosphere (config_run_duration = '0_24:00:00'); checar criação de pastas e links simbólicos no script 2  (ou criar um script de configuração da rodada diária);  copiar dados que permitem rodar o testcase com diferentes números de processadores em 10km para o arquivos de dados; incluir dados do GFS de t00z, t06z, t12z, t18z; checar chegada do dado e colocar o script 2 no cron; estabelecer quais variáveis que serão pós-processadas e incluí-las apropriadamente; colocar o script 2 no ecflow.
-
- Padrões operacionais no NCEP:
- https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf
- Informações sobre o ecflow:
- https://confluence.ecmwf.int/display/ECFLOW/ecFlow@ECMWF
- https://confluence.ecmwf.int/display/ECFLOW/Documentation
- https://confluence.ecmwf.int/display/ECFLOW/Ecflow+User+Manual
- https://github.com/morianemo/debian-ecflow/blob/master/notebook/ecFlow.ipynb
- https://github.com/ecmwf/ecflow
- 

### Denis - Adaptação do pós na pasta egeon_oper
- Modificação dos scripts 2.pre_monan.bash, run_monan_egeon.bash e principalmente no ngridlat2lon.sh, passando os parâmetros data inicial, final e resolução para este poder ser parametrizável com estes parâmetros.
- Validada a rodada do dia 27/01/2024. A figura com previsão de 24h, gerada automaticamente (MONAN.png):

![image](https://github.com/monanadmin/monan/assets/6113640/0542e25c-4903-4816-9e2f-ec990b73580e)

- Validada a rodada do dia 27/01/2024, com previsão de 10 dias:
  - Abriu-se o arquivo surface.nc, assim como no script prec.gs, e plotou-se o acumulado de chuva entre 05/02 e 06/02:
  
![image](https://github.com/monanadmin/monan/assets/6113640/1c8c07d3-7b4d-42ef-8113-06fb5132c34b)

![image](https://github.com/monanadmin/monan/assets/6113640/5ba5468d-cc36-425a-8892-75f73fdf8c3c)

#### Bug fix:
- Correção para evitar sobrescrita de dados e testcase do ftp e scripts da pasta "MONAN_ori/testcase/scripts" (do repositório) na pasta de trabalho "MONAN". Motivo: uma segunda execução sobrescrevia dados alterados pelo usuário na pasta MONAN

#### Melhorias
- arquivos da pasta testcase/scripts do ftp movidos completamente para pasta MONAN_ori/testcase/scripts
- Fix no número da versão atual: 0.2.2 no script 2.
- Criada a pasta e arquivos com a versão 0.2.2 no ftp, para contemplar a mudança no script.

**[João] CRON**

Script do Cron: /mnt/beegfs/monan/cronmonan/rmonancron.sh
Crontab: (Todo dia as 8h - configurado no egeon-login)
0 8 * * * /mnt/beegfs/monan/cronmonan/rmonancron.sh > /mnt/beegfs/monan/cronmonan/rmonancron-08h.log 2>&1
Resultados foram inseridos nos comentários (2 testes realizados com sucesso).

## :rotating_light: Problemas encontrados

_(... problemas técnicos reais apresentados durante a execução das atividades)_

## :white_check_mark: Conclusão

- Testes automatizados com rodadas diárias pelo cron da conta monan foram realizados com sucesso desde o uso de dados diários do GFS até o pós processamento. O passo a passo do processo todo será aos poucos implementado no ambiente do ecflow.  

## :spiral_calendar: Trabalhos Futuros

- Implementar o passo a passo no ecflow nos padrões da DIPTC.

**Comment by joaomas** [comment]
Pessoal, já peguei a senha da conta MONAN junto ao Help e já troquei a senha, depois repasso a vocês.

**Comment by joaomas** [comment]
Coloquei no 'crontab' da conta 'monan' na Egeon 4 rodadas (MONAN-Scripts) diárias (0h, 6h, 12h e 18h) para 3 dias de previsão usando 4 nodes e 256 cores. O objetivo é validar a conta na Egeon e sua estabilidade e futuramente substituir pelas rodadas pré-operacionais.

**Comment by joaomas** [comment]
Cron as 8h todo dia.

**Comment by joaomas** [comment]
Consultar documento de requisitos de operação junto ao IO.

**Comment by deniseiras** [comment]
Informações do Pablo

Pablo executou o MPAS com GFS 24Km em /mnt/beegfs/julio.fernandez/MPAS/bench/GFS2/2021060100
à partir desta pasta, foram armazenados seus scripts e namelists principais em:

https://github.com/monanadmin/MONAN_GCC_issues/tree/main/387/from_pablo

**Comment by joaomas** [comment]
**Rodada 24/1/24**

![Image](https://github.com/monanadmin/monan/assets/41485190/859c5093-1519-4f80-8e58-24e8576e308b)

**Rodada** 25/1/24

![Image](https://github.com/monanadmin/monan/assets/41485190/1c60e7c7-4ee7-415e-9254-6188bbfcde59)

**Rodada 26/1/24**

![Image](https://github.com/monanadmin/monan/assets/41485190/edffab7f-32aa-4b5f-829d-c167dd7584ec)
