### ISSUE TITLE
[GCC] GRC: Implementar uma segunda regra (modulo)

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#406]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS retomar o desenvolvimento da ferramenta para Code Review,
PARA iniciar o uso desta ferramenta no processo de revisão do código.

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Implementar uma segunda regra (modulo).
- [x] Executar todos os testes de todas as regras - devem passar

## :pencil: Detalhamento adicional da atividade

Implementar uma regra que teste o código de validação do módulo.
Antes, validar se existe essa regra no DTN e alinhar o código com a regra DTN, ou o contrário (nesse caso validar com o time).

Ver trecho de código comentado no CodeReviewer:
~~~
        # TODO Create Rule
        # points = verify_module_name(points, full_file_name, root)
~~~
Implementado a regra verify_module name.

Arquivos implementados: <https://github.com/GCC-DIMNT-CPTEC/codereviewer/tree/feature/monan-406-NF/src>

## :comet: Impactos

_(... consequência técnica encontrada durante a execução da issue)_

## :link: Dependências

Issue: Implementar o parser e uma regra na ferramenta codereviewer. (https://github.com/monanadmin/monan/issues/368)

## :hammer_and_wrench: Solução

Branch feature/monan-406-NF criada. A regra fora implementada e os testes passaram. 

PS: A ferramenta "Testing" do VSCode foi empregada  para auxiliar nos testes.

## :rotating_light: Problemas encontrados

Os testes precisam ser verificados, pois ocorreram interferências nas regras anteriores. Reinserido arquivo de teste.f90. Renomeado o metodo run_validator para execute _validation e Cocderewier.py e dependencias,  evitando aquivocos com run_validator da classe Validator_xml. Para  melhorar a compreenção de classses foi feito um documento de análise do programa principal Codereviewer.py com considerações sobre os conceitos empregados e judtificativas. 

_(... problemas técnicos reais apresentados durante a execução das atividades)_

## :white_check_mark: Conclusão

A regra foi implementada, e os testes passaram.

## :spiral_calendar: Trabalhos Futuros

-.

**Comment by klclaudio** [comment]
Branch feature/monan-406-NF criada.
