### ISSUE TITLE
Portabilidade: compilar UFS%Egeon@INTEL

### ISSUE THREAD

**Issue by deniseiras** [monanadmin/monan#41]
# Descrição
Compilar o UFS com o compilador intel. Seguir os passos da tarefa 
# Impactos
Não há impactos.

# Dependências
- #47

# Solução

## Solução Final
1) Carregar ambiente intel  
2) Criar Environment 
3) adicionar os compiladores atuais
4) editar o arquivo spack.yaml (equivalente ao compilers, mas do environment nesse caso) para tratar o compilador intel como módulo. 
5) Instalar o ufs reutilizando somente o perl

Isto é:

1) load_spack_env_ufs_intel.sh
```
#!/bin/bash

# Modulos necessarios para compilacao:
module purge
module load intel/2022.0.2
# module load hwloc  - ufs depende
module load python-3.9.13-gcc-9.4.0-moxjnc6
# module load cmake/3.21.3 - é anterior a versão do ufs

# spack unload
SPACK_ROOT_ENV_DIRS=$(pwd)
. $SPACK_ROOT_ENV_DIRS/spack_ufs/share/spack/setup-env.sh

export SPACK_USER_CONFIG_PATH=$SPACK_ROOT_ENV_DIRS/.spack/spack_ufs
export TMP=$SPACK_USER_CONFIG_PATH/tmp
export SPACK_USER_CACHE_PATH=$TMP
export TMPDIR=$TMP

# após criar o environment, esse arquivo pode ser usado para carregar o spack e environment
spack env activate ufs_intel


```
2) create_spack_env_ufs_intel.sh 
```
ENV_INTEL_NAME='ufs_intel'
spack env create $ENV_INTEL_NAME

echo "Faça: spack env activate $ENV_INTEL_NAME"
```
3) `spack compilers find`
4) `vim /mnt/beegfs/denis.eiras/spack/spack_ufs/var/spack/environments/ufs_intel/spack.yaml`
  - Alterando a seção do compilador do intel do arquivo /mnt/beegfs/denis.eiras/spack/spack_ufs/var/spack/environments/ufs_intel/spack.yaml:
```
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: [ufs-weather-model@2.0.0%intel@2021.5.0 ^perl@5.26.3%intel@2021.5.0]
  view: true
  concretizer:
    unify: false
  compilers:
  - compiler:
      spec: dpcpp@2022.0.0
      paths:
        cc: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/icx
        cxx: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/dpcpp
        f77: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/ifx
        fc: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/ifx
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@8.5.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: intel@2021.5.0
      paths:
        cc: icc
        cxx: icpc
        f77: ifort
        fc: ifort
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules:
      - intel/2022.0.2
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: oneapi@2022.0.0
      paths:
        cc: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/icx
        cxx: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/icpx
        f77: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/ifx
        fc: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/ifx
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```
  - para:
```
# inicio alteração
  - compiler:
      spec: intel@2021.5.0
      paths:
        cc: icc
        cxx: icpc
        f77: ifort
        fc: ifort
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules:
      - intel/2022.0.2
      environment: {}
      extra_rpaths: []
# fim alteração
```
5) `spack install --reuse -j 16 ufs-weather-model@2.0.0%intel@2021.5.0 ^perl@5.26.3%intel@2021.5.0`

Essa alteração não gerou o erro com o compilador ifort.

## Tentativas anteriores:
- padrão da issue #43 - spack compiler find (adiciona intel)
  - Erro ao instalar ufs: 
  " Check for working Fortran compiler: /mnt/beegfs/denis.eiras/spack
           /spack_ufs_intel/spack/lib/spack/env/intel/ifort - broken"

- Uso do intel com módulos ( https://spack.readthedocs.io/en/latest/getting_started.html#intel-compilers )
  - instalar GCC - deu mesmo erro do compilador intel:
  " Check for working Fortran compiler: /mnt/beegfs/denis.eiras/spack
           /spack_ufs_intel/spack/lib/spack/env/intel/ifort - broken"

Foi pesquisado e identificado:
- Issue com spack - 2020 - wrapper com erro : https://github.com/spack/spack/issues/2055
- uso de módulos diretamente (https://spack.readthedocs.io/en/latest/getting_started.html#cray-compiler-detection)

Então fez-se a tentativa:
- Criar environment
- module load intel/2020.0.2
- cmake carregado cmake@3.21.3 com spack external find
- spack env create intel
- spack install --reuse -j 16 ufs-weather-model@2.0.0%intel@2021.5.0 ^perl@5.26.3%intel@2021.5.0 ^cmake@3.21.3%intel@2021.5.0 
  deu erro com alguns pacotes e cmake (erro_fortran_compiler.txt na egeon): 
```
  Installing sp-2.3.3-icu75xuuvfkkimifndoy72azkgmifyvg
==> No binary for sp-2.3.3-icu75xuuvfkkimifndoy72azkgmifyvg found: installing from source
==> Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
==> Fetching https://mirror.spack.io/_source-cache/archive/c0/c0d465209e599de3c0193e65671e290e9f422f659f1da928505489a3edeab99f.tar.gz
==> No patches needed for sp
==> sp: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/mnt/beegfs/denis.eiras/spack/spack_ufs/opt/spack/linux-rhel8-zen2/intel-2021.5.0/sp-2.3.3-icu75xuuvfkkimifndoy72azkgmifyvg' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/mnt/beegfs/denis.eiras/spack/spack_ufs/opt/spack/linux-rhel8-zen2/intel-2021.5.0/sp-2.3.3-icu75xuuvfkkimifndoy72azkgmifyvg/lib;/mnt/beegfs/denis.eiras/spack/spack_ufs/opt/spack/linux-rhel8-zen2/intel-2021.5.0/sp-2.3.3-icu75xuuvfkkimifndoy72azkgmifyvg/lib64' '-DCMAKE_PREFIX_PATH:STRING=/opt/ohpc/pub/utils/cmake/3.21.3' '/mnt/beegfs/denis.eiras/spack/.spack/spack_ufs/tmp/spack-stage/spack-stage-sp-2.3.3-icu75xuuvfkkimifndoy72azkgmifyvg/spack-src'

4 errors found in build log:
     2     ==> [2022-06-30-12:28:58.613303] 'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/mnt/beegfs/denis.eiras/spack/spack_ufs/opt/spack/linux-rhel8-zen2/intel-2021.5.0/sp-2.3.3-icu75xuuvf
           kkimifndoy72azkgmifyvg' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_R
           PATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/mnt/beegfs/denis.eiras/spack/spack_ufs/opt/spack/linux-rhel8-zen2/intel-2021.5.0/sp-2.3.3-icu75xuuvfkkimifndoy72azkgmifyvg/lib;/mnt/beeg
           fs/denis.eiras/spack/spack_ufs/opt/spack/linux-rhel8-zen2/intel-2021.5.0/sp-2.3.3-icu75xuuvfkkimifndoy72azkgmifyvg/lib64' '-DCMAKE_PREFIX_PATH:STRING=/opt/ohpc/pub/utils/cmake/3.21.3' '/mnt/beegf
           s/denis.eiras/spack/.spack/spack_ufs/tmp/spack-stage/spack-stage-sp-2.3.3-icu75xuuvfkkimifndoy72azkgmifyvg/spack-src'
     3     -- The Fortran compiler identification is Intel 2021.5.0.20211109
     4     -- Detecting Fortran compiler ABI info
     5     -- Detecting Fortran compiler ABI info - failed
     6     -- Check for working Fortran compiler: /mnt/beegfs/denis.eiras/spack/spack_ufs/lib/spack/env/intel/ifort
     7     -- Check for working Fortran compiler: /mnt/beegfs/denis.eiras/spack/spack_ufs/lib/spack/env/intel/ifort - broken
  >> 8     CMake Error at /opt/ohpc/pub/utils/cmake/3.21.3/share/cmake-3.21/Modules/CMakeTestFortranCompiler.cmake:54 (message):
     9       The Fortran compiler
     10    
     11        "/mnt/beegfs/denis.eiras/spack/spack_ufs/lib/spack/env/intel/ifort"
     12    
     13      is not able to compile a simple test program.
```

Então fez-se outra tentativa usando o cmake do ufs, pois o erro parece partir do cmake e a versão do cmake do ufs (cmake-3.23.1) é maior do que a do ambiente (cmake@3.21.3):
- Criar environment
- module load intel/2020.0.2
- spack env create intel
- spack install --reuse -j 16 ufs-weather-model@2.0.0%intel@2021.5.0 ^perl@5.26.3%intel@2021.5.0

Mas o problema efetivamente estava no compilador intel, então, executou-se a modificação para tratar o compilador como módulo. (Solução final)

Possíveis outras soluções não testadas: 
- não usar environment e alterar o compilers.yaml usando módulo, como acima
- não usar environment e alterar o compilers.yaml sem usar módulo, mas alteando o paths:

## Problemas encontrados
Não há.

**Comment by egkhamis** [comment]
Ao compilar a biblioteca paralell-netcdf pelo spack com o compilador intel, , o seguinte erro ocorre:
configure:5098: checking for C compiler version
configure:5107: /opt/ohpc/pub/mpi/openmpi4-intel/4.1.1/bin/mpicc --version >&5
/opt/ohpc/pub/mpi/openmpi4-intel/4.1.1/bin/mpicc: error while loading shared libraries: libimf.so: cannot open shared object file: No suc
h file or directory

O mesmo nao acontece com a versao 2019.1.3 do compilador intel na Rattler.

**Comment by egkhamis** [comment]
Denis, o UFS pede na compilacao com o spack o openmpi. Os testes que fiz com impi falharam.
