### ISSUE TITLE
[GCC] PAD: SST e US - modificar o script para atender leitura da SST na CI e Umidade do Solo (US)

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#417]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS iniciar o processo de testes contínuos do MONAN-MPAS começando pelas condições iniciais,
PARA melhor avaliação do modelo e uso do Egeon.

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Modificar o script para atender leitura da SST na CI e Umidade do Solo (US).

## :pencil: Detalhamento adicional da atividade

_(... espaço para detalhar melhor o que deve ser realizado)_

## :comet: Impactos

_(... consequência técnica encontrada durante a execução da issue)_

## :link: Dependências

_(... issues e requisitos que devem ser executados previamente)_

## :hammer_and_wrench: Solução

- EGK: Foi difícil encontrar a variável de SST/SKINTEMP no arquivo GFS original do NCEP/operação_Egeon, entretanto, após o link com a Vtable.GFS e o ungrib.exe, podemos utilizar, por exemplo, utilitários como rd_intermediate.exe (lê e lista os campos encontrados no arquivo intermediário após o ungrib.exe) ou int2nc.exe (cria um netcdf a partir desse arquivo intermediário) onde podemos utilizar ncdump/ncview com a saída em netcdf. Ambos utilitários vem da compilação do WPS.
- Identificadas na saída do "re_intermediate.exe GFS:2024-01-01_00" as variáveis:
================================================
FIELD = SKINTEMP
UNITS = K DESCRIPTION = Skin temperature
DATE = 2024-01-01_00:00:00 FCST = 0.000000
SOURCE = NCEP GFS Analysis
LEVEL = 200100.000000
I,J DIMS = 1440, 721
IPROJ = 0  PROJECTION = LAT LON
  REF_X, REF_Y = 1.000000, 1.000000
  REF_LAT, REF_LON = 90.000000, 0.000000
  DLAT, DLON = -0.250000, 0.250000
  EARTH_RADIUS = 6371.229492
DATA(1,1)=243.663040

================================================
FIELD = SM000010
UNITS = fraction DESCRIPTION = Soil Moist 0-10 cm below grn layer (Up)
DATE = 2024-01-01_00:00:00 FCST = 0.000000
SOURCE = NCEP GFS Analysis
LEVEL = 200100.000000
I,J DIMS = 1440, 721
IPROJ = 0  PROJECTION = LAT LON
  REF_X, REF_Y = 1.000000, 1.000000
  REF_LAT, REF_LON = 90.000000, 0.000000
  DLAT, DLON = -0.250000, 0.250000
  EARTH_RADIUS = 6371.229492
DATA(1,1)=0.000000

================================================
FIELD = SM010040
UNITS = fraction DESCRIPTION = Soil Moist 10-40 cm below grn layer
DATE = 2024-01-01_00:00:00 FCST = 0.000000
SOURCE = NCEP GFS Analysis
LEVEL = 200100.000000
I,J DIMS = 1440, 721
IPROJ = 0  PROJECTION = LAT LON
  REF_X, REF_Y = 1.000000, 1.000000
  REF_LAT, REF_LON = 90.000000, 0.000000
  DLAT, DLON = -0.250000, 0.250000
  EARTH_RADIUS = 6371.229492
DATA(1,1)=0.000000

================================================
FIELD = SM040100
UNITS = fraction DESCRIPTION = Soil Moist 40-100 cm below grn layer
DATE = 2024-01-01_00:00:00 FCST = 0.000000
SOURCE = NCEP GFS Analysis
LEVEL = 200100.000000
I,J DIMS = 1440, 721
IPROJ = 0  PROJECTION = LAT LON
  REF_X, REF_Y = 1.000000, 1.000000
  REF_LAT, REF_LON = 90.000000, 0.000000
  DLAT, DLON = -0.250000, 0.250000
  EARTH_RADIUS = 6371.229492
DATA(1,1)=0.000000

================================================
FIELD = SM100200
UNITS = fraction DESCRIPTION = Soil Moist 100-200 cm below gr layer
DATE = 2024-01-01_00:00:00 FCST = 0.000000
SOURCE = NCEP GFS Analysis
LEVEL = 200100.000000
I,J DIMS = 1440, 721
IPROJ = 0  PROJECTION = LAT LON
  REF_X, REF_Y = 1.000000, 1.000000
  REF_LAT, REF_LON = 90.000000, 0.000000
  DLAT, DLON = -0.250000, 0.250000
  EARTH_RADIUS = 6371.229492
DATA(1,1)=0.000000

- Saída da SST pelo ncview:

![Image](https://github.com/monanadmin/monan/assets/98923325/eb52ca04-6e4d-46cd-995c-2c5d50900480)

-Saída da umidade do solo (1a camada):

![Image](https://github.com/monanadmin/monan/assets/98923325/c475f92b-8c88-44b5-a879-1133d93c1367)

- Informações sobre o formato do arquivo intermediário [fontes: https://www2.mmm.ucar.edu/wrf/OnLineTutorial/Basics/IM_files/index.php ,
https://www2.mmm.ucar.edu/wrf/OnLineTutorial/Basics/IM_files/IM_wps.php]:

"Fields are written to the intermediate files as 2–dimensional horizontal slabs of data. Each horizontal slab contains a single level of a single variable (i.e., 500 mb RH, surface T, etc.). Any number of horizontal slabs may be written to a single file. The slabs in a given file are not necessarily all from the same data source, or all on the same grid or map projection, but they should all represent the data valid at the same time.

Each file contains data for a single time. The file names consist of a prefex (ideally, but not necessarily, denoting the source of data), followed by a colon, followed by a time–stamp in the form YYYY–MM–DD_HH.

The files are written as unformatted FORTRAN records. For each horizontal data slab a number of records are written. The number of records depends on the intermediate file version. Typical information in these records is:

– A version number
– Information common to all types of gridded data
– Information specific to the particular grid type represented
– A 2–dimensional slab of data
The intermediate file format was originally developed for the MM5 model. Due to its easy use, this file format has been passed on to the WRF modeling system. To fulfill extra requirements, various versions of this format are currently in use. The WPS package can read all the different versions, so users with older intermediate file formats can still use this data as input to the WPS. A switch in the namelist.wps file (out_format) gives users control over the version they are using as input."

## :rotating_light: Problemas encontrados

N.A.

## :white_check_mark: Conclusão

Não há necessidade de modificar os scripts pois os dados de SST e umidade do solo já se encontram no arquivo gfs.t00z.pgrb2.0p25.f000.2024010100.grib2, também não é necessária a atualização periódica desses campos para 10 dias de previsão.

## :spiral_calendar: Trabalhos Futuros

_(... caso a issue demande trabalhos futuros detalhar aqui e marcar o campo "Future Work" ao lado para "Sim")_

**Comment by egkhamis** [comment]
Arquivos gerados para verificação:


[intermediateGFS.txt](https://github.com/monanadmin/monan/files/14125841/intermediateGFS.txt)



[ncdump_GFS.txt](https://github.com/monanadmin/monan/files/14125832/ncdump_GFS.txt)
