### ISSUE TITLE
[GCC] PAD: Configurar as variaveis repassadas ao GCC

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#433]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS iniciar o processo de testes contínuos do MONAN-MPAS,
PARA melhor avaliação do modelo e uso do Egeon.

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Configurar a saída com as variáveis da tabela repassada ao GCC (https://docs.google.com/document/d/1cEo6c8gDUdWnIAFImAZMLLvfwj_5Na2krhrMmWoW-S8/edit?pli=1),  versão "testes continuos - 418" com todos os níveis do MPAS.
- [x] Verificar se as variáveis aparecessem na saída.
- [X] Finalizar a feature "egeon-oper".
- [X] Fazer o merge com a devolep.
- [X] Criar uma nova feature.

## :pencil: Detalhamento adicional da atividade

N/A

## :comet: Impactos

N/A

## :link: Dependências

N/A

## :hammer_and_wrench: Solução

- Finalizada a feature 387.
- Feito o merge com a devolep.
- Criada uma nova feature 433
- Incluídas em Registry.xml as variáveis:
```
temperature
uReconstructZonal
uReconstructMeridional
zgrid
relhum
spechum
w
t2m
q2
u10
v10
hfx
lh
rainc
rainnc
hpbl
sst
aclwdnb
aclwdnbc
aclwdnt
aclwdntc
aclwupb
aclwupbc
aclwupt
aclwuptc
acswdnb
acswdnbc
acswdnt
acswdntc
acswupb
acswupbc
acswupt
acswuptc
cd
ch
chs
cldfrac
delta
kzh
kzm
kzq
rublten
rvblten
rqvblten
rucuten
rvcuten
rqvcuten
rthratenlw
rthratensw
scalars
acsnow
```
onde o array _scalars_ consiste das variáveis abaixo:
```
qv
qc
qr
qi
qs
qg
ni
nr
```
- Código compilado e executado para testar a inclusão das variáveis.

- Passo a passo para as alterações:

```
$ git clone git clone https://github.com/monanadmin/MONAN-scripts
$ git checkout feature/monanscripts-433-QI
```
- na pasta namelist: foi adicionado o novo arquivo Registry.xml.atm que será copiado no lugar de Registry.xml em egeon_oper/MONAN_src/MONAN-Model_v0.1.0_egeon.gnu940/src/core_atmosphere/
(isso foi feito no script 1.install_monan.bash), adicionada a lista de variáveis em stream_list.atmosphere.diagnostics e removidas diversas variáveis de stream_list.atmosphere.output (referente a saída de history)

- na pasta scripts: foi incluída a lista de variáveis no arquivo include_fields.diag e removidas variáveis de include_fields.history para diminuir o tempo de pós processamento:

```
$ git add (dos arquivos modificados)
$ git commit -m "..."
$ git push
$ git flow init
```

- Com o comando _git flow init_ foi escolhida a feature/monanscripts-433-QI conforme figura abaixo:

![Image](https://github.com/monanadmin/monan/assets/98923325/372382b9-766a-45e7-9275-d60f77fac109)

- Em seguida foi fechada a branch:
```
$ git flow feature finish feature/monanscripts-433-QI
```
![Image](https://github.com/monanadmin/monan/assets/98923325/af232fc1-ff47-462b-b3e4-2e9e71034d75)

- E depois foi atualizado o merge na branch develop:
```
$ git push
```

![Image](https://github.com/monanadmin/monan/assets/98923325/af0c1159-43a5-4409-9d4c-1fbadc786138)

- Voltou-se a branch feature/monanscripts-433-QI para fechá-la utilizando o procedimento a seguir:
```
$ git checkout feature/monanscripts-433-QI
$ git branch -m feature/monanscripts-433-QI feature/monanscripts-433-QI_CLOSED
$ git push origin --delete feature/monanscripts-433-QI
$ git push origin -u feature/monanscripts-433-QI_CLOSED
```

- Foi checado que todas as variáveis aparecem na saída após o pós processamento com o _convert_mpas_. Duas delas não apareceram (nr, ni) por fazerem parte da rotina de _thompson_ que não foi utilizada na configuração da rodada do modelo. Uma das varáveis, qv, é checada com _nview surface.nc_ conforme a figura abaixo:

![Image](https://github.com/monanadmin/monan/assets/98923325/6ef962e3-ab5b-46a8-8176-17f5b46de039)

- Foi atualizado na conta monan o repositório Monan-scripts que aponta para a branch develop com o comando _git pull_ de modo a atualizar as novas configurações para os testes contínuos. 

- Código recompilado do MONAN em MONAN-Scripts da conta monan. 

## :rotating_light: Problemas encontrados

- Tamanho dos arquivos pós processados surface.nc e mean.nc, cada um com  639G.
- Espaço em disco de todas as saídas diag (5.4 G): 1.3T.
- Tempo elevado do pós processamento, necessidade de utilização do aplicativo _cdo_.

## :white_check_mark: Conclusão

- Configurada a inclusão de variáveis para  constarem nas saídas diag*.nc do modelo.
- Verificou-se que as variáveis aparecem nas saídas do modelo após o pós processamento com o _convert_mpas_.
- Feita atualização dos testes contínuos na conta monan.

## :spiral_calendar: Trabalhos Futuros

- Compactar saídas diag;
- Realizar pós processamento na América do Sul para reduzir tamanho dos arquivos pós processados (já está configurado assim);
- Diminuir o número de variáveis para o pós processamento;
- Incluir um maior número de níveis intermediários para as variáveis adicionadas (possibilidade de utilizar o MPASSIT, que já inclui esses níveis e tem processamento paralelo, para o pós processamento dessas variáveis num recorte da América do Sul);
- Checar outras possibilidades de realizar o pós processamento;
- Incluir nos logs dos testes contínuos a versão do repositório MONAN-scripts . Por exemplo, informação do último commit: "git log | head -1" (Sugestão para o Carlos Renato).

**Comment by deniseiras** [comment]
Criada a planilha https://docs.google.com/document/d/1lGM7O9xc9Iqf6H4LUtvENC5h1bTW89lW0HlsCrtVvyk/edit?usp=sharing para fazer testes com algumas variáveis.

**Comment by deniseiras** [comment]
## Feito testes com 3h de previsão. 

### Variáveis

include_fields.diag:
- variváveis temperature_**hPa

include_fields.history:
- Variaveis u, v e zgrid

### Saídas geradas:

history.2024-01-01_03.00.00.nc
- 03h, 06h e 09h - **ERRADO - remover?**
- Variaveis u, v (55 níveis) e zgrid (56 níveis)

wind+pw_sfc.nc
 - 00 e 03h
 - Variaveis u, v (55 níveis) e zgrid (56 níveis)

Vento: todos níveis e tempos:
![image](https://github.com/monanadmin/monan/assets/6113640/e2139136-91cd-4998-8626-2d6cba3a4cbb)


zgrid: 1 tempo com 56 níveis
![image](https://github.com/monanadmin/monan/assets/6113640/d52269dc-7f0b-41f3-90c2-bb1960ea825c)


surface.nc
- variváveis temperature_**hPa
- 00h, 01h e 03h
![image](https://github.com/monanadmin/monan/assets/6113640/bda9f31a-daeb-464f-a293-1883bba6714b)
