### ISSUE TITLE
[GCC] PAD: Investigar modificação no código para alteração dos níveis verticais com o Kubota (SPIKE)

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#434]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS iniciar o processo de testes contínuos do MONAN-MPAS,
PARA melhor avaliação do modelo e uso do Egeon.

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Investigar modificação no código para alteração dos níveis verticais com o Kubota (SPIKE)

## :pencil: Detalhamento adicional da atividade

N/A

## :comet: Impactos

N/A

## :link: Dependências

N/A

## :hammer_and_wrench: Solução

- Algumas modificações realizadas pelo Kubota:

```
Em physics/mpas_atmphys_driver_convection.F
linha 1090 está multiplicando por dt que corrige as dimensões de rainc:

!update the accumulated precipitation at the end of each dynamic time-step:
 do i = its, ite
    rainc(i) = rainc(i) + cuprec(i) * dt_dyn
.
.
.

Criado template do Registry para adicionar as variáveis da física Registry_physics.xml (ou nome semelhante,
adicionado no final do arquivo diagnostics/Registry_isobaric.xml)

Em namelist.atmosphere.TEMPLATE, alterada a variável abaixo:
config_bucket_update = '01:00:00'    (estava none) agora acumula as variáveis da física: radiação, etc..
Porem, foi necessário alterar o código para zerar as variáveis e corrigir a soma acumulada que vão somando 
sem limite.

Algumas variáveis estão com erro de unidades: uma delas multiplica por dt de modo errado.

Necessário criar dt1 e dt2 para saber a diferença entre tempos, porém, perde-se a soma total final que deve 
ser implementada à parte

Em physics/mpas_atmphys_update.F
linha 160 radiação multiplicando errado todas as variáveis por dt: acswdnb, acswdnbc, etc..
a unidade das variáveis ficam erradas:

         do iCell = its, ite
    !short-wave radiation:
    acswdnb(iCell)  = acswdnb (iCell) + swdnb (iCell)*dt_dyn
    acswdnbc(iCell) = acswdnbc(iCell) + swdnbc(iCell)*dt_dyn
.
.
.

Em diagnostics/mpas_isobaric_diagnostics.F
linha 1005, subrotina que faz a interpolação vertical em níveis de pressão. Utilizar essa rotina
para interpolar em níveis arbitrários:

subroutine interp_tofixed_pressure(ncol,nlev_in,nlev_out,pres_in,field_in,pres_out,field_out)

Também foram feiras modificações no pacote convert_mpas.

```

- Para modificar o código e alterar os níveis verticais, deve-se seguir procedimento conforme detalhado em #427, porém, adequando as variáveis já existentes e os _drivers_ respectivos da física.

- Disponibilizar fork do MONAN com modificações do código realizadas pelo Kubota.

- Disponibilizado fork do MPASSIT com modificações para compilar e rodar o pacote na Egeon. O procedimento encontra-se a seguir.

- Compiling MPASSIT code at Egeon:

``` 
$ git clone https://github.com/egkhamis/MPASSIT
$ cd MPASSIT/run
$ source load_modules.sh
$ ./compile.sh
``` 

- Running MPASSIT:
```
$ ./run.sh
``` 

- Checking results:
```
$ nvciew monan/out_hist_diag.nc
``` 

## :rotating_light: Problemas encontrados

N/A

## :white_check_mark: Conclusão

- Foram Investigadas modificações no código para alteração dos níveis verticais junto ao Kubota que já tem trabalho em andamento.
- Foi disponibilizado fork do MPASSIT com instruções de compilação e execução na Egeon. 
- Ficamos no aguardo de um fork do MONAN com as modificações do Kubota.

## :spiral_calendar: Trabalhos Futuros

- Estabelecer conduta ou melhor forma de colaboração entre grupos. (SM: Inserido na Retrospectiva)

**Comment by egkhamis** [comment]
- Computing new diagnostic fields in MPAS-Atmosphere simulations: https://www2.mmm.ucar.edu/projects/mpas/tutorial/Virtual2023/lectures/Diagnostics.pdf
