### ISSUE TITLE
[GCC] PAD: Alterar MPAS para incluir os niveis solicitados

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#438]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS Alterar o código do MPAS,
PARA Incluir as variáveis com os níveis solicitados.

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Código alterado para atender aos níveis solicitados.
- [x] Documentar as variáveis e níveis alterados nesta issue e nas anteriores em https://docs.google.com/document/d/1lGM7O9xc9Iqf6H4LUtvENC5h1bTW89lW0HlsCrtVvyk/edit?usp=sharing

## :pencil: Detalhamento adicional da atividade

Alterar o código fortran e arquivos do tipo Registry.XML para substituir os atuais níveis de pressão pelos níveis definidos no documento https://docs.google.com/document/d/1lGM7O9xc9Iqf6H4LUtvENC5h1bTW89lW0HlsCrtVvyk/edit?usp=sharing .

## :comet: Impactos

N.A.

## :link: Dependências

N.A.

## :hammer_and_wrench: Solução

- Passo a passo para introduzir uma variável (no exemplo, a variável u_zonal) resumidos no commit abaixo:

[commit.txt](https://github.com/monanadmin/monan/files/14524821/commit.txt)

Variáveis com nimplementações de níveis já existentes (oito) foram implementadas com 15 níveis

As variáveis que tiveram seus níveis alterados estão marcadas na documentação na primeira coluna . Ex: Temperatura DME - done

Das variáveis sem saída:
- geopotencial foi implementado
- nr, ni, ch - ainda falta implementar

branch feature/monan-438_439-NF finalizada e integrada a develop, seguindo DTN06.

## :rotating_light: Problemas encontrados

N.A.

## :white_check_mark: Conclusão

Níveis implementados nas variáveis com níveis existentes, e uma variável implementada por completo.

## :spiral_calendar: Trabalhos Futuros

Implementar variáveis com saídas em 55 níveis em 17 níveis. Ou fazer no pós processamento a ser desenvolvido.

**Comment by egkhamis** [comment]
@deniseiras lembrar de fazer o push da develop local do MONAN-Model (máquina que está no INPE) para o remoto

**Comment by joaomas** [comment]
Em trabalhos futuros já é o pedido do cliente de forma macro (épico).
