### ISSUE TITLE
[GCC] GRC: Testar CD_CT

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#445]
## :people_holding_hands: User Story

COMO GCC,
QUEREMOS Testar os scripts do CD_CT,
PARA Contribuir com a melhoria da qualidade da entrega do script.

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Testar CD_CT e reportar resultados ao time.

## :pencil: Detalhamento adicional da atividade

- Seguir as instruções no README do repostiório https://github.com/monanadmin/scripts_CD-CT/tree/develop

## :comet: Impactos

-.

## :link: Dependências

-.

## :hammer_and_wrench: Solução

$ git clone https://github.com/monanadmin/scripts_CD-CT.git

**NOTA TEST**  Adicionaria no README -> $ git checkout develop && cd scripts após o git clone.

$ ./1.install_monan.bash https://github.com/joaomas/MONAN-Model-JMAS

$ ./2.pre_processing.bash GFS 1024002 2024010100 24

**NOTA TEST** O script esta com default para 16 nodes e 1024 cores, ajustado para 4 nodes e 256 cores, foi alterado o "scripts_CD-CT/scripts/setenv.bash" para ter recurso na maquina.

**NOTA TEST** Para otimizar os testes foi necessário ajustar a rodada apenas para 2 horas, editado namelist em "scripts_CD-CT/namelists/namelist.atmosphere.TEMPLATE".

$ ./3.run_model.bash GFS 1024002 2024010100 24

$ ./4.run_post.bash GFS 1024002 2024010100 24

$ ./5.run_products.bash GFS 1024002 2024010100 24

Saídas (dataout):

dataout/2024010100:
total 2.0K
drwxrwsr-x 3 joao.messias joao.messias 3 Mar 14 15:12 Pre
drwxrwsr-x 3 joao.messias joao.messias 5 Mar 14 18:48 Model
drwxrwsr-x 3 joao.messias joao.messias 3 Mar 14 18:51 Post
drwxrwsr-x 3 joao.messias joao.messias 2 Mar 14 18:53 Prods

dataout/2024010100/Pre:
total 9.3G
-rw-rw-r-- 1 joao.messias joao.messias 781M Mar 14 15:10 GFS:2024-01-01_00
-rw-rw-r-- 1 joao.messias joao.messias 8.5G Mar 14 15:12 x1.1024002.init.nc
drwxrwsr-x 2 joao.messias joao.messias    9 Mar 14 15:12 logs

dataout/2024010100/Pre/logs:
total 79K
-rw-rw-r-- 1 joao.messias joao.messias  256 Mar 14 15:10 namelist.2024-01-01_00:00:00.wps
-rw-rw-r-- 1 joao.messias joao.messias  30K Mar 14 15:10 ungrib.2024-01-01_00:00:00.log
-rw-rw-r-- 1 joao.messias joao.messias  26K Mar 14 15:10 debrib.o338798
-rw-rw-r-- 1 joao.messias joao.messias  100 Mar 14 15:10 debrib.e338798
-rw-rw-r-- 1 joao.messias joao.messias  669 Mar 14 15:11 streams.init_atmosphere
-rw-rw-r-- 1 joao.messias joao.messias 1.3K Mar 14 15:11 namelist.init_atmosphere
-rw-rw-r-- 1 joao.messias joao.messias  15K Mar 14 15:12 log.init_atmosphere.0000.x1.1024002.init.nc.2024010100.out
-rw-rw-r-- 1 joao.messias joao.messias  369 Mar 14 15:12 initatmos.bash.o338799
-rw-rw-r-- 1 joao.messias joao.messias 3.2K Mar 14 15:12 initatmos.bash.e338799

dataout/2024010100/Model:
total 12G
-rw-rw-r-- 1 joao.messias joao.messias  11G Mar 14 18:47 history.2024-01-01_00.00.00.nc
-rw-rw-r-- 1 joao.messias joao.messias 430M Mar 14 18:47 diag.2024-01-01_00.00.00.nc
-rw-rw-r-- 1 joao.messias joao.messias 430M Mar 14 18:48 diag.2024-01-01_01.00.00.nc
-rw-rw-r-- 1 joao.messias joao.messias 430M Mar 14 18:48 diag.2024-01-01_02.00.00.nc
drwxrwsr-x 2 joao.messias joao.messias   12 Mar 14 18:48 logs

dataout/2024010100/Model/logs:
total 72K
-rw-rw-r-- 1 joao.messias joao.messias  340 Mar 14 15:29 model.bash.o338801
-rw-rw-r-- 1 joao.messias joao.messias  232 Mar 14 16:15 model.bash.e338801
-rw-rw-r-- 1 joao.messias joao.messias  340 Mar 14 16:18 model.bash.o338804
-rw-rw-r-- 1 joao.messias joao.messias  232 Mar 14 17:13 model.bash.e338804
-rwxrwxr-x 1 joao.messias joao.messias 1.3K Mar 14 18:46 streams.atmosphere
-rwxrwxr-x 1 joao.messias joao.messias    9 Mar 14 18:46 stream_list.atmosphere.surface
-rwxrwxr-x 1 joao.messias joao.messias  907 Mar 14 18:46 stream_list.atmosphere.output
-rwxrwxr-x 1 joao.messias joao.messias 1.2K Mar 14 18:46 stream_list.atmosphere.diagnostics
-rw-rw-r-- 1 joao.messias joao.messias 1.8K Mar 14 18:46 namelist.atmosphere
-rw-rw-r-- 1 joao.messias joao.messias  38K Mar 14 18:48 log.atmosphere.0000.out
-rw-rw-r-- 1 joao.messias joao.messias  369 Mar 14 18:48 model.bash.o338840
-rw-rw-r-- 1 joao.messias joao.messias  25K Mar 14 18:48 model.bash.e338840

dataout/2024010100/Post:
total 27M
-rwxrwxr-x 1 joao.messias joao.messias  72 Mar 14 18:51 include_fields
drwxrwsr-x 2 joao.messias joao.messias   2 Mar 14 18:51 logs
-rw-rw-r-- 1 joao.messias joao.messias 27M Mar 14 18:51 surface.nc

dataout/2024010100/Post/logs:
total 5.5K
-rw-rw-r-- 1 joao.messias joao.messias  687 Mar 14 18:51 post.bash.o338841
-rw-rw-r-- 1 joao.messias joao.messias 4.4K Mar 14 18:51 post.bash.e338841

dataout/2024010100/Prods:
total 12K
drwxrwsr-x 2 joao.messias joao.messias   2 Mar 14 18:53 logs
-rw-rw-r-- 1 joao.messias joao.messias 12K Mar 14 18:53 MONAN.png

dataout/2024010100/Prods/logs:
total 2.5K
-rw-rw-r-- 1 joao.messias joao.messias 1.6K Mar 14 18:53 prods.bash.o338842
-rw-rw-r-- 1 joao.messias joao.messias   42 Mar 14 18:53 prods.bash.e338842

## :rotating_light: Problemas encontrados

- O parâmetro 'FCST' não funciona na prática, ele não altera o namelist como 'LABELI' faz.

- Msg de erro no 2.pré: 
 
date: invalid date ' :00 24 hours'

Mesmo com a msg passou.

- Rodar o pós com data diferente do run erro (evidentemente).

- Execução do pré com datas muito antigas erro.

## :white_check_mark: Conclusão

- Teste realizado.
- Foi necessário personalizar o numeros de nodes/cpu e o namelist para rodada mais curta devido a disponibilidade do Egeon.
- Dica de melhoria do README em soluções e outros em problemas encontrados.

## :spiral_calendar: Trabalhos Futuros

-.

**Comment by joaomas** [comment]
@carlosrenatosouza2 teste finalizado.

**Comment by carlosrenatosouza2** [comment]
O erro do item "date: invalid date ' :00 24 hours'" é importante sim, é por isso que não funcionou para outras datas.
Quando fui aplicar as mods da #443 eu me deparei com esse erro e ja o corrigi na branch, mas é preciso corrigir isso ASAP na develop. 
O erro ocooreu por um desvio do próprio editor VSCODE que colocou a variável YYYYMMDDHHi em alguns pontos do script em minusculo (yyyymmddhhi) e o bash não reconheceu. Basta alterar tudo para caixa alta e este problema está resolvido. 

Necessário criar um bug fix

**Comment by carlosrenatosouza2** [comment]
Sobre a questão dos recursos definidos em 16n para o modelo: isso está definido no script `setenv.bash`, que é versionado, portanto pode ser alterado conforme for melhor e alterar no versionamento. uma vez que usuário baixa os scripts e começa a usar, ele pode alterar sua versão local conforme ele achar necessário.

**Comment by carlosrenatosouza2** [comment]
Pensar numa forma de prover a seguinte situação:

qdo o usuário for executar omodelo pela 2a vez, usará os scripts do diretorio de trabalho, e nao os scripts versionados que criam os scrpts na pasta de trabalho. Problema: o script cria os links necessários para rodar o processo, isso tera q ser refeito numa 2a vez.
