### ISSUE TITLE
GRC: Ferramenta Understand - 1

### ISSUE THREAD

**Issue by klclaudio** [monanadmin/monan#469]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS Testar e investigar o funcionamento da ferramenta Understand
PARA Adiantar o conhecimento de seu funcionamento em futura aquisição.

## :clipboard: Critérios de aceite de conclusão da Issue

Responder os critério de aceite apenas com "Sim" e "Não".
- ~~[] Investigar a ferramenta e gerar um relatório com as impressões. [Sprint 59]~~
- [x] Detalhes de bug indentification
- [x] Detalhes de checagem de regras
- [x] Detalhes de test coverage
- [x] Como pode ser usado (quais regras) na DTN01
- [x] Testar um caso "real" de uso ou se encontrado na documentação não há necessidade do teste "real".
- [x] Verificar existência de APIs
- [x] Verificar dependências de biblioteca e SO's

## :pencil: Detalhamento adicional da atividade

-.

## :comet: Impactos

-.

## :link: Dependências

-.

## :hammer_and_wrench: Solução

O  [Understand](https://scitools.com/) code é uma ferramenta comercial desenvolvida pela SciTools, possui versão free para testes.
"Understanding é uma ferramenta de análise estática focada na compreensão do código-fonte, métricas, e testes de padrões. Ele foi projetado para ajudar a manter e compreender grandes quantidades de código-fonte legado ou recém-criado. Ele fornece uma plataforma cruzada, multilíngue, IDE orientado para manutenção (ambiente de desenvolvimento interativo)."

O Understanding auxilia nas respostas das seguintes perguntas: O que é esta entidade? Onde foi alterado? Onde é referenciado? Quem depende disso? De que depende?

![Image](https://github.com/monanadmin/monan/assets/98035185/b30aa4db-0c37-473f-9bb4-eee79496d309)

**Análise Lógica**

Responder os critério de aceite apenas com "Sim" e "Não".

| Critério de Aceite | SIM | NÃO | OBS |
| --- | --- | --- | --- |
| ~~1. [] Investigar a ferramenta e gerar um relatório com as impressões. [Sprint 59]~~ | - | - | Este critério não se aplica mais |
| 2. Bug Indentification |  |X| |
| 3. Checagem de Regras |X| | Permite inserção de regras via API |
| 4. Test Coverage | |X| |
| 5. Regras DTN01 | |X| Permite inserção de regras via API |
| 6. Teste "real" ou Docs | X | | Encontrado as informações nas documentações |
| 7. Suporte a APIs |X| |
| 8. Verificar dependências de biblioteca e SO's |X| | |

## :rotating_light: Problemas encontrados

-.

## :white_check_mark: Conclusão

- O Understand é um verificador de código estático, que permite também verificação de padróes de codificação, inclusive via APIs e abre possibilidades de interação com os desenvolvedores para novas regras.
- A análise lógica dos critérios foi realizada, um maior detalhamento encontra-se na issue #470 

## :spiral_calendar: Trabalhos Futuros

-.

**Comment by joaomas** [comment]
@klclaudio movi os parágrafos explicativos para a issue #470
