### ISSUE TITLE
[GCC] GCC: Integração - Paiva

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#499]
## :people_holding_hands: User Story

COMO GCC,
QUEREMOS integrar o novo membro ao time,
PARA levar ao conhecimento o funcionamento dos trabalhos no GCC.

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Inclusão e-mail gcc.dimnt
- [x] Inclusão grupo Whatsapp
- [x] Planilha doodle (reunião e férias):
- [x] Agenda GCC Google
- [x] Pasta GCC Drive
- [x] Link da sala de reunião
- [x] Apresentação Scrum GCC
- [x] GitHub: Org. MONANADMIN
- [x] GitHub: Org. GCC-DIMNT
- [x] Leitura superficial dos trabalhos do GCC - Avaliação Core Dinâmico
- [x] Leitura superficial dos trabalhos do GCC - 1° Workshop MONAN
- [x] Leitura superficial dos trabalhos do GCC - DTN01, DTN03 e DTN06
- [x] Rodada teste MONAN usando Script_CD_CT

## :pencil: Detalhamento adicional da atividade

-.

## :comet: Impactos

-.

## :link: Dependências

-.

## :hammer_and_wrench: Solução

$ ssh -YC marcelo.paiva@egeon
$ cd /mnt/beegfs/marcelo.paiva/ (**Sistema de armazenamento mais performático**)
$ mkdir MONAN
$ cd MONAN/
$ git clone https://github.com/monanadmin/scripts_CD-CT.git
$ cd cd scripts_CD-CT/scripts/
$ git branch -a
$ git status
$ git checkout develop
$ git status
$ ./1.install_monan.bash https://github.com/marcelopaivaramos/MONAN-Model_paiva.git
$ ./2.pre_processing.bash GFS 1024002 2024010100 24
$ ./3.run_model.bash GFS 1024002 2024010100 24
$ ./4.run_post.bash GFS 1024002 2024010100 24
$ ./5.run_products.bash GFS 1024002 2024010100 24
$ module load imagemagick-7.0.8-7-gcc-11.2.0-46pk2go
$ display ../dataout/2024010100/Prods/MONAN_PREC_GFS_2024010100_2024010103.00.00.x1024002L55.png

## :rotating_light: Problemas encontrados

First you need to get a fork repository in your github account of a MONAN oficial repo: **https://github.com/monanadmin/monan.git** (link errado)
**The** (Then?) you can install the model in your work directory by running:

## :white_check_mark: Conclusão

- O nome "scripts_CD-CT" poderia fazer referência modelo, por exemplo: monan_v1.0.0 
\monan_v1.0.0
........ README.md
........ datain
........ dataout
........ execs
........ scripts
........ sources

## :spiral_calendar: Trabalhos Futuros

_(... caso a issue demande trabalhos futuros detalhar aqui e marcar o campo "Future Work" ao lado para "Sim")_

**Comment by joaomas** [comment]
@marcelopaivaramos enviado e-mail com alguns links, com isso alguns critérios de aceite já podem ser dados como ok, te explico mais tarde quando falar sobre o GitHub com você.

**Comment by joaomas** [comment]
@marcelopaivaramos 1° Workshop do MONAN as apresentações estão aqui (https://monanadmin.github.io/)
Do GCC especifico são: http://dataserver.cptec.inpe.br/dataserver_dimnt/monan/workshop_2023_10_02e03/GCC%20-%20App%20Estrutura%20de%20Chamadas%20MPAS.pdf e http://dataserver.cptec.inpe.br/dataserver_dimnt/monan/workshop_2023_10_02e03/GCC%20-%20App%20GitHub%20-%20Fork-clone-branch-monan-1.pdf e http://dataserver.cptec.inpe.br/dataserver_dimnt/monan/workshop_2023_10_02e03/MONAN_v.0.2.1_QuickStart.pdf

**Comment by joaomas** [comment]
@marcelopaivaramos 

1 - AVALIAÇÃO COMPUTACIONAL DE NÚCLEOS DINÂMICOS CANDIDATOS PARA O MONAN - http://mtc-m21d.sid.inpe.br/col/sid.inpe.br/mtc-m21d/2023/08.25.12.04/doc/thisInformationItemHomePage.html

2 - DTN-01 - https://docs.google.com/document/d/1vsINH2ozui-LLiBrZbVORI0pONCcI_6nS8_byUcTx3Y/edit

3 - DTN-03 - https://docs.google.com/document/d/1R8dsyUQU9esXD08Z6UfrcCHaO4VdothklZiQ1QkNPEs/edit

4 - DTN-06 - https://docs.google.com/document/d/1gGO4c5s5iDjz3s45aE4PvyWNO3t0DC_g1RNctetEAh8/edit

5 - Apresentações Diversas: https://drive.google.com/drive/u/3/folders/1kQCgQ8qA0N-PYSlfDEhWAfZ7PBd0nywb

**Comment by joaomas** [comment]
@marcelopaivaramos segue o link do repositório do CD_CT para testes na Egeon, este repositório contem um README com o passo a passo para a execução, tente fazer sozinho primeiro e se tiver dificuldade me acione.

Link: https://github.com/monanadmin/scripts_CD-CT/tree/develop

Obrigado.

**Comment by marcelopaivaramos** [comment]
Rodada teste MONAN usando Script_CD_CT:

![Image](https://github.com/monanadmin/monan/assets/26490180/ff600f75-674c-4410-9f14-3f163f0a73f0)
