### ISSUE TITLE
[GCC] PAD: Implementação nova versão do GF - Teste Inicial

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#511]
## :people_holding_hands: User Story

COMO (...)
QUEREMOS (...)
PARA (...)

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Testar (rodada de 4h), sem alterar a parametrização atual é preciso bater binário na saída ou resultao semelhante aprovado pelo Saulo.
- [x] Se não compilar tem que corrigir.

## :pencil: Detalhamento adicional da atividade

- N/A

## :comet: Impactos

- N/A

## :link: Dependências

#509 

## :hammer_and_wrench: Solução

- Após PR realizado, foi realizada  durante o merge a correção de bug reportada na develop.
- Testes feitos com sucesso numa rodada de 4 horas.
- Estatísticas feitas nas saídas pós-processadas das versões 0.6.0 e 1.0.0 (release a ser criado) foram idênticas. Resultados mostrados nos comentários dessa tarefa. Script utilizado encontrado em: https://github.com/gerasimosmichalitsianos/compare_netcdf_or_grib
- Enviados os resultados ao Saulo. 

## :rotating_light: Problemas encontrados

- N/A

## :white_check_mark: Conclusão

- Testes realizados e bug corrigido no PR.

## :spiral_calendar: Trabalhos Futuros

N/A

**Comment by joaomas** [comment]
Dica Paiva.


$ find dir1/ -type f -exec sha256sum {} + > hashes.txt

$ sha256sum -c hashes.txt
dir1/file1.txt: OK
dir1/dir2/dir3/file3.txt: OK
dir1/dir2/file2.txt: OK

$ echo "oi" >> dir1/dir2/file2.txt

$ sha256sum -c hashes.txt
dir1/file1.txt: OK
dir1/dir2/dir3/file3.txt: OK
dir1/dir2/file2.txt: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

**Comment by cfbastarz** [comment]
Olá @egkhamis, segue um script simples (`diff.py`) para fazer a diferença entre dois campos de um arquivo NetCDF utilizando o Xarray e o Cartopy:

```python
#! /usr/bin/env python3

import os
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.pyplot as plt 

bpath = '/mnt/beegfs/eduardo.khamis/issues/511/scripts_CD-CT/dataout/zzz/2024020100.teste.binario'
fname = 'MONAN_DIAG_G_POS_GFS_2024020100.00.00.x1024002L55.nc'

ds1 = xr.open_dataset(os.path.join(str(bpath), 'Post', fname), engine='netcdf4')
ds2 = xr.open_dataset(os.path.join(str(bpath), 'z/Post', fname), engine='netcdf4')

# https://docs.xarray.dev/en/latest/generated/xarray.Dataset.equals.html
print('Datasets are equal: ', ds1.equals(ds2))

# https://docs.xarray.dev/en/stable/generated/xarray.Dataset.identical.html
print('Datasets are identical: ', ds1.identical(ds2))

# Dif. entre uma variável de um dataset e outro (para um tempo e nível específicos)
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_global()

(ds1['zgeo'].isel(time=0, level=0) - ds2['zgeo']).isel(time=0, level=2).plot.contourf(ax=ax, transform=ccrs.PlateCarree())

ax.coastlines()

plt.savefig('zgeo_t0_l0.png')
```

* Uso: `./diff.py`

O resultado é a seguinte figura:

![image](https://github.com/monanadmin/monan/assets/18047029/a9ecb003-00f5-4a44-add5-201478152051)

* **Nota 1:** eu coloquei `level=2` de propósito no `ds2` para forçar aparecer uma diferença.
* **Nota 2:** os métodos `equals` e `identical` podem ser úteis para verificar a consistência entre as dimensões e coordenadas de cada dataset.

**Comment by egkhamis** [comment]
Oi @cfbastarz , muito obrigado! 

Fizemos o PR, vou atualizar tudo e testar o python.

**Comment by cfbastarz** [comment]
@egkhamis , esqueci de comentar sobre o ambiente em que executei esse script:

```
conda create -n xarray_netcdf
conda activate xarray_netcdf
pip install xarray[complete]
pip install cartopy
```

Abraço!

**Comment by joaomas** [comment]
@egkhamis e @marcelopaivaramos 


---
Pre
---

sha256sum 2024060500/Pre/x1.1024002.init.nc
df2695f43a9684738a4984282d1952ca9647290a79573b9ff26152e559706798  2024060500/Pre/x1.1024002.init.nc

sha256sum 2024060500-11h30/Pre/x1.1024002.init.nc
df0dded1b509481760d6f0981b8e02e263a0ed536bc5fc3282fdbcfa9e57ea20  2024060500-11h30/Pre/x1.1024002.init.nc

-----
Model
-----
sha256sum 2024060500/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc 
b559ccd209ac80f86ff73fb247cbe76b80def0d0615bf77ed2060aca8c686c1a  2024060500/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc

sha256sum 2024060500-11h30/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc 
e073222a9bca43b51f65f63f0af936b7e727aae3354cb7847a8952bc874f7f87  2024060500-11h30/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc

----
Post
----
sha256sum 2024060500/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc
53eb75524f80edc0a9f327f5f7ef4ceede1bf850c6b597907803bbdf5dc717d7  2024060500/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc

sha256sum 2024060500-11h30/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc
0fba34204799f6eb5b749224ace9996d17cdbd6c76b5ed2bfadfb25fb7803767  2024060500-11h30/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc

**Comment by joaomas** [comment]
@joaomas e @egkhamis 

Usando comando "cmp" - rodada 11h30 e 20h30 - mesmo GFS e mesma data da analise 05/06

---
Pre
---

cmp 2024060500/Pre/x1.1024002.init.nc 2024060500-11h30/Pre/x1.1024002.init.nc
2024060500/Pre/x1.1024002.init.nc 2024060500-11h30/Pre/x1.1024002.init.nc differ: byte 3337, line 7

-----
Model
-----

cmp 2024060500/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc 2024060500-11h30/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc
2024060500/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc 2024060500-11h30/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc differ: byte 541, line 4

----
Post
----

cmp 2024060500/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc 2024060500-11h30/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc
2024060500/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc 2024060500-11h30/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc differ: byte 12428, line 19

**Comment by egkhamis** [comment]
@cfbastarz , ah, sim, eu consegui rodar o script mas instalei o xarray e cartopy com o conda install -c conda-forge xarray (e cartopy também).

Entretanto, encontrei um script bem completo que faz o diff entre dois arquivos netcdf, e gera estatísticas das variáveis que se repetem nos dois arquivos: média, mínimo, máximo, desvio padrão e correlação. Fiz também a instalação do rioxarray, netCDF4, matplotlib, cftime, cfgrid para usar esse script. Infelizmente está dando um erro no meio da execução e não sei se é bug ou falha na instalação desses pacotes, ou mesmo falta de memória (submeti num nó e o erro foi o mesmo). O erro que talvez seja a falta da palavra chave _global_ no código é o seguinte:

```
Traceback (most recent call last):
  File "/mnt/beegfs/eduardo.khamis/issues/511/scripts_CD-CT/./compare_netcdf_or_grib.py", line 598, in <module>
    main()
  File "/mnt/beegfs/eduardo.khamis/issues/511/scripts_CD-CT/./compare_netcdf_or_grib.py", line 586, in main
    compareNetcdfsOrGribs(netcdf_or_grib_1,netcdf_or_grib_2, plot , outDir)
  File "/mnt/beegfs/eduardo.khamis/issues/511/scripts_CD-CT/./compare_netcdf_or_grib.py", line 414, in compareNetcdfsOrGribs
    valid_locs = np.where((~np.isnan(arr1_1d))&(~np.isnan(arr2_1d)))
UnboundLocalError: local variable 'arr1_1d' referenced before assignment
```
Estou investigando e testando nova instalação do ambiente conda.

Veja o script em: https://github.com/gerasimosmichalitsianos/compare_netcdf_or_grib

Um exemplo da saída da variável w:
```
    MONAN_DIAG_G_POS_GFS_2024020100.00.00.x1024002L55.nc (w) 
      Mean      : -0.0010223837
      Min,      : -1.0604509
      Max.      : 2.2051587
      Std. Dev. : 0.027128834
    MONAN_DIAG_G_POS_GFS_2024020100.00.00.x1024002L55.nc (w) 
      Mean      : -0.0010493156
      Min,      : -1.0604509
      Max.      : 6.2310433
      Std. Dev. : 0.027042756
 
    MONAN_DIAG_G_POS_GFS_2024020100.00.00.x1024002L55.nc (w) 
    MONAN_DIAG_G_POS_GFS_2024020100.00.00.x1024002L55.nc (w) 
      difference number of elements     : 28551600
      difference Mean,Min.,Max.,St. dev : 0.0023486994, 0.0, 6.1408625, 0.0101217525
```
Abraço!

**Comment by egkhamis** [comment]
> [@joaomas](https://github.com/joaomas) e [@egkhamis](https://github.com/egkhamis)
> 
> Usando comando "cmp" - rodada 11h30 e 20h30 - mesmo GFS e mesma data da analise 05/06
> 
> ## Pre
> cmp 2024060500/Pre/x1.1024002.init.nc 2024060500-11h30/Pre/x1.1024002.init.nc 2024060500/Pre/x1.1024002.init.nc 2024060500-11h30/Pre/x1.1024002.init.nc differ: byte 3337, line 7
> 
> ## Model
> cmp 2024060500/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc 2024060500-11h30/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc 2024060500/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc 2024060500-11h30/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc differ: byte 541, line 4
> 
> ## Post
> cmp 2024060500/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc 2024060500-11h30/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc 2024060500/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc 2024060500-11h30/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc differ: byte 12428, line 19

@joaomas , eu cheguei a testar esse comando, mas ele para logo na primeira diferença. Talvez ele tenha uma -flag para mostrar todas as diferenças mas parece que seria preciso fazer um script com uma combinação de flags.

**Comment by egkhamis** [comment]
@cfbastarz , @joaomas , @marcelopaivaramos , usei uma versão anterior do  que funcionou na configuração do conda na minha conta :)

```
git clone https://github.com/gerasimosmichalitsianos/compare_netcdf_or_grib
cd compare_netcdf_or_grib
git checkout 240755aff0f58b56f707f734d80415c66295e292
cd bin
```

Vejam o log da saída:

[comparison_statistics_20240606_121535.txt](https://github.com/user-attachments/files/15645988/comparison_statistics_20240606_121535.txt)

Vou tentar incluir a diferença entre figuras que o @cfbastarz enviou.

**Comment by joaomas** [comment]
> > [@joaomas](https://github.com/joaomas) e [@egkhamis](https://github.com/egkhamis)
> > Usando comando "cmp" - rodada 11h30 e 20h30 - mesmo GFS e mesma data da analise 05/06
> > ## Pre
> > cmp 2024060500/Pre/x1.1024002.init.nc 2024060500-11h30/Pre/x1.1024002.init.nc 2024060500/Pre/x1.1024002.init.nc 2024060500-11h30/Pre/x1.1024002.init.nc differ: byte 3337, line 7
> > ## Model
> > cmp 2024060500/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc 2024060500-11h30/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc 2024060500/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc 2024060500-11h30/Model/MONAN_DIAG_G_MOD_GFS_2024060500_2024060501.00.00.x1024002L55.nc differ: byte 541, line 4
> > ## Post
> > cmp 2024060500/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc 2024060500-11h30/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc 2024060500/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc 2024060500-11h30/Post/MONAN_DIAG_G_POS_GFS_2024060500.00.00.x1024002L55.nc differ: byte 12428, line 19
> 
> [@joaomas](https://github.com/joaomas) e [@marcelopaivaramos](https://github.com/marcelopaivaramos) , eu cheguei a testar o comando cmp, mas ele para logo na primeira diferença. Talvez ele tenha uma -flag para mostrar todas as diferenças mas parece que seria preciso fazer um script com uma combinação de flags.

@egkhamis o curioso é dar diferença, aparentemente no Pré... usei agora o -l - se o pré esta diferente tudo será... convém começar a analise pelo pré então né ?

$ cmp -l 2024060500/Pre/x1.1024002.init.nc 2024060500-11h30/Pre/x1.1024002.init.nc
      3337 165 156
      3338 153  64
      3339 165 155
      3340  63 142
      3341  64 167
      3342 162 156
      3343 144  60
      3344 151  64
      3345 143 160
      3346  63 147
     27201   0 363
     27202   0 354
     27203   0 101
     27204   0 107
     27205   0 363
     27206   0 354
     27207   0 101
     27208   0 107
     27209   0 363
     27210   0 354
     27211   0 101
     27212   0 107
     27213   0 363
     27214   0 354
     27215   0 101
     27216   0 107
     27217   0 363
     27218   0 354
     27219   0 101
     27220   0 107
     27221   0 363
     27222   0 354
     27223   0 101
     27224   0 107
     27225   0 363
     27226   0 354
     27227   0 101
     27228   0 107
     27229   0 363
     27230   0 354
     27231   0 101
     27232   0 107
     27233   0 363
     27234   0 354
     27235   0 101
     27236   0 107
     27237   0 363
     27238   0 354
     27239   0 101
     27240   0 107
     27241   0 363
     27242   0 354
     27243   0 101
     27244   0 107
     27245   0 363
     27246   0 354
     27247   0 101
     27248   0 107
     27249   0 363
     27250   0 354
     27251   0 101
     27252   0 107
     27253   0 363
     27254   0 354
     27255   0 101
     27256   0 107
     27257   0 363
     27258   0 354
     27259   0 101
     27260   0 107
     27261   0 363
     27262   0 354
     27263   0 101
     27264   0 107
     27265   0 363
     27266   0 354
     27267   0 101
     27268   0 107
     27269   0 363
     27270   0 354
     27271   0 101
     27272   0 107
     27273   0 363
     27274   0 354
     27275   0 101
     27276   0 107
     27277   0 363
     27278   0 354
     27279   0 101
     27280   0 107
     27281   0 363
     27282   0 354
     27283   0 101
     27284   0 107
     27285   0 363
     27286   0 354
     27287   0 101
     27288   0 107
     27289   0 363
     27290   0 354
     27291   0 101
     27292   0 107
     27293   0 363
     27294   0 354
     27295   0 101
     27296   0 107
     27297   0 363
     27298   0 354
     27299   0 101
     27300   0 107
     27301   0 363
     27302   0 354
     27303   0 101
     27304   0 107
     27305   0 363
     27306   0 354
     27307   0 101
     27308   0 107
     27309   0 363
     27310   0 354
     27311   0 101
     27312   0 107
     27313   0 363
     27314   0 354
     27315   0 101
     27316   0 107
     27317   0 363
     27318   0 354
     27319   0 101
     27320   0 107
     27321   0 363
     27322   0 354
     27323   0 101
     27324   0 107
     27325   0 363
     27326   0 354
     27327   0 101
     27328   0 107
     27329   0 363
     27330   0 354
     27331   0 101
     27332   0 107
     27333   0 363
     27334   0 354
     27335   0 101
     27336   0 107
     27337   0 363
     27338   0 354
     27339   0 101
     27340   0 107
     27341   0 363
     27342   0 354
     27343   0 101
     27344   0 107
     27345   0 363
     27346   0 354
     27347   0 101
     27348   0 107
     27349   0 363
     27350   0 354
     27351   0 101
     27352   0 107
     27353   0 363
     27354   0 354
     27355   0 101
     27356   0 107
     27357   0 363
     27358   0 354
     27359   0 101
     27360   0 107
     27361   0 363
     27362   0 354
     27363   0 101
     27364   0 107
     27365   0 363
     27366   0 354
     27367   0 101
     27368   0 107
     27369   0 363
     27370   0 354
     27371   0 101
     27372   0 107
     27373   0 363
     27374   0 354
     27375   0 101
     27376   0 107
     27377   0 363
     27378   0 354
     27379   0 101
     27380   0 107
     27381   0 363
     27382   0 354
     27383   0 101
     27384   0 107
     27385   0 363
     27386   0 354
     27387   0 101
     27388   0 107
     27389   0 363
     27390   0 354
     27391   0 101
     27392   0 107
     27393   0 363
     27394   0 354
     27395   0 101
     27396   0 107
     27397   0 363
     27398   0 354
     27399   0 101
     27400   0 107
     27401   0 363
     27402   0 354
     27403   0 101
     27404   0 107
     27405   0 363
     27406   0 354
     27407   0 101
     27408   0 107
     27409   0 363
     27410   0 354
     27411   0 101
     27412   0 107
     27413   0 363
     27414   0 354
     27415   0 101
     27416   0 107
     27417   0 363
     27418   0 354
     27419   0 101
     27420   0 107
     27421   0 363
     27422   0 354
     27423   0 101
     27424   0 107
     27425   0 363
     27426   0 354
     27427   0 101
     27428   0 107
     27429   0 363
     27430   0 354
     27431   0 101
     27432   0 107
     27433   0 363
     27434   0 354
     27435   0 101
     27436   0 107
     27437   0 363
     27438   0 354
     27439   0 101
     27440   0 107
     27441   0 363
     27442   0 354
     27443   0 101
     27444   0 107
     27445   0 363
     27446   0 354
     27447   0 101
     27448   0 107
     27449   0 363
     27450   0 354
     27451   0 101
     27452   0 107
     27453   0 363
     27454   0 354
     27455   0 101
     27456   0 107
     27457   0 363
     27458   0 354
     27459   0 101
     27460   0 107
     27461   0 363
     27462   0 354
     27463   0 101
     27464   0 107
     27465   0 363
     27466   0 354
     27467   0 101
     27468   0 107
     27469   0 363
     27470   0 354
     27471   0 101
     27472   0 107
     27473   0 363
     27474   0 354
     27475   0 101
     27476   0 107
     27477   0 363
     27478   0 354
     27479   0 101
     27480   0 107
     27481   0 363
     27482   0 354
     27483   0 101
     27484   0 107
     27485   0 363
     27486   0 354
     27487   0 101
     27488   0 107
     27489   0 363
     27490   0 354
     27491   0 101
     27492   0 107
     27493   0 363
     27494   0 354
     27495   0 101
     27496   0 107
     27497   0 363
     27498   0 354
     27499   0 101
     27500   0 107
     27501   0 363
     27502   0 354
     27503   0 101
     27504   0 107
     27505   0 363
     27506   0 354
     27507   0 101
     27508   0 107
     27509   0 363
     27510   0 354
     27511   0 101
     27512   0 107
     27513   0 363
     27514   0 354
     27515   0 101
     27516   0 107
     27517   0 363
     27518   0 354
     27519   0 101
     27520   0 107
     27521   0 363
     27522   0 354
     27523   0 101
     27524   0 107
     27525   0 363
     27526   0 354
     27527   0 101
     27528   0 107
     27529   0 363
     27530   0 354
     27531   0 101
     27532   0 107
     27533   0 363
     27534   0 354
     27535   0 101
     27536   0 107
     27537   0 363
     27538   0 354
     27539   0 101
     27540   0 107
     27541   0 363
     27542   0 354
     27543   0 101
     27544   0 107
     27545   0 363
     27546   0 354
     27547   0 101
     27548   0 107
     27549   0 363
     27550   0 354
     27551   0 101
     27552   0 107
     27553   0 363
     27554   0 354
     27555   0 101
     27556   0 107
     27557   0 363
     27558   0 354
     27559   0 101
     27560   0 107
     27561   0 363
     27562   0 354
     27563   0 101
     27564   0 107
     27565   0 363
     27566   0 354
     27567   0 101
     27568   0 107
     27569   0 363
     27570   0 354
     27571   0 101
     27572   0 107
     27573   0 363
     27574   0 354
     27575   0 101
     27576   0 107
     27577   0 363
     27578   0 354
     27579   0 101
     27580   0 107
     27581   0 363
     27582   0 354
     27583   0 101
     27584   0 107
     27585   0 363
     27586   0 354
     27587   0 101
     27588   0 107
     27589   0 363
     27590   0 354
     27591   0 101
     27592   0 107
     27593   0 363
     27594   0 354
     27595   0 101
     27596   0 107
     27597   0 363
     27598   0 354
     27599   0 101
     27600   0 107
     27601   0 363
     27602   0 354
     27603   0 101
     27604   0 107
     27605   0 363
     27606   0 354
     27607   0 101
     27608   0 107
     27609   0 363
     27610   0 354
     27611   0 101
     27612   0 107
     27613   0 363
     27614   0 354
     27615   0 101
     27616   0 107
     27617   0 363
     27618   0 354
     27619   0 101
     27620   0 107
     27621   0 363
     27622   0 354
     27623   0 101
     27624   0 107
     27625   0 363
     27626   0 354
     27627   0 101
     27628   0 107
     27629   0 363
     27630   0 354
     27631   0 101
     27632   0 107
     27633   0 363
     27634   0 354
     27635   0 101
     27636   0 107
     27637   0 363
     27638   0 354
     27639   0 101
     27640   0 107
     27641   0 363
     27642   0 354
     27643   0 101
     27644   0 107
     27645   0 363
     27646   0 354
     27647   0 101
     27648   0 107
   4123657   0 202
   4123658   0 347
   4123659   0  45
   4123660   0 107
   4123661   0 170
   4123662   0 350
   4123663   0  45
   4123664   0 107
   4123665   0 156
   4123666   0 351
   4123667   0  45
   4123668   0 107
   4123669   0 144
   4123670   0 352
   4123671   0  45
   4123672   0 107
   4123673   0  60
   4123674   0 353
   4123675   0  45
   4123676   0 107
   4123677   0  46
   4123678   0 354
   4123679   0  45
   4123680   0 107
   4123681   0  34
   4123682   0 355
   4123683   0  45
   4123684   0 107
   4123685   0 351
   4123686   0 355
   4123687   0  45
   4123688   0 107
   4123689   0 336
   4123690   0 356
   4123691   0  45
   4123692   0 107
   4123693   0 253
   4123694   0 357
   4123695   0  45
   4123696   0 107
   4123697   0 241
   4123698   0 360
   4123699   0  45
   4123700   0 107
   4123701   0 227
   4123702   0 361
   4123703   0  45
   4123704   0 107
   4123705   0 144
   4123706   0 362
   4123707   0  45
   4123708   0 107
   4123709   0 131
   4123710   0 363
   4123711   0  45
   4123712   0 107
   4123713   0 117
   4123714   0 364
   4123715   0  45
   4123716   0 107
   4123717   0 105
   4123718   0 365
   4123719   0  45
   4123720   0 107
   4123721   0  22
   4123722   0 366
   4123723   0  45
   4123724   0 107
   4123725   0 336
   4123726   0 366
   4123727   0  45
   4123728   0 107
   4123729   0 324
   4123730   0 367
   4123731   0  45
   4123732   0 107
   4123733   0 241
   4123734   0 370
   4123735   0  45
   4123736   0 107
   4123737   0 227
   4123738   0 371
   4123739   0  45
   4123740   0 107
   4123741   0 144
   4123742   0 372
   4123743   0  45
   4123744   0 107
   4123745   0  60
   4123746   0 373
   4123747   0  45
   4123748   0 107
   4123749   0  46
   4123750   0 374
   4123751   0  45
   4123752   0 107
   4123753   0 363
   4123754   0 374
   4123755   0  45
   4123756   0 107
   4123757   0 300
   4123758   0 375
   4123759   0  45
   4123760   0 107
   4123761   0 266
   4123762   0 376
   4123763   0  45
   4123764   0 107
   4123765   0 202
   4123766   0 377
   4123767   0  45
   4123768   0 107
   4123769   0 170
   4123771   0  46
   4123772   0 107
   4123773   0 105
   4123774   0   1
   4123775   0  46
   4123776   0 107
   4123777   0  22
   4123778   0   2
   4123779   0  46
   4123780   0 107
   4123781   0   7
   4123782   0   3
   4123783   0  46
   4123784   0 107
   4123785   0 324
   4123786   0   3
   4123787   0  46
   4123788   0 107
   4123789   0 241
   4123790   0   4
   4123791   0  46
   4123792   0 107
   4123793   0 227
   4123794   0   5
   4123795   0  46
   4123796   0 107
   4123797   0 144
   4123798   0   6
   4123799   0  46
   4123800   0 107
   4123801   0 131
   4123802   0   7
   4123803   0  46
   4123804   0 107
   4123805   0  46
   4123806   0  10
   4123807   0  46
   4123808   0 107
   4123809   0 363
   4123810   0  10
   4123811   0  46
   4123812   0 107
   4123813   0  22
   4123814   0  12
   4123815   0  46
   4123816   0 107
   4123817   0 336
   4123818   0  12
   4123819   0  46
   4123820   0 107
   4123821   0 253
   4123822   0  13
   4123823   0  46
   4123824   0 107
   4123825   0 241
   4123826   0  14
   4123827   0  46
   4123828   0 107
   4123829   0 156
   4123830   0  15
   4123831   0  46
   4123832   0 107
   4123833   0 144
   4123834   0  16
   4123835   0  46
   4123836   0 107
   4123837   0  60
   4123838   0  17
   4123839   0  46
   4123840   0 107
   4123841   0 375
   4123842   0  17
   4123843   0  46
   4123844   0 107
   4123845   0 363
   4123846   0  20
   4123847   0  46
   4123848   0 107
   4123849   0 351
   4123850   0  21
   4123851   0  46
   4123852   0 107
   4123853   0 266
   4123854   0  22
   4123855   0  46
   4123856   0 107
   4123857   0 253
   4123858   0  23
   4123859   0  46
   4123860   0 107
   4123861   0 170
   4123862   0  24
   4123863   0  46
   4123864   0 107
   4123865   0 156
   4123866   0  25
   4123867   0  46
   4123868   0 107
   4123869   0 144
   4123870   0  26
   4123871   0  46
   4123872   0 107
   4123873   0  60
   4123874   0  27
   4123875   0  46
   4123876   0 107
   4123877   0  46
   4123878   0  30
   4123879   0  46
   4123880   0 107
   4123881   0  34
   4123882   0  31
   4123883   0  46
   4123884   0 107
   4123885   0 351
   4123886   0  31
   4123887   0  46
   4123888   0 107
   4123889   0 336
   4123890   0  32
   4123891   0  46
   4123892   0 107
   4123893   0 324
   4123894   0  33
   4123895   0  46
   4123896   0 107
   4123897   0 241
   4123898   0  34
   4123899   0  46
   4123900   0 107
   4123901   0 227
   4123902   0  35
   4123903   0  46
   4123904   0 107
   4123905   0 215
   4123906   0  36
   4123907   0  46
   4123908   0 107
   4123909   0 202
   4123910   0  37
   4123911   0  46
   4123912   0 107
   4123913   0 117
   4123914   0  40
   4123915   0  46
   4123916   0 107
   4123917   0 105
   4123918   0  41
   4123919   0  46
   4123920   0 107
   4123921   0  73
   4123922   0  42
   4123923   0  46
   4123924   0 107
   4123925   0  60
   4123926   0  43
   4123927   0  46
   4123928   0 107
   4123929   0 375
   4123930   0  43
   4123931   0  46
   4123932   0 107
   4123933   0 363
   4123934   0  44
   4123935   0  46
   4123936   0 107
   4123937   0 351
   4123938   0  45
   4123939   0  46
   4123940   0 107
   4123941   0 266
   4123942   0  46
   4123943   0  46
   4123944   0 107
   4123945   0 253
   4123946   0  47
   4123947   0  46
   4123948   0 107
   4123949   0 241
   4123950   0  50
   4123951   0  46
   4123952   0 107
   4123953   0 227
   4123954   0  51
   4123955   0  46
   4123956   0 107
   4123957   0 215
   4123958   0  52
   4123959   0  46
   4123960   0 107
   4123961   0 131
   4123962   0  53
   4123963   0  46
   4123964   0 107
   4123965   0  46
   4123966   0  54
   4123967   0  46
   4123968   0 107
   4123969   0 105
   4123970   0  55
   4123971   0  46
   4123972   0 107
   4123973   0  22
   4123974   0  56
   4123975   0  46
   4123976   0 107
   4123977   0   7
   4123978   0  57
   4123979   0  46
   4123980   0 107
   4123981   0 324
   4123982   0  57
   4123983   0  46
   4123984   0 107
   4123985   0 241
   4123986   0  60
   4123987   0  46
   4123988   0 107
   4123989   0 300
   4123990   0  61
   4123991   0  46
   4123992   0 107
   4123993   0 215
   4123994   0  62
   4123995   0  46
   4123996   0 107
   4123997   0 131
   4123998   0  63
   4123999   0  46
   4124000   0 107
   4124001   0 117
   4124002   0  64
   4124003   0  46
   4124004   0 107
   4124005   0 105
   4124006   0  65
   4124007   0  46
   4124008   0 107
   4124009   0  22
   4124010   0  66
   4124011   0  46
   4124012   0 107
   4124013   0   7
   4124014   0  67
   4124015   0  46
   4124016   0 107
   4124017   0 324
   4124018   0  67
   4124019   0  46
   4124020   0 107
   4124021   0 312
   4124022   0  70
   4124023   0  46
   4124024   0 107
   4124025   0 227
   4124026   0  71
   4124027   0  46
   4124028   0 107
   4124029   0 144
   4124030   0  72
   4124031   0  46
   4124032   0 107
   4124033   0 131
   4124034   0  73
   4124035   0  46
   4124036   0 107
   4124037   0  46
   4124038   0  74
   4124039   0  46
   4124040   0 107
   4124041   0  34
   4124042   0  75
   4124043   0  46
   4124044   0 107
   4124045   0 351
   4124046   0  75
   4124047   0  46
   4124048   0 107
   4124049   0 266
   4124050   0  76
   4124051   0  46
   4124052   0 107
   4124053   0 253
   4124054   0  77
   4124055   0  46
   4124056   0 107
   4124057   0 170
   4124058   0 100
   4124059   0  46
   4124060   0 107
   4124061   0 156
   4124062   0 101
   4124063   0  46
   4124064   0 107
   4124065   0  73
   4124066   0 102
   4124067   0  46
   4124068   0 107
   4124069   0  60
   4124070   0 103
   4124071   0  46
   4124072   0 107
   4124073   0 375
   4124074   0 103
   4124075   0  46
   4124076   0 107
   4124077   0 312
   4124078   0 104
   4124079   0  46
   4124080   0 107
   4124081   0 300
   4124082   0 105
   4124083   0  46
   4124084   0 107
   4124085   0 215
   4124086   0 106
   4124087   0  46
   4124088   0 107
   4124089   0 131
   4124090   0 107
   4124091   0  46
   4124092   0 107
   4124093   0 117
   4124094   0 110
   4124095   0  46
   4124096   0 107
   4124097   0  34
   4124098   0 111
   4124099   0  46
   4124100   0 107
   4124101   0  22
   4124102   0 112
   4124103   0  46
   4124104   0 107
   4124105   0 336
   4124106   0 112
   4124107   0  46
   4124108   0 107
   4124109   0 324
   4124110   0 113
   4124111   0  46
   4124112   0 107
   4124113   0 312
   4124114   0 114
   4124115   0  46
   4124116   0 107
   4124117   0 227
   4124118   0 115
   4124119   0  46
   4124120   0 107
   4124121   0 144
   4124122   0 116
   4124123   0  46
   4124124   0 107
   4124125   0 131
   4124126   0 117
   4124127   0  46
   4124128   0 107
   4124129   0 117
   4124130   0 120
   4124131   0  46
   4124132   0 107
   4124133   0  34
   4124134   0 121
   4124135   0  46
   4124136   0 107
   4124137   0  22
   4124138   0 122
   4124139   0  46
   4124140   0 107
   4124141   0 336
   4124142   0 122
   4124143   0  46
   4124144   0 107
   4124145   0 324
   4124146   0 123
   4124147   0  46
   4124148   0 107
   4124149   0 312
   4124150   0 124
   4124151   0  46
   4124152   0 107
   4124153   0 300
   4124154   0 125
   4124155   0  46
   4124156   0 107
   4124157   0 215
   4124158   0 126
   4124159   0  46
   4124160   0 107




//


$ echo "teste 1 - arquivo a sera igual ao b" > a.txt
$ echo "teste 1 - arquivo a sera igual ao b" > b.txt

$ cmp -l a.txt b.txt
$ (blank)

**Comment by egkhamis** [comment]
@joaomas , para analisarmos o pré teremos que pós processá-lo também. Não sei se convém fazermos isso agora pois temos que fechar as tarefas atuais. Melhor deixarmos para a próxima sprint e levantarmos essas observações.
