### ISSUE TITLE
[GCC] 5ª Reunião Geral do MONAN

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#529]
## :people_holding_hands: User Story

COMO (...)
QUEREMOS (...)
PARA (...)

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Acompanhar a reunião geral e fazer apontamentos pertinentes.

## :pencil: Detalhamento adicional da atividade

-.

## :comet: Impactos

-.

## :link: Dependências

-.

## :hammer_and_wrench: Solução

14:00-14:20 - Avanços na implementação do modelo HYCOM  [Rosio Camayo]. 
14:20-14:40 - Avanços na implementação do modelo MOM6 [Emanuel]. 
14:40-15:00 - Avanços na implementação do modelo MPAS-Ocean [André]. 
15:00-15:30 - Levantamento do estado da arte de acopladores e o MONAN [Carlos Renato]
15:30-15:50 - Intervalo  
15:50-16:10 - Implementação e novos testes do Sistema HYCOM-RODAS[ João]. 
16:10-16:30 - Levantamento de critérios para a definição da componente oceânica [Emanuel].
16:30-16:45 - Discussão geral [Todos].

//

[Carlos Renato] - no tangente sobre acopladores..

    Apresentei um resumo sobre os atuais acopladores do mercado
    Foi basicamente a apresentação da Qualificação simplificada e atualizada
    Levantei algumas questões que eu considero importantes no final
    Mostrei a importância de se olhar para os acopladores já quando olhar para a componente oceânica
    Mostrei a dificuldade de se manter, ajustar um conjunto complexo acoplado
    Candidatos à componente oceânica do MONAN: HYCOM, MPAS-O, MOM6
    Importante: MPAS-O usa a mesma grade de Voronoi que o MPAS-A
    MPAS-O Descontinuado, futuro -> OMEGA-O
    Alguns MC-O já vêm com acoplador embutido: investigar quais são, e como trabalham (das componentes candidatas)
    Sugestão de montar um laboratório simplificado: Toy-Problem: MC-A + MC-O simplificado para trabalhar acoplado

## :rotating_light: Problemas encontrados

-.

## :white_check_mark: Conclusão

- Reunião acompanhada e apontamos realizados.

## :spiral_calendar: Trabalhos Futuros

-.

**Comment by carlosrenatosouza2** [comment]
### Minhas considerações sobre a 5a Reunião Geral do MONAN:

(no tangente sobre acopladores)

- Apresentei um resumo sobre os atuais acopladores do mercado
- Foi basicamente a apresentação da Qualificação simplificada e atualizada 
- Levantei algumas questões que eu considero importantes no final
- Mostrei a importância de se olhar para os acopladores já quando olhar para a componente oceânica
- Mostrei a dificuldade de se manter, ajustar um conjunto complexo acoplado
- Candidatos à componente oceânica do MONAN: `HYCOM`, `MPAS-O`, `MOM6`
- *Importante:* MPAS-O usa a mesma grade de Voronoi que o MPAS-A
- MPAS-O Descontinuado, futuro -> OMEGA-O
- Alguns MC-O já vêm com acoplador embutido: investigar quais são, e como trabalham (das componentes candidatas)
- Sugestão de montar um laboratório simplificado: Toy-Problem: MC-A + MC-O simplificado para trabalhar acoplado
