### ISSUE TITLE
[GCC] PAD: Rodar 7 dias do mês de janeiro

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#546]
## :people_holding_hands: User Story

COMO (...)
QUEREMOS (...)
PARA (...)

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Interação com o Saulo para validar.
- [x] Usar CD_CT feature criada nesta Sprint.
- [x] Usar MONAN-Model Release 1.0.0.
- [x] Não usar o TC.
- [x] Correções computacionais se necessário.
- [x] Rodada 240 horas de previsão.

## :pencil: Detalhamento adicional da atividade

- N/A

## :comet: Impactos

- N/A

## :link: Dependências

- issue #544 

## :hammer_and_wrench: Solução

- Rodadas manuais do pré, modelo e pós processamento enviadas e aprovadas pela avaliação do Saulo, em acordo com os critérios de aceite dessa tarefa.

## :rotating_light: Problemas encontrados

- N/A

## :white_check_mark: Conclusão

- Rodadas concluídas e aprovadas pelo Saulo. 

## :spiral_calendar: Trabalhos Futuros

- N/A

**Comment by deniseiras** [comment]
Bom dia Denis e colegas,
Fiz uma avaliação qualitativa e me parece ok. Vamos em frente iniciando dia 01/01. Como teremos várias iterações, vamos deixar para incluir as variáveis acumuladas do Kubota para a próxima fase. Peço a ele que inclua no versão 1.0 e o GCC faça a avaliação para se tornar oficial.
É importante termos estas rodadas em alguma página web. Peço que orientem os estagiários juntos com a Rose para desenvolvê-la.

Obrigado e abs
Saulo
