### ISSUE TITLE
Correção longitude 0 no pós

### ISSUE THREAD

**Issue by deniseiras** [monanadmin/monan#549]
## :people_holding_hands: User Story

COMO (...)
QUEREMOS (...)
PARA (...)

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Pós desenhando no grads todas lon e lat

## :pencil: Detalhamento adicional da atividade

Olá Denis,
Não entendo esses procedimentos do MONAN. 
Nas latitudes não tem nem -90, nem 90 e nem 0.
No arquivo que deu o caminho tem longitude 360 e não tem 0, mas não adiantou, continua colocando um valor indefinido na longitude 0.
O que posso dizer é que o Pablo fez pós-processamento do experimento MONAN para o caso do ciclone Raoni e lá não apareceu esse problema.
Abraços, Bonatti  

---
Em qua., 26 de jun. de 2024 às 15:53, Denis Magalhẽs de Almeida Eiras <denis.eiras@inpe.br> escreveu:

  Olá Bonatti e Kubota,

  a minha correção foi aumentar em 0.25 as bordas da longitude e mudar nlon de 721 para 720 (não entendi o motivo do 721, talvez seja uma tentativa de corrigir o problema):

  nlat = 360
  nlon = 720
  startlat = -90.
  startlon = -0.25
  endlat = 90.
  endlon = 360.25

  Então percebi que a latitude tem o mesmo problema, não tem LAT -90 ou 90.

  Do jeito que está o centro da grade parece estar correto. Mas talvez ainda precise ajustar o starlat e startlon. Acho que faz sentido usar a mesma lógica de correção? Isto é: startlat = -90.25, endlat 90.25 ? (Ainda não testei)

  Veja como está com a configuração de cima:

  ga-> set X 1  
  LON set to 0.000347227 0.000347227
  ga-> set X 360
  LON set to 179.75 179.75
  ga-> set X 361
  LON set to 180.25 180.25
  ga-> set X 720
  LON set to 360 360
  ga->
  ga-> set Y 1
  LAT set to -89.75 -89.75
  ga-> set Y 180
  LAT set to -0.25 -0.25
  ga-> set Y 181
  LAT set to 0.25 0.25
  ga-> set Y 360
  LAT set to 89.75 89.75

  Abs,

  Denis

  Achei que era um "problema" do grads, mas no ncview também ocorre o mesmo

## :comet: Impactos

_.

## :link: Dependências

_.

## :hammer_and_wrench: Solução

- Corrigido problema de interpolação no arquivo target_mesh.F90
- Criados testes unitários e funcionais, na pasta test
- Criada release 1.0.1 para testes
- 
## :rotating_light: Problemas encontrados

_.

## :white_check_mark: Conclusão

Solução integrada na release 1.0.1.

## :spiral_calendar: Trabalhos Futuros

Gerar tag

**Comment by joaomas** [comment]
Tag gerada, FW - OK.
