### ISSUE TITLE
[GCC] GCC: Rodada MONAN 1.0.0

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#555]
## :people_holding_hands: User Story

COMO (...)
QUEREMOS (...)
PARA (...)

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Rodar desde janeiro Pré, Model e Pós.
- [x] Acompanhar as rodadas até o período possível dentro da Sprint.

## :pencil: Detalhamento adicional da atividade

- Usar as últimas tags (MONAN 1.0.0, Convert 1.0.1 e CD_CT 0.2.0).
- Rodar com 16 nodes a priori.
- Apagar o bruto (deixar o pré e o pós).

## :comet: Impactos

- N/A

## :link: Dependências

- N/A

## :hammer_and_wrench: Solução

- Alterada a versão do convert_mpas para 1.0.0 após solicitação do _PO_ assim como o target_domain na pasta _datain/namelists_ dos scripts_CD-CT de modo a corrigir falta de pontos na latitude e longitude lidas pelo grads do arquivo pós processado:

```
nlat = 361
nlon = 721
startlat = -90.25
startlon = -0.25
endlat = 90.25
endlon = 360.25
```

- Script utilizado para as rodadas do pré, model e pós:
```fortran
#!/bin/bash

# Input variables:--------------------------------------
EXP=${1};         #EXP=GFS
RES=${2};         #RES=1024002
YYYYMMDDHHi=${3}; #YYYYMMDDHHi=2024010100
FCST=${4};        #FCST=240
NDAYS=${5}        #numero de dias do ciclo 
#-------------------------------------------------------

for j in $(seq 0 $NDAYS)
do
   echo "j=$j days "
   hh=${YYYYMMDDHHi:8:2}
   currentdate=`date -d "${YYYYMMDDHHi:0:8} ${hh}:00 ${j} days" +"%Y%m%d%H"`
   echo "${currentdate}"
   diag_name=MONAN_DIAG_G_MOD_GFS_${YYYYMMDDHHi}_${currentdate}.00.00.x${RES}L55.nc
   echo "diag_name=${diag_name}"
   ./2.pre_processing.bash ${EXP} ${RES} ${currentdate} ${FCST} > saida_pre.txt &
   wait
   #./3.run_model.bash ${EXP} ${RES} ${currentdate} ${FCST} > saida_model.txt &
   #wait
   #./4.run_post.bash ${EXP} ${RES} ${currentdate} ${FCST} > saida_post.txt &
   #wait
   #rm -rf ../dataout/${currentdate}/Model
done

```

- Backup da rodada bruta do modelo, assim como o pré e pós do modelo na conta monan.
- Backup dos dados de janeiro de 2024 do GFS para a conta monan visto que serão removidos da operação.

## :rotating_light: Problemas encontrados

- Erro no modelo (referência inválida da memória) nas datas 2024020300, 2024022700, 2024032400 e 2024052500.

## :white_check_mark: Conclusão

- Rodadas do ciclo (Pré, Model e Pós) desde janeiro até meados de junho.

## :spiral_calendar: Trabalhos Futuros

- Investigar falhas nas rodadas do modelo.
- Finalizar rodadas até a data atual.
- Aguardando validação do pós (cálculo da energética pelo Bonatti após ok inicial) para remoção completa dos dados brutos do modelo.

**Comment by egkhamis** [comment]
- Script que utiliza a data inicial e final como entrada para o ciclo de rodadas do modelo e do pós:

```fortran
#!/bin/bash
  
# Input variables:--------------------------------------
EXP=${1};         #EXP=GFS
RES=${2};         #RES=1024002
YYYYMMDDHHi=${3}; #YYYYMMDDHHi=2024010100
YYYYMMDDHHf=${4}; #YYYYMMDDHHi=2024070100
FCST=${5};        #FCST=240
#NDAYS=${5}        #numero de dias do ciclo
#-------------------------------------------------------


# Local variables--------------------------------------
yyyymmddi=${YYYYMMDDHHi:0:8}
yyyymmddf=${YYYYMMDDHHf:0:8}
#hhi=${YYYYMMDDHHi:8:2}
#yyyymmddhhf=$(date +"%Y%m%d%H" -d "${yyyymmddi} ${hhi}:00 ${FCST} hours" )
#final_date=${yyyymmddhhf:0:4}-${yyyymmddhhf:4:2}-${yyyymmddhhf:6:2}_${yyyymmddhhf:8:2}.00.00
#-------------------------------------------------------


let NDAYS=($(date +%s -d $yyyymmddf)-$(date +%s -d $yyyymmddi))/86400
echo "initial_date=$yyyymmddi"
echo "final_date=$yyyymmddf"
echo "NDAYS=$NDAYS"
echo "running the cycle..."
echo ""


for j in $(seq 0 $NDAYS)
do
   echo "j=$j days "
   hh=${YYYYMMDDHHi:8:2}
   currentdate=`date -d "${YYYYMMDDHHi:0:8} ${hh}:00 ${j} days" +"%Y%m%d%H"`
   echo "${currentdate}"
   diag_name=MONAN_DIAG_G_MOD_GFS_${YYYYMMDDHHi}_${currentdate}.00.00.x${RES}L55.nc
   echo "diag_name=${diag_name}"
   #./2.pre_processing.bash ${EXP} ${RES} ${currentdate} ${FCST} > saida_pre.txt &
   #wait
   ./3.run_model.bash ${EXP} ${RES} ${currentdate} ${FCST} > saida_model.txt &
   wait
   ./4.run_post.bash ${EXP} ${RES} ${currentdate} ${FCST} > saida_post.txt &
   wait
   #rm -rf ../dataout/${currentdate}/Model
done

```

**Comment by joaomas** [comment]
@egkhamis @deniseiras 

**/mnt/beegfs/monan/tc/1.0.0/... (saida yyyymmddhh/Post)**
