### ISSUE TITLE
[GCC] GCC: EcFlow - Nivelamento Operacional

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#557]
## :people_holding_hands: User Story

COMO (...)
QUEREMOS (...)
PARA (...)

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Nivelar Operacionalmente o EcFlow ao time.

## :pencil: Detalhamento adicional da atividade

-.

## :comet: Impactos

-.

## :link: Dependências

-.

## :hammer_and_wrench: Solução

- ecFlow Documentaion: https://confluence.ecmwf.int/display/ECFLOW/Documentation
- ecFlow training course 2017: https://confluence.ecmwf.int/download/attachments/13207146/2017-01-19-ecFlowUI-for-ecFlow-training-course.pdf?api=v2

![Image](https://github.com/user-attachments/assets/4b9a7ce0-5b54-4e2a-8915-5d9bc07538ae)

- ecFlow training course 2018: https://confluence.ecmwf.int/download/attachments/13207146/ecflowcourse2018.pdf?api=v2

- Notas:

scritpt

"%" pega variáveis do ECFlow nos scripts

Suítes
- suite.def

suite suite_name
  some variables

family myfamily

  taskxxx (taskxxx.ecf) - sempre tem um head.h e um tail.h
  cron 
  triggers

---
para rodar um script temporario para execução, sem alterar o script original, clicar na aba "Edit"

Cores
- Server Cinza - FORA DO AR!
- Rosa - Suíte só com o Server sem a suíte
  - para subir a suíte, chamar "inicializadef MONAN_STAB"
    - apagar antes arquivos .check para zerar o status da suíte.
  
  - clicar com o botão direito e "restart" do servidor
- azul enfileirado
- verde: rodando
- amarelo: OK
- vermelho: erro

dir ecflow/eclogs
 - scripts ferramentas para operar o ECFlow
 - ex: stop.ksh - parar servidor, start.ksh - iniciar
 - inicializadef.ksh - inicializa suite passada por parâmetro
 - esses comando também estão como link dentro do ~/bin da conta monan
 - arquivos .check - foto do status anterior da ultima instância

apos criar um script.def, rodar um atualizadef SUITENAME 

## :rotating_light: Problemas encontrados

-.

## :white_check_mark: Conclusão

- Nivelamento realizado a todo o grupo.

## :spiral_calendar: Trabalhos Futuros

-.

**Comment by deniseiras** [comment]
Minhas anotações

ECFlow
scritpt

"%" pega variáveis do ECFlow nos scripts

Suítes
- suite.def

suite suite_name
  some variables

family myfamily

  taskxxx (taskxxx.ecf) - sempre tem um head.h e um tail.h
  cron 
  triggers


---
para rodar um script temporario para execução, sem alterar o script original, clicar na aba "Edit"


Cores
- Server Cinza - FORA DO AR!
- Rosa - Suíte só com o Server sem a suíte
  - para subir a suíte, chamar "inicializadef MONAN_STAB"
    - apagar antes arquivos .check para zerar o status da suíte.
  
  - clicar com o botão direito e "restart" do servidor
- azul enfileirado
- verde: rodando
- amarelo: OK
- vermelho: erro

dir ecflow/eclogs
 - scripts ferramentas para operar o ECFlow
 - ex: stop.ksh - parar servidor, start.ksh - iniciar
 - inicializadef.ksh - inicializa suite passada por parâmetro
 - esses comando também estão como link dentro do ~/bin da conta monan
 - arquivos .check - foto do status anterior da ultima instância


apos criar um script.def, rodar um atualizadef SUITENAME
