### ISSUE TITLE
[GCC] GCC: Monitorar TC - Stable

### ISSUE THREAD

**Issue by deniseiras** [monanadmin/monan#563]
## :people_holding_hands: User Story

COMO (...)
QUEREMOS (...)
PARA (...)

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Verificar saída do Sanity Check.
- [x] Verificar EcFlow.
- [x] Documentar comportamento das rodadas ao longo da Sprint.

## :pencil: Detalhamento adicional da atividade

-.

## :comet: Impactos

-.

## :link: Dependências

-.

## :hammer_and_wrench: Solução

Cron Start: 6h

**Stab MONAN 1.0.0 - Convert 1.0.1 - CD-CT 0.2.0**
Saída: 3h em 3h

| Data | Model <br> Time | Final <br> Time | Pré <br> Model <br> Pós | Sanity-Check <br> Compare_Stats | Ocorrências |
| :---: | :---: | :---: | :---: |  :---: | :--- |
| 09/07/2024 | 4484.39648 | 09:24 | ok <br> ok <br> ok | ok <br> ok | - |
| 10/07/2024 | 4410.22803 | 09:24 | ok <br> ok <br> ok | ok <br> ok | - |
| 11/07/2024 | 4494.88965 | 09:24 | ok <br> ok <br> ok | ok <br> ok | - |

#### Procedimentos de monitoramento

**Entrar no EcFlow**

$ oec
- Verificar status das tasks

**Criado Script check_rodada.bash (utils/)***

OBS: Para verificar o compare do dia, deve-se rodar uma data anterior pois ele grava as saidas em dataout [DD = hoje -1].

`/mnt/beegfs/monan/utils/check_rodada.bash YYYYMMDD00`

Ver alguns resultados em comentários

O monitoramento foi suspenso até o fim das rodadas da tarefa #555 por conta de recursos operacionais.

## :rotating_light: Problemas encontrados

-.

## :white_check_mark: Conclusão

- Monitoramento de 09 a 11 de julho não apresentou problemas.

## :spiral_calendar: Trabalhos Futuros

-.

**Comment by deniseiras** [comment]
monan@egeon-login1: /mnt/beegfs/monan/utils $ /mnt/beegfs/monan/utils/check_rodada.bash 2024071000

 *******************************************************************************
 Diretorio CDCT: /mnt/beegfs/monan/scripts_CD-CT
 Diretorio PRODS: /mnt/beegfs/monan/MONAN-WorkFlow/ecflow/MONAN_STAB/Products/MONAN-Products
 Diretorio FTP: /pesq/share/monan/testes_continuos_CD-CT
 Rodada: 2024071000
 *******************************************************************************

 =====>> Verificando Pré... [Referência 3 files | >9G size]
 Files: 3
 Size: 9.7G
 Final Time: 06:02

 =====>> Verificando Model... [Referência 83 files | >200G size]
 Files: 83
 Size: 215G
 Final Time: 07:30

 =====>> Verificando Pós... [Referência 3 files | >50G size]
 Files: 3
 Size: 55G
 Final Time: 07:30

 =====>> Verificando Prods: Sanity Check... [Referência 513 files | >250M size]
 Files: 513
 Size: 251M
 Final Time: 07:45

 =====>> Verificando Prods: Compare_Stats... [Referência 17 files | >500K size]
 Files: 17
 Size: 525K
 Final Time: 09:15

 =====>> Verificando FTP: Sanity Check... [Referência 513 files | >250M size]
 Files: 513
 Size: 254M
 Final Time: 07:46

 =====>> Verificando Model Time
 Total Time (log.atmosphere): 4410.22803

 *******************************************************************************

 Atenção! No momento o compare_stats apresentado é referente ao produto do dia posterior (+1)

**Comment by joaomas** [comment]
- Suspendido suite MONAN_STAB no EcFlow. O cron stable já foi desativado após a migração da Etapa 2.
- Suspendido também o Cron na Egeon do ambiente DEV.
