### ISSUE TITLE
Escalabilidade - Minerva - MPAS - Intel

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#64]
# Descrição

Nota Sprint 6: Nova estimativa 4h.

**Revisão PO (Sprint 5): novas rodadas agora com nºs de cores padronizados; testar novamente com 32 nodes usando solução do suporte Lab Dell e tomada de tempo apenas do core-dinâmico.**

Rodar modelo MPAS de 1 a 32 nós (step 1, 2, 4, 8, 16, 32) com resolução de 15km (usar a tarefa de execução anterior) com previsão de 12 horas.
Estimativa: 18h
Realidade: -
**Nova estimativa da revisão: 12h (incluindo gráficos)**

# Dependências

#61 e #62 

# Solução

1. Gerar arquivo de malha para qtde de cores q forem necessários e que não estiver disponível no pacote do benchmark:
~~~
carregar o modulo metis primeiro e depois usar o comando:

gpmetis -minconn -contig -niter=200 x1.5898242.graph.info 256

onde 5897242 é um número  fixo para resolução de 10km (para 15km esse número é diferente) e 256 é o número de processadores que irá usar.
~~~

Mais detalhes podem ser encontrados na issue #24 .

2. Criar scripts para facilitar as rodadas automaticas: `run_make_submitis.hs` executa 5 vezes (para cada configuração de cores) o script `make_submits.sh`, que, pos sua vez, constroi o script `submits.sh`com o cabeçalho SBATCH correto e o submete. Segue abaixo os scripts:
`run_make_submits.sh`:
~~~
#!/bin/ksh

nsleeps=20

for i in 1 2 3 4 5
do
   for nodes in 1 2 4 8 16 32
   do
      ncores=$(echo "${nodes}*128" | bc)
      ntpn=64
      nnodes=$(echo "${ncores}/${ntpn}" | bc)

      echo "make_submits.sh ${ncores} ${nnodes} ${ntpn} ${i}"
      ./make_submits.sh ${ncores} ${nnodes} ${ntpn} ${i}
      sleep ${nsleeps}
   done
done
~~~

`make_submits.sh`:
~~~
#!/bin/ksh 

#SBATCH --nodes=${nnodes}
#SBATCH --ntasks=${ncores}               #Numero total de tarefas MPI
#SBATCH --tasks-per-node=${ntpn}
#SBATCH --partition=7713
#SBATCH --job-name=MPAS.CR
#SBATCH --time=12:00:00         
##sbatch --mem-per-cpu=64000M

executable=atmosphere_model

. /work/carlos.inpe/mpas_minerva_intel/env.sh

spack load --only dependencies mpas-model%intel@19.1.3.304
spack load --list

resultdir=${DIRHOME}/results/partition-\${SLURM_JOB_PARTITION}/NUMNODES-\$SLURM_JOB_NUM_NODES/MPI-\${SLURM_NTASKS}/JOBID-\${SLURM_JOBID}

mkdir -p \${resultdir}

#export MPAS_DYNAMICS_RANKS_PER_NODE=2
#export MPAS_RADIATION_RANKS_PER_NODE=6
#export MALLOCSTATS=1

ulimit -s unlimited

#export OMP_NUM_THREADS=1

cd  \$SLURM_SUBMIT_DIR
echo \$SLURM_JOB_NUM_NODES


date
echo "mpirun -np \$SLURM_NTASKS ./\${executable}"
time mpirun -np \$SLURM_NTASKS ./\${executable}
date

cp slurm-\${SLURM_JOBID}.out \${resultdir}/
cp log.atmosphere.*.out \${resultdir}/
cp namelist.atmosphere \${resultdir}/
cp submit_atmosphere.sh \${resultdir}/
mv x1.*.init.nc-*.lock \${resultdir}/
mv diag* \${resultdir}/
mv histor* \${resultdir}/
EOSC

chmod a+x ${DIRHOME}/run_${ncores}-${nnodes}-${ntpn}r${nrun}/submits_${ncores}-${nnodes}-${ntpn}r${nrun}.sh
sbatch  ${DIRHOME}/run_${ncores}-${nnodes}-${ntpn}r${nrun}/submits_${ncores}-${nnodes}-${ntpn}r${nrun}.sh

~~~

Importante ressaltar que para 1 nó (128 cores) houve falta de memória suficiente no nó, precisando dividir os 128 cores em 2 nós. Para facilitar a identificação das configurações de cada rodada, usei um label padrão: N1-N2-N3, onde: N1 = número total de tasks MPI, N2 = número de nós e N3 = número de tasks por nó.

3. Foram feitas 5 rodadas iguais para cada configuração de experimento: 1 nó (128 cores), 2 (256), 4 (512), 8 (1024), 16 (2048) e 32 nós (4096 cores). ::

- 1 nó (128 cores): 128-1-128 (node207) 
- 1 nó (128 cores): 128-2-64 
- 2 (256): 256-2-128
- 4 (512): 512-4-128
- 8 (1024): 1024-16-64
- 16 (2048): 2048-32-64
- 32 (4096): 4096-64-64 (não rodou!)
- 64 nós (8196 cores): 8196-128-64  (Qtde de nós insuficiente)

# Problemas encontrados

- Aparentemente, não é possível rodar MPAS dentro de 1 nó. Das três instâncias, apenas uma rodou. 

> Solução: Falta de memoria. O nó 207 tem mais memória que os demais, e a instância que rodou foi no node207. Então as rodadas sequenciais serão realizadas no 207.

- Configurações acima de 8 nós não rodaram. Também por falta de memória.

> Solução: tentativa de rodar com menos cores/nó: 64 cores/nó.

- Rodadas com 4096 não executou (eu acho que é) por falta de memória. 

> Solução: no script de submissão:  export I_MPI_OFI_PROVIDER=Verbs e -genv UCX_TLS=all na linha do mpirun.

- Estranhamente, a rodada com 128 cores alocados dentro do mesmo nó (node207) levou 10.411 segundos para integrar 12hs; a mesma rodada com os mesmos 128 cores mas quando alocados em dois nós quaisquer (distribuindo 64 cores por nó) levou 5.933 segundos (a se discutir). 
...

**Comment by carlosrenatosouza2** [comment]
Como as rodadas com 4096 cores não executaram por falta de recursos, fecho esta tarefa com a execução de todas as rodadas que usaram menos cores que 4096.

Done!

**Comment by joaomas** [comment]
Issue reaberta para adequação das correções propostas pelo PO: rodada com numero de processadores padronizado e nova tentativa de execução com 32 nodes usando solução experimentada na SHiELD.
Nova estimativa: 12h

**Comment by robertopsouto** [comment]
@carlosrenatosouza2 , eu preparei um shell script para somar os tempos da rotinas do core dinâmico do MPAS:
**dyncoretime.sh**
```bash
#!/bin/bash

var=0
for j in $(cat dyncore.txt);do
    dyncoretime=`grep -w ${j} log.atmosphere.0000.out | awk '{ print $3 }'`
    echo $dyncoretime " (${j} time)"
    var=$(echo $var + $dyncoretime  | bc)
done
echo
echo $var" (Total dyncore time)"
```

onde o conteúdo de **dyncore.txt** é:
```bash
atm_rk_integration_setup
atm_compute_moist_coefficients
atm_compute_vert_imp_coefs
atm_compute_dyn_tend
small_step_prep
atm_advance_acoustic_step
atm_recover_large_step_variables
atm_compute_solve_diagnostics
atm_rk_dynamics_substep_finish
atm_advance_scalars
atm_advance_scalars_mono
```

A saída deve ser algo similar a:
```bash
52.24352  (atm_rk_integration_setup time)
19.00019  (atm_compute_moist_coefficients time)
30.64906  (atm_compute_vert_imp_coefs time)
815.67914  (atm_compute_dyn_tend time)
118.17416  (small_step_prep time)
283.14929  (atm_advance_acoustic_step time)
366.89252  (atm_recover_large_step_variables time)
446.51663  (atm_compute_solve_diagnostics time)
115.29865  (atm_rk_dynamics_substep_finish time)
164.96556  (atm_advance_scalars time)
413.52124  (atm_advance_scalars_mono time)

2826.08996 (Total dyncore time)
```

**Comment by carlosrenatosouza2** [comment]
# Revisão da Issue

## Solução

@robertopsouto rodou para 1, 2, 4, 8, 16, e 32 nós utilizando 128 cores/nó, e também utilizando 64 cores/nó. Utilizando o seguinte script de submissão:
~~~
#!/bin/bash
#SBATCH --nodes=1               
#SBATCH --ntasks=8              
#SBATCH -p gpuq                 
#SBATCH -J atmosphere_model     
#SBATCH --time=03:30:00         

executable=atmosphere_model

rm log.atmosphere.*.out

module load hpc
module load python37
module load intel/compiler/19.1.3.304

. /work/rpsouto.incc/spack/v0.17.1_minerva_mlogin/share/spack/setup-env.sh
export SPACK_USER_CONFIG_PATH=/work/rpsouto.incc/.spack/v0.17.1_minerva_mlogin

spack load --only dependencies mpas-model%intel@19.1.3.304
spack load --list
ldd $executable

resultdir=results/partition-${SLURM_JOB_PARTITION}/NUMNODES-$SLURM_JOB_NUM_NODES/MPI-${SLURM_NTASKS}/JOBID-${SLURM_JOBID}

mkdir -p ${resultdir}

cd  $SLURM_SUBMIT_DIR

echo "mpirun -np $SLURM_NTASKS -genv UCX_TLS=all ./${executable}"
mpirun -np $SLURM_NTASKS -genv UCX_TLS=all ./${executable}

cp slurm-${SLURM_JOBID}.out ${resultdir}/
cp log.atmosphere.*.out ${resultdir}/
~~~

Utilizando a seguinte linha de submissão: 
`$ sbatch -N32 -n4096 -p 7713 submit_atmosphere_minerva_mlogin_intel.sh`

Obtendo os seguintes resultados:

![Captura de tela de 2022-08-01 14-26-28](https://user-images.githubusercontent.com/89524306/182207196-a519b200-55bc-4f3b-bb6d-941d51427db6.png)

![Captura de tela de 2022-08-01 14-27-16](https://user-images.githubusercontent.com/89524306/182207274-80b60ed4-9f66-4a00-9dc4-abc0e05e372c.png)

![Captura de tela de 2022-08-01 14-27-43](https://user-images.githubusercontent.com/89524306/182207339-7a615bd6-cad2-4f5e-ac7d-fcd9d1358dd5.png)
