### ISSUE TITLE
Grafico - Minerva - MPAS - Intel

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#65]
# Descrição

Nota Sprint 6: Nova estimativa 0h.

**Revisão PO: novos gráficos baseados nas novas rodadas com nºs de cores padronizados**

Elaborar o gráfico de speedup, eficiência e escalabilidade do modelo MPAS utilizando o template da avaliação parcial (GDrive - GCC). Hora final de extrapolação 24h, utilizar tempo do core dinâmico.

Estimativa: 6h

# Impactos

Não há impactos.

# Dependências

#64 

# Solução

1. Importante mostrar a estruura de diretorios que os scripts utilizados na issu #64 criaram para acondicionar os logs das rodadas:
~~~
dentro da pasta de submissão\
          \ results \
               \ partition-7713 \            # Fila que foi usada
                    \ NUMNODES-N \     # N: numero de nós que foram utilizados
                         \ MPI-nnn \            # nnn: quantidade de cores mpis utilizados
                              \ JOBID-jjjjjj \    # jjjjjj: job id 

~~~

2. Capturar os tempos das rodadas da issue #64 que estão no final do log de saida `log.atmosphere.0000.out" dentro da pasta `JOBID-jjjjjj`. Com o seguinte comando:
Na pasta `MPI-nnn` :
~~~
grep "1 total time" */log.a* | tr '.' ','  # ja trocar pontos por vigulas para facilitar a inserção dos tempos na planilha template dos gráficos.

Resultado:

JOBID-113817/log,atmosphere,0000,out:  1 total time                                       10409,55664         1    10409,44336    10409,55664    10409,49902   100,00       0,00       1,00
JOBID-113818/log,atmosphere,0000,out:  1 total time                                       10417,48340         1    10417,39160    10417,48340    10417,44141   100,00       0,00       1,00
JOBID-113863/log,atmosphere,0000,out:  1 total time                                       10415,22852         1    10415,13477    10415,22852    10415,18555   100,00       0,00       1,00
~~~

3. Utilizei a planilha de graficos template na área do ggogle drive do GCC.
4. Obtive dois conjuntos de graficos: 

>  (1) speed ups e eficiências relativos calculados com o tempo das rodadas "sequenciais" de 1 nó (128 cores) alocados em um nó apenas: aproximadamente 10.415 segundos.

> (2) speed ups e eficiências relativos calculados com o tempo das rodadas "sequenciais" de 1 nó (128 cores) alocados em 2 nós: aproximadamente 5.933 segundos.

# Resultados:

(1)

![Captura de tela de 2022-07-26 13-13-21](https://user-images.githubusercontent.com/89524306/181057092-8031c1de-9e73-4f48-ab1d-5e2cd65ecc69.png)

![Captura de tela de 2022-07-26 13-14-50](https://user-images.githubusercontent.com/89524306/181059015-50f92b91-611b-43ee-b7c7-1ba9504c4ba2.png)

![Captura de tela de 2022-07-26 13-15-46](https://user-images.githubusercontent.com/89524306/181059044-de4bd611-cde7-435a-86c4-e94bdb1910ac.png)

![Captura de tela de 2022-07-26 13-16-25](https://user-images.githubusercontent.com/89524306/181059054-d4df917a-dd92-4e2c-84cb-cbbfa3cdb60a.png)

(2)

![Captura de tela de 2022-07-26 13-17-12](https://user-images.githubusercontent.com/89524306/181058832-20d587a4-ce84-490f-adda-353d118fbc4f.png)

![Captura de tela de 2022-07-26 13-17-42](https://user-images.githubusercontent.com/89524306/181058725-da22bd98-474d-4a3c-a941-c519b475a57d.png)

![Captura de tela de 2022-07-26 13-18-17](https://user-images.githubusercontent.com/89524306/181058752-8f79498c-7c8f-4976-aee0-56259c2ee6f5.png)

![Captura de tela de 2022-07-26 13-18-48](https://user-images.githubusercontent.com/89524306/181058771-22b079f8-c9c2-4207-839b-7d507b75f96b.png)

**Comment by carlosrenatosouza2** [comment]
Done.

**Comment by joaomas** [comment]
Issue reaberta para adequação das correções propostas pelo PO: correção dos gráficos com base na nova rodada com numero de processadores padronizados e nova tentativa de execução com 32 nodes usando solução experimentada na SHiELD.
Nova estimativa: incluso na issue de escalabilidade.

**Comment by carlosrenatosouza2** [comment]
# Revisão Issue

# # Solução

@robertopsouto rodou para 1, 2, 4, 8, 16 e 32 nós utilizando 64 cores/nó, obtendo os seguintes resultados:


![Captura de tela de 2022-08-01 14-26-28](https://user-images.githubusercontent.com/89524306/182207996-14ec2968-430a-4c09-a491-66f8068be651.png)

![Captura de tela de 2022-08-01 14-27-16](https://user-images.githubusercontent.com/89524306/182208024-042b9dfa-1c65-4063-bce1-a27aa80462b4.png)

![Captura de tela de 2022-08-01 14-27-43](https://user-images.githubusercontent.com/89524306/182208041-2c63854a-3b1a-4d5b-9c4d-b3d5a050e257.png)


Planilha com os resultados está na pasta: GDrive_GCC/Milestones_Issue_docs/TST_PEE/65

Issue revisada, corrigida, encerrada.
