### ISSUE TITLE
Escalabilidade - Minerva - SHiELD- Intel

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#66]
# Descrição

**Revisão PO: novas rodadas agora com nºs de cores padronizados**
Para o Shield foram considerados 72 processadores, que estariam mais próximos dos 64 usados pelo MPAS.

Rodar modelo SHiELD de 1 a 32 nós (step 1, 2, 4, 8, 16, 32) com resolução de 13km (usar a tarefa de execução anterior) com previsão de 12 horas.
Estimativa: 16h
**Nova estimativa da revisão: 8h (incluindo gráficos)**

# Impactos

Não há impactos.

# Dependências

- #58 , que depende de #57 

# Solução

Utilizou-se a solução da Issue #58 como base para esta:

1. Criou-se o diretório `/work/denis.inpe/shield_intel_minerva/`
2. Criou-se um link para o spack da Issue 57: `ln -s /work/eduardo.inpe/.spack/v0.17.1_minerva_intel/`
3. Carregou-se o ambiente: `source v0.17.1_minerva_intel/env.sh`
4. Copiou-se a pasta com o build completo do Shield (#57): `/work/eduardo.inpe/shield/shield_container_minerva_intel/SHiELD_build` , para utilizar o executável
5. Copiou-se /work/eduardo.inpe/shield/global_scalability_minerva_intel e /work/eduardo.inpe/shield/GFS_fix para a pasta  global_scalability (#57)
6. Criou-se o template para o input.nml, input.def ( http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/github_issues_files/66/global_scalability/input.def ) na pasta global_scalability
7. Criou-se o template para a submissão, baseado no script de submissão da #58, shield.def ( http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/github_issues_files/66/shield.def )
8. Criou-se o disparador de jobs run_exps.sh que dispara entre 1 e 32 nós ( http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/github_issues_files/66/run_exps.sh)
9. Executou-se o run_exps.sh

Foram utilizados 2 nodes para gerar os resultados de 1 node, pois o resultado usando 1 node (node2017) foi ruim, o que impactou muito as curvas de speed up e eficiência.

Os resultados são exibidos nos gráficos da #67 .

# Problemas encontrados

Ao executar com 16 ou 32 nodes, o seguinte erro foi apresentado:
`mlx5dv_devx_obj_create(QP) failed, syndrome 0: Cannot allocate memory`

Uma das soluções encontrada em https://urldefense.com/v3/__https:/community.intel.com/t5/Intel-Fortran-Compiler/UCX-error-with-Coarray-Distributed-Mode/m-p/1230477__;!!LpKI!ha_Cc5Y5YJUHSoENPCopYBG7Gy9E8EN9sJAbcUU11zElVSFQxhn6cX0PtBvHqDkmO6tfApZJ338ajbNU9TXULrRQL7E$ :
`export I_MPI_OFI_PROVIDER=Verbs`

Porém, ao consultar o lab da Dell, a seguinte solução sugerida foi utilizada para todas as execuções: 
`mpirun -genv UCX_TLS=all ... `

Ambas execuções não diferenciaram significativamente em tempo de execução.

**Comment by deniseiras** [comment]
O número de processadores foi alterado de 96 cores por nó para 72 cores por nó. Os resultados anteriores foram mantidos na planilha e na #67
