### ISSUE TITLE
Grafico - Minerva - SHiELD - Intel

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#67]
# Descrição

**Revisão PO: novos gráficos baseados nas novas rodadas com nºs de cores padronizados**
Para o Shield foram considerados 72 processadores, que estariam mais próximos dos 64 usados pelo MPAS.

Elaborar o gráfico de speedup, eficiência e escalabilidade do modelo SHiELD utilizando o template da avaliação parcial (GDrive - GCC). Hora final de extrapolação 24h, utilizar tempo do core dinâmico.

Estimativa: 6h

# Impactos

Não há impactos.

- #66

Não há dependências.

# Solução

1. Gerou-se os gráficos, a partir do template
`GCC/Milestones_Issues_docs/TST_PEE/Avaliação da Eficiência dos núcleos dinâmicos TEMPLATE`
em 
`GCC/Milestones_Issues_docs/TST_PEE/66/Avaliação da Eficiência Shield Minerva`
de onde as seguintes figuras foram geradas (usou-se 96 e 72 processadores por nó, com exceção dos resultados de um nó, que usou 96/72 processadores em 2 nós). Para efeitos de comparação com o MPAS, considerar 72 processadores por nó.

![image](https://user-images.githubusercontent.com/6113640/181615469-cf379a46-225e-4054-941c-b4d1bb46fcf7.png)

![image](https://user-images.githubusercontent.com/6113640/181615524-c36ba2a9-870a-4610-ae65-e13e9c8b7a6c.png)

![image](https://user-images.githubusercontent.com/6113640/181615598-a8578b1d-b745-4e45-91ec-ff136394d680.png)

# Problemas encontrados

...

**Comment by joaomas** [comment]
Issue reaberta para adequação das correções propostas pelo PO: correção dos gráficos com base na nova rodada com numero de processadores padronizados.
Nova estimativa: incluso na issue de escalabilidade.

**Comment by deniseiras** [comment]
Foi feita rodadas adicionais com 64 nós. A planilha geradora dos gráficos foi atualizada.
