### ISSUE TITLE
Verificar quais regras e recomendações do Code Paterns podem seu automatizadas

### ISSUE THREAD

**Issue by monanadmin** [monanadmin/monan#69]
Um dos subgrupos do GCC é responsável pelas tarefas de code review. Os códigos costumam vir sem respeitar parte das regras de codificação definidas em [Code Paterns](https://github.com/monanadmin/monan/wiki/Padr%C3%A3o-de-codifica%C3%A7%C3%A3o---(Code-patterns)) tratado para o modelo MONAN. Para facilitar a tarefa do subgrupos algumas ações prévias de formatação de código podem ser usadas.

A tarefa consiste em analisar e desenvolver ferramentas que auxiliem na avaliação e criação de relatórios conformidade e não conformidade para cada código submetido.  Essas ferramentas podem usar o pacote desenvolvido para o compilador G95 como base para 'parse' do código e extração de informações para tal análise.

A base do estudo está em [Parser XML G95](http://g95-xml.sourceforge.net/)

**Comment by joaomas** [comment]
Esta issue foi substituta pelas issues #110 #115 #119 e #120
