### ISSUE TITLE
Relatório: Introdução

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#78]
# Descrição

Descrição: Elaborar texto introdutório do relatório final dos experimentos
Estimativa: 8h

# Dependências

Não há dependências.

# Documentação ou Link externo da documentação

Link: [Doc - GDrive](https://docs.google.com/document/d/1drJMJYJp5UZzjdjsbU5nRl4Rth7jzbmIYBrWLNW8uXw/edit)

...

**Comment by luflarois** [comment]
A introdução foi escrita. Cabe uma revisão pelos pares para a versão final.

**Comment by joaomas** [comment]
Revisão final será feita em outra issue.
