### ISSUE TITLE
Relatório: Conclusão

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#84]
# Descrição

Descrição: Elaborar texto de conclusão do relatório final dos experimentos
Estimativa: 8h

# Dependências

Não há dependências.

# Documentação ou Link externo da documentação

Link: [Doc no GDrive](https://docs.google.com/document/d/1drJMJYJp5UZzjdjsbU5nRl4Rth7jzbmIYBrWLNW8uXw/edit)

**Comment by luflarois** [comment]
Observação: Esse capítulo carece dos resultados descritos nos capítulos anteriores.

**Comment by joaomas** [comment]
Revisão final será feita em outra issue.
