### ISSUE TITLE
Revisão final documento de avaliação

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#89]
# Descrição

Descrição: Revisão final do documento de avaliação

**Estimativa (Sprint 10): 4h**

# Dependências

Não há dependências.

# Documentação ou Link externo da documentação

Link: https://docs.google.com/document/d/1drJMJYJp5UZzjdjsbU5nRl4Rth7jzbmIYBrWLNW8uXw/edit#heading=h.pgh675kc4e19

**Comment by luflarois** [comment]
O documento foi totalmente revisado e está concluído. Será enviado um PDF do mesmo para o Comitê Científico e ficará também disposto no SEI dentro do processo do TAP do MONAN.
