### ISSUE TITLE
Criar documento com critérios de avaliação de qualidade do Core Dinâmico

### ISSUE THREAD

**Issue by deniseiras** [monanadmin/monan#9]
# Descrição
A escolha do Core Dinâmico deverá guiada por critérios pré-definidos de qualidade de software. Um documento deve ser criado para detalhar quais as principais características de Qualidade de Software deverão ser utilizadas para a escolha.

#8 #7 
@cfbastarz @joaogerd @robertopsouto @lufla-1962 @egkhamis

**Comment by joaomas** [comment]
Relatório de avaliação do core dinâmico criado.
