### ISSUE TITLE
Portabilidade: Executar MPAS%Egeon@INTEL - IntelMPI

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#95]
# Descrição

Executar o MPAS na Egeon com IntelMPI após #91.

**Estimativa (Sprint 13): 4h**

# Impactos

Não há impactos.

# Dependências

- [x] #91 

# Solução

1. Realizar os passos da issue #91  que compila o MPAS com compilador INTEL.

2.  Baixar os dados de benchmark com resolução de 15km:
~~~
wget https://www2.mmm.ucar.edu/projects/mpas/benchmark/v6.x/MPAS-A_benchmark_15km_L56.tar.gz
tar xzvf MPAS-A_benchmark_15km_L56.tar.gz
~~~

3. Criar um script básico para submissão submit_atmosphere.sh (este já usa o esquema de organização dos resultados em pastas criado por RPS):
~~~
#!/bin/bash
#SBATCH --nodes=2 
####SBATCH --tasks-per-node=128
#SBATCH --ntasks=256               #Numero total de tarefas MPI
#SBATCH -p PESQ1                  #Fila (partition) a ser utilizada
#SBATCH -J MPAS-V6.3       #Nome job
#SBATCH --time=12:00:00          #Obrigatório
#sbatch --mem-per-cpu=64000M
###SBATCH --exclusive

executable=atmosphere_model

module purge
module load ohpc
module swap gnu9 intel/2021.4.0
module swap openmpi4/4.1.1 impi/2021.4.0
module load hwloc
module load python-3.9.10-gcc-11.2.0-cf2iam6
module load cmake/3.21.3

. /mnt/beegfs/eduardo.khamis/usr/local/spack/github/spack_v0.18.1_oneapi/share/spack/setup-env.sh
export SPACK_USER_CONFIG_PATH=/mnt/beegfs/eduardo.khamis/.spack/spack_v0.18.1_oneapi
export SPACK_USER_CACHE_PATH=/mnt/beegfs/eduardo.khamis/.spack/spack_v0.18.1_oneapi/tmp
export TMP=/mnt/beegfs/eduardo.khamis/.spack/spack_v0.18.1_oneapi/tmp
export TMPDIR=/mnt/beegfs/eduardo.khamis/.spack/spack_v0.18.1_oneapi/tmp

export LC_ALL="en_US.UTF-8"

spack load --only dependencies mpas-model%intel@2021.4.0
spack load --list

module list
lscpu
env

resultdir=results/partition-${SLURM_JOB_PARTITION}/NUMNODES-$SLURM_JOB_NUM_NODES/MPI-${SLURM_NTASKS}/JOBID-${SLURM_JOBID}

mkdir -p ${resultdir}

#export MPAS_DYNAMICS_RANKS_PER_NODE=2
#export MPAS_RADIATION_RANKS_PER_NODE=6
#export MALLOCSTATS=1

ulimit -s unlimited

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export I_MPI_DEBUG=5
export MKL_DEBUG_CPU_TYPE=5
export I_MPI_FABRICS=shm:ofi

cd  $SLURM_SUBMIT_DIR
#ls  $SLURM_SUBMIT_DIR
#touch x1.2621442.init.nc 
echo $SLURM_JOB_NUM_NODES

date
echo "mpirun -np $SLURM_NTASKS ./${executable}"
mpirun -genvall ./${executable} 
#time mpirun -np $SLURM_NTASKS ./${executable} 
#mpirun -np $SLURM_NTASKS -mca btl tcp,self,vader -mca btl_tcp_if_include ib0 --bind-to core --map-by ppr:8:L3cache ./${executable}
#mpirun -np $SLURM_NTASKS -mca btl tcp,self,vader -mca btl_tcp_if_include ib0 -bind-to core -map-by core  ./${executable} 
date

cp slurm-${SLURM_JOBID}.out ${resultdir}/
cp log.atmosphere.*.out ${resultdir}/
cp namelist.atmosphere ${resultdir}/
cp submit_atmosphere.sh ${resultdir}/
mv x1.*.init.nc-*.lock ${resultdir}/
mv diag* ${resultdir}/
mv histor* ${resultdir}/ 

exit
~~~

4. Gerar arquivo de malha para a quantidade de cores que forem necessários e que não estiver disponível no pacote do benchmark (para 256 cores nesse caso):
~~~
carregar o modulo metis primeiro e depois usar o comando:

gpmetis -minconn -contig -niter=200 x1.2621442.graph.info 256

onde 2621442 é um número  fixo para resolução de 15km  e 128 é o número de processadores que irá usar.
~~~

5. Copiar o executável `atmosphere_model` da pasta padrão para a pasta do benchmark que deseja submeter os jobs.

6. Submeter um teste:
~~~
$ sbatch submit_atmosphere.sh
$ squeue -u ${USER}

~~~

7. Rodada finalizará com sucesso quando ao final do arquivo de saída do modelo `log.atmosphere.0000.out` conter uma mensagem semelhante:
~~~
-----------------------------------------
 Total log messages printed:
    Output messages =                 6533
    Warning messages =                   3
    Error messages =                     0
    Critical error messages =            0
 -----------------------------------------
 Logging complete.  Closing file at 2022/09/27 20:38:37
~~~

# Problemas encontrados

**Comment by deniseiras** [comment]
Tarefas realizadas em grupo:
1 - Criar script para reprodução
2 - Eduardo conseguiu reproduzir o mesmo problema da 2021.5 com a versão 2021.4
3 - Renato deixou compilando com mesmo passo a passo do Eduardo
4 - Fizemos um diff do spec da Minerva e Egeon
5 - Alteramos as bibliotecas que estavam diferentes na Egeon: netcdf-fortran@4.5.3 ^hdf5@1.10.7 e deixamos instalando:

```
[denis.eiras@headnode testEduardo]$ spack spec mpas-model%intel@2021.4.0 ^intel-oneapi-mpi@2021.4.0 ^parallel-netcdf ^hdf5@1.10.7 ^netcdf-fortran@4.5.3
Input spec
--------------------------------
mpas-model%intel@2021.4.0
    ^hdf5@1.10.7
    ^intel-oneapi-mpi@2021.4.0
    ^netcdf-fortran@4.5.3
    ^parallel-netcdf

Concretized
--------------------------------
mpas-model@7.1%intel@2021.4.0 arch=linux-rhel8-zen2
    ^intel-oneapi-mpi@2021.4.0%intel@2021.4.0~external-libfabric~ilp64 arch=linux-rhel8-zen2
    ^parallelio@2_5_4%intel@2021.4.0~ipo+pnetcdf~timing build_type=RelWithDebInfo arch=linux-rhel8-zen2
        ^cmake@3.21.3%intel@2021.4.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-rhel8-zen2
        ^netcdf-c@4.8.1%intel@2021.4.0~dap~fsync~hdf4~jna+mpi~parallel-netcdf+pic+shared patches=de556da arch=linux-rhel8-zen2
            ^hdf5@1.10.7%intel@2021.4.0~cxx~fortran+hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo patches=2a1e311 arch=linux-rhel8-zen2
                ^pkgconf@1.8.0%intel@2021.4.0 arch=linux-rhel8-zen2
                ^zlib@1.2.12%intel@2021.4.0+optimize+pic+shared patches=0d38234 arch=linux-rhel8-zen2
            ^m4@1.4.19%intel@2021.4.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-rhel8-zen2
                ^libsigsegv@2.13%intel@2021.4.0 arch=linux-rhel8-zen2
        ^netcdf-fortran@4.5.3%intel@2021.4.0~doc+pic+shared arch=linux-rhel8-zen2
        ^parallel-netcdf@1.12.2%intel@2021.4.0~burstbuffer+cxx+fortran+pic+shared arch=linux-rhel8-zen2
            ^perl@5.26.3%intel@2021.4.0~cpanm+shared+threads patches=8cf4302 arch=linux-rhel8-zen2

[denis.eiras@headnode testEduardo]$ spack install mpas-model%intel@2021.4.0 ^intel-oneapi-mpi@2021.4.0 ^parallel-netcdf ^hdf5@1.10.7 ^netcdf-fortran@4.5.3
```

**Comment by egkhamis** [comment]
Refiz a compilacao com as libs diferentes da Minerva, conforme o Denis e o Renato tambem estão fazendo.
Aqui terminou e pude concluir com sucesso a compilação e execução do MPAS com pnetcdf na versao do intel 2021.4.0 (o mesmo deve funcionar para a 2021.5.0). Muito obrigado pelo esforço conjunto!
    Em terça-feira, 27 de setembro de 2022 17:19:45 BRT, Denis Eiras ***@***.***> escreveu:  
 
 


Tarefas realizadas em grupo:
1 - Criar script para reprodução
2 - Eduardo conseguiu reproduzir o mesmo problema da 2021.5 com a versão 2021.4
3 - Renato deixou compilando com mesmo passo a passo do Eduardo
4 - Fizemos um diff do spec da Minerva e Egeon
5 - Alteramos as bibliotecas que estavam diferentes na Egeon: ***@***.*** ***@***.*** e deixamos instalando:
***@***.*** testEduardo]$ spack spec ***@***.*** ***@***.*** ^parallel-netcdf ***@***.*** ***@***.***
Input spec
--------------------------------
***@***.***
    ***@***.***
    ***@***.***
    ***@***.***
    ^parallel-netcdf

Concretized
--------------------------------
***@***.******@***.*** arch=linux-rhel8-zen2
    ***@***.******@***.***~external-libfabric~ilp64 arch=linux-rhel8-zen2
    ***@***.******@***.***~ipo+pnetcdf~timing build_type=RelWithDebInfo arch=linux-rhel8-zen2
        ***@***.******@***.***~doc+ncurses+ownlibs~qt build_type=Release arch=linux-rhel8-zen2
        ***@***.******@***.***~dap~fsync~hdf4~jna+mpi~parallel-netcdf+pic+shared patches=de556da arch=linux-rhel8-zen2
            ***@***.******@***.***~cxx~fortran+hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo patches=2a1e311 arch=linux-rhel8-zen2
                ***@***.******@***.*** arch=linux-rhel8-zen2
                ***@***.******@***.***+optimize+pic+shared patches=0d38234 arch=linux-rhel8-zen2
            ***@***.******@***.***+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-rhel8-zen2
                ***@***.******@***.*** arch=linux-rhel8-zen2
        ***@***.******@***.***~doc+pic+shared arch=linux-rhel8-zen2
        ***@***.******@***.***~burstbuffer+cxx+fortran+pic+shared arch=linux-rhel8-zen2
            ***@***.******@***.***~cpanm+shared+threads patches=8cf4302 arch=linux-rhel8-zen2

***@***.*** testEduardo]$ spack install ***@***.*** ***@***.*** ^parallel-netcdf ***@***.*** ***@***.***

**Comment by luflarois** [comment]
Parabéns a todos! É muito bom saber que a equipe está entrosada. Vamos em
frente!

Em ter, 27 de set de 2022 19:51, Eduardo Khamis ***@***.***>
escreveu:
