### ISSUE TITLE
Escalabilidade - Egeon - MPAS - IntelMPI

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#98]
# Descrição

Rodar modelo MPAS de 1 a 32 nós (step 1, 2, 4, 8, 16, 32) com resolução de 15km (usar a tarefa de execução anterior) com previsão de 12 horas na Egeon utilizando IntelMPI.

**Estimativa: 17h**

# Impactos

Não há impactos.

# Dependências

- #91 
- #95 

# Solução

1. Realizar os passos da issue #91  que compila o MPAS com compilador INTEL.

2. Realizar os passos da issue #95  que executa o MPAS com compilador INTEL.

3. Repetir o procedimento alterando o número de nós e processadores no script de submissão. 

4. Resultados com três repetições em cada configuração (com 64 e 128 processadores por nó) podem ser encontrados na Egeon nas pastas:
 /pesq/share/dmdcc/dist/monan/issue_98/results
 /pesq/share/dmdcc/dist/monan/issue_98/results_64pn
ou por ftp:
[http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/issue_98/results](http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/issue_98/results)
[http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/issue_98/results_64pn](http://ftp.cptec.inpe.br/pesquisa/dmdcc/monan/issue_98/results_64pn)

# Problemas encontrados

- Quando utilizado o número total de processadores (128) em 32 nós, a escalabilidade ficou degradada. Para resolver esse problema, metade dos processadores em cada nó foram utilizados com o custo de um tempo um pouco maior no processamento.

**Comment by egkhamis** [comment]
Ao apresentar tabela de resultados por e-mail, o Pablo do grupo GAM solicitou comparação com resultados da compilação/execução do MPAS na Egeon com compilador gnu9 e openmpi do seu grupo e uma integração do modelo para previsão de 10 dias utilizando na execução 16 nós da Egeon. Para isso, o seguinte procedimento foi feito:

- Realizou-se os passos da issue #91 e foi feita/solicitada uma única alteração no processo. Durante a criação do shell script para compilar o MPAS
**make_oneapi_egeon.sh**, a linha com o comando make foi alterada de:
```bash
make -j 8 ifort CORE=atmosphere OPENMP=true USE_PIO2=true PRECISION=single 2>&1 | tee make.output
```
para a opção **OpenMP=false**, ou seja:
```bash
make -j 8 ifort CORE=atmosphere USE_PIO2=true PRECISION=single 2>&1 | tee make.output
```

- Comparações entre Timing integration steps foram observadas.

- Resultado com **OpenMP=true**

Tempo de integração para previsão de 9h utilizando 128 cores por nó:

nós    tempo total (segundos)
16           572

- Resultado com **OpenMP=false**

Tempo de integração para previsão de 10 dias utilizando 128 cores por nó:

nós    tempo total (horas)
16           2h48min

- Tempo para completar tarefa: 8 h
